### ISSUE TITLE
detailed changelog on forums

### ISSUE THREAD

**Issue by Lightforger** [r888888888/danbooru#1091]
This might be good for the regular (forum) users to keep track of what changes.

I already have a format in mind, just wanted to ask if there are any changes that shouldn't be posted (like, things related to security / possible vulnerability & such - since many check the forums, but not git).

**Comment by Type-kun** [comment]
I'd like to reopen this. Actually, changelog is necessary, sometimes useful features go unnoticed by other users, who don't frequent github, for months.
There's one thing through, I'm pretty sure that changelog should be a wiki page, not a forum thread. This way, more recent changes can be posted first, the older changes last, which is more common changelog format; also, any user who feels like it can describe the changes, without waiting or wasting anyone's time.

If we agree that it's a good idea, I can populate the page to some extent using older forum posts and commits. Also, perhaps version number in the footer should link to it.

**Comment by ToksT** [comment]
For the record, the [releases](https://github.com/r888888888/danbooru/releases) page on github would be helpful for creating such a changelog, since the releases page lists each version number with what the last commit was for that version.

**Comment by r888888888** [comment]
I can start documenting the release tags on Github and crosspost to Danbooru. If the goal is informing users about changes though maybe the wiki isn't the best place for it. Add a news update linking to Github maybe?

**Comment by Type-kun** [comment]
Actually, the goal is to both inform users of changes and to list all the new functions danbooru got since v2, so that any user could just take a quick look at changelog, older entries included, instead of thinking "was that a bug or a feature I just encountered" or "how the hell did I do that". News ticker is better reserved for major changes, like it was earlier.

Also, I want the changelog to be community-driven because there were at least three attempts (I think) to keep the changelog in the forums, and all three stopped rather quickly. Though, perhaps it could be a file on github instead of a wiki on danbooru, so that any collaborator could fill it, not just any user?

**Comment by ToksT** [comment]
> Though, perhaps it could be a file on github instead of a wiki on danbooru, so that any collaborator could fill it, not just any user?

In that case it may make more sense to use the releases page I linked earlier. If you go to the release you want to write a changelog for and click "Edit tag" there's a field to write a description of it. I think any collaborator can edit these. Here's what it looks like for a repo that uses them: https://github.com/rgrove/sanitize/releases

**Comment by ToksT** [comment]
btw I just found a way to see commits for a specific version:

The page https://github.com/r888888888/danbooru/compare/2.59.0...2.60.0 shows changes made in v2.60. You need to type the begin and end versions manually.

**Comment by Type-kun** [comment]
[Tried it out](https://github.com/r888888888/danbooru/releases). Seems fine to me, except that it now lists me as a releaser :3

**Comment by Type-kun** [comment]
Will keep a changelog in a gist for now: https://gist.github.com/Type-kun/eccddd3aea50a86bfe58 and populate it more tomorrow; grammar and content check before it goes live to `releases` will be much appreciated. Also, it really was necessary, since it turns out that I myself wasn't aware of some recent features, either, even though I try to keep an eye out for those.

**Comment by ToksT** [comment]
>Aliased tags are included in autocomplete (currently broken due to delayed job failure)

This feature uses a daily maintenance task, not a delayed job

>Animated images always display originals, no more samples

Maybe mention gif/apng specifically? Ugoira still have samples.

**Comment by Type-kun** [comment]
Done in the same gist up to 2.56.0. Check appreciated as before.
Will fill releases up to 2.70 now.
This turned out to be way harder than expected, probably gonna stop at some point, but gonna continue for tomorrow at least.

**Comment by ToksT** [comment]
>Last note time wasn't updated sometimes, caused bugged notes

Technically last_noted_at was being updated, it was just being set to an *outdated older value* instead of a newer one.

Maybe simplify it to "Fix some notes temporarily disappearing" since most people will probably just want to know about the effect it had.

>When artist name is already taken, notice contains link to thtat artist

thtat

>Popular posts, pools, appeals and flags pages now have blacklist controls

I think popular already had it before that.

**Comment by Type-kun** [comment]
>I think popular already had it before that.

Perhaps; it had `render "blacklists"` but was changed to render partials. This was done in commit 1fffc2977f641c6087f39635aeb9e65ca9036685, for reference. That said, updated.

**Comment by ToksT** [comment]
> Perhaps; it had render "blacklists" but was changed to render partials.

Yeah, those are the same partial, I renamed it so that pools/flags/appeals could use the same partial that popular did.

**Comment by ToksT** [comment]
@r888888888 Apparently github makes it so "Draft" releases are only visible to collaborators, regular users can't see them until they're published
