### ISSUE TITLE
Searching for specific tags using the changes search

### ISSUE THREAD

**Issue by RenimLS** [r888888888/danbooru#1335]
I've run into the issue of needing the ability to search specific tags and find out when changes have occurred to posts involving those tags (particularly the removal of a tag).  The only idea I currently have for this is being able to search for tags in the changes search (currently only allows searching by user and by post).

Whatever mechanism is devised would need to be able to aid in drudging up posts that used to tagged with a tag, especially a low population tag, that was then removed from the image.  There has been a tendency to kill low population tags, and trying to find out if the images were migrated to another tag or just simply the tag was discarded has proven to be difficult.

**Comment by r888888888** [comment]
We now have the resources to store this kind of data in a separate database so as to not affect everyone else. It could even slurp the versions data from isshiki. The question is what's the best way to store this data. Is Postgres still the best answer? With queries like this we don't need atomicity, isolation, durability, and small consistency errors aren't a big issue.

**Comment by r888888888** [comment]
I plan on using Google BigQuery to house all the versioning data. Storing the diff would be interesting...but would make export vastly slower. Considering this is a table with millions of rows, it'd be simpler to just do a 1-to-1 export into BigQuery and pull up the diff when a query is requested.

**Comment by Type-kun** [comment]
The thing is, this is most useful when searching for _changes_. Finding all post versions that removed the tag "X" for example, to monitor vandalism or research tag nuking. Also finding out who exactly is populating the posts with tag "Y". Simply searching the versions for the presence of tag wouldn't give much info, alas - if this is getting an implementation, it would be better to make it useful right off the bat.

I understand how this would make the export slower, but does it really matter if it's an async delayed job? Granted, initial population would be slow, but after that it'll take as much processing as showing tag history for post, and initial population can be done in leisure. I'd say that diff should be calculated on Danbooru's side and then pushed together with version number, if only because it allows to handle version merging properly. Pulling up the diff on query is going to be extraordinarily slow, because it's a window function that requires a fullscan and can't be indexed.

**Comment by r888888888** [comment]
You make good points and the initial export seemed fast enough so I'll add the diff info.

**Comment by r888888888** [comment]
Now the question is what sorts of queries people want to be able to run.

**Comment by r888888888** [comment]
This is now available at http://danbooru.donmai.us/reports/post_versions

Some caveats: This does a simple substring search so you will get back partial matches. It's possible to run regular expression searches to get around this, but that necessitates extra escaping.

**Comment by Type-kun** [comment]
You mean, searching for `foo` will also yield changes for `foobar`? That's a bit troublesome. If these are space-delimited, you could search for `' '||needle||' '` in `' '||haystack||' '`, unless it further slows down the query.

Also, does bigdata support reverse indexes/full-text search? Substring search is bound to be pretty slow, it's always a fullscan.

**Comment by r888888888** [comment]
I've implemented the regexp solution which seems to work without any further data changes.

AFAICT BigQuery doesn't really have any concept of indexes. By limiting the data types every query is basically the same. On the data set the queries seem fairly fast though, within 5 seconds, so maybe it makes sense to make this report synchronous.

**Comment by Type-kun** [comment]
5 seconds, is it. When I tried it this morning, it took about 10 minutes for mail to arrive, but now it works within a minute. Synchronous is OK, and it would probably also allow pulling all the version info from main DB immediately, based on version numbers. E-mail is good in a sense that info is saved somewhere, though. I've thought about assingning an ID to every search, saving a `<search_ID>.json` file with resulting version IDs, creating a page that would display versions based on a data in specified json file, and then linking that page in dmail when the report is done; but if it's actually done within seconds, that's a definite overkill.

**Comment by r888888888** [comment]
Well I don't think there are any guarantees about how long queries take which is why you may see some variation.

**Comment by Type-kun** [comment]
Used the report a few times, it's proving to be quite handy. One last question though - when does synchronization occur? More specifically, does it handle merged versions correctly?

**Comment by r888888888** [comment]
I suppose it's possible that the sync to BigQuery (which basically happens every few minutes) happens in between version merges. So that is a potential source of inconsistency.

**Comment by r888888888** [comment]
I can also add additional search parameters like looking up by user or ip address or post. Everything in the versions table is in the BigQuery table so it should all be searchable.

**Comment by Type-kun** [comment]
> I suppose it's possible that the sync to BigQuery (which basically happens every few minutes) happens in between version merges. So that is a potential source of inconsistency.

Hmm, that's not good enough. It'll quickly become inconsistent since versions are merged within an hour (if I read the source code correctly), and many people add tags gradually. Can version merge trigger BigQuery update? Additional index on "changed" column might be too expensive. Then again, it might be not, and it's the simplest solution.

By the way, does BigQuery support "upsert" operation?

>I can also add additional search parameters like looking up by user or ip address or post. Everything in the versions table is in the BigQuery table so it should all be searchable.

As an additional filter, yes, it can come in handy. IP address should be searchable without any other parameters to catch vandals.

**Comment by r888888888** [comment]
Unfortunately data on BigQuery can't be updated (one of the caveats to it being fast). Maybe a better compromise is to just not sync anything unless it's at least X hours old.

**Comment by Type-kun** [comment]
Hmm, no updates is troublesome. Then yes, not syncing a version until it's 1,5 hrs old is a good idea, but it won't work with current implementation (saved last ID), you'll probably need index on "changed" column after all.

**Comment by Type-kun** [comment]
I don't think https://github.com/r888888888/reportbooru/commit/20497ec87ed1b38e626ddf6bdb42aa28a1bfcb2d fixes it - imagine if you have version 1, then version 2 on another post, then 50 minutes later version 1 gets updated. Eventually, version 2 will be sent to BigQuery, and when that happens,  `last_id` will be set to 2. So, version 1 will never get to BigQuery since next queries will go with `id > 2` condition.

I'm not sure what's the best way here. You can get rid of `id` conditions and go with `updated`, saving the last synced version `updated` instead of last ID; then go with say three hour window instead of 5000 versions window. This would require another index on `updated` though, not sure how well it would perform. 

Another way is to create a sort of sliding ID window - mark synchronized versions in database column (no index required), then have `last_id` store the _earliest_ **un**synchronized version id. That would require getting  `and updated_at < ?` out of query into an `if` block, adding `is_synchronized` column into the query, and ordering query results by `id asc`. 

Second way will get inefficient in the off-chance if there's some constantly updated version in the beginning of the batch. Say, in batch of IDs from 1 to 5000 all versions get synchronized except 3 which was just updated. So `last_id` is set to 3, and next updates will try versions 3 through 5002 until 3 is finally old enough to get synchronized. So, perhaps rewrite the query to use limit? `select ... where id >= last_id and is_synchronized = 0 and updated_at < ... order by id asc limit 5000`. I'm not exactly sure, but it should, theoretically, perform well enough, using index on `id`.

**Comment by r888888888** [comment]
How about updating the version id whenever it gets updated. It still maintains the relative ordering but makes sure it gets pulled into the next sync. The only issue is BigQuery will have (older) versions that aren't in Postgres, but that's not a huge issue.

**Comment by r888888888** [comment]
Alternatively, disable the merge but delete the older version.

**Comment by Type-kun** [comment]
>Alternatively, disable the merge but delete the older version.

This would work. ID and `updated_at` will always correlate this way. The only side-effects are ID gaps and updates on ID index, and that it might break some third-party apps, since versions didn't vanish before. 
Another way is to leave the merge, but merge within an hour of version _creation_ rather than last update. That said, creation date doesn't seem to be stored separately in DB.

**Comment by Type-kun** [comment]
Unless I'm missing something, with 917e42ed29ef7cf2484f6db4a77a99b579fffa02, ID and updated_at should always be in the same order. Now, version database should be regenerated once to account for all the errors made, and this can be considered implemented. This tool may not be used often, but when it is necessary, it's very useful, so thank you for tackling the issue.

That said, since the report could be made synchronous, how about improving the UI? More exactly, displaying the usual [version interface](https://danbooru.donmai.us/post_versions) once IDs are obtained from the reportbooru. I can try to work UI myself, but I'll need the initial synchronous report to use as a base. Something like what's currently displayed in E-Mail, list of version ids, will be enough.

**Comment by r888888888** [comment]
Please reopen if still desired.
