### ISSUE TITLE
CSS in note "style" attributes is not sanitized

### ISSUE THREAD

**Issue by kxz** [r888888888/danbooru#1932]
It's possible to sneak in JavaScript XSS attacks via `url(javascript:...)`, cover the UI with fixed positioning, etc. I question the need for whitelisting the `style` attribute at all — as far as I can see, virtually all of the notes that use it, use it for effects that can be accomplished with `<font size color bgcolor>` — but if it's allowed, it definitely needs to be cleaned up before it's presented to the user.

Rails 3.2 [includes a CSS sanitizer helper](http://api.rubyonrails.org/v3.2.12/classes/ActionView/Helpers/SanitizeHelper.html), so that is probably a good starting point.

**Comment by ToksT** [comment]
Sanitize started sanitizing css by itself when I updated it, so fixed. You can see a list of which properties are currently allowed [here](https://github.com/rgrove/sanitize/blob/c179467c1e0ad72b33d15e1a8567dd5460667c97/lib/sanitize/config/relaxed.rb#L46-L526), this can be customized if needed.

**Comment by kittey** [comment]
I’m not exactly sure how Sanitize handles CSS, but shouldn’t removing `http` and  `https` from `:protocols => ['http', 'https', :relative],` take care of many XSS issues in CSS because then only site-relative URIs would be allowed?

Maybe `http` and  `https` should also be removed from the allowed protocols for `del`, `img` and `ins`, preventing CSRF via those tags.

Sanitize is only used for notes, right? I don’t see any reason to allow access to any site-external resources there and we probably don’t want that anyway. We probably don’t even need site-relative URIs in there.

**Comment by ToksT** [comment]
> I’m not exactly sure how Sanitize handles CSS, but shouldn’t removing http and https from :protocols => ['http', 'https', :relative], take care of many XSS issues in CSS because then only site-relative URIs would be allowed?
> 
> Sanitize is only used for notes, right? I don’t see any reason to allow access to any site-external resources there and we probably don’t want that anyway. We probably don’t even need site-relative URIs in there.

Are there any xss issues?

Either way, I agree that loading images in notes doesn't seem like it has legitimate usage so I'll disallow urls in css.

> Maybe http and https should also be removed from the allowed protocols for del, img and ins, preventing CSRF via those tags.

Danbooru doesn't allow del img and ins html tags in notes to begin with.

The only tag that Danbooru allows any URL protocols in is `<a href="...">`, which I don't think we should disallow, since it's [commonly used](https://danbooru.donmai.us/notes?utf8=%E2%9C%93&group_by=note&search[body_matches]=*href%3D%22http*) in translator notes.
