### ISSUE TITLE
Random image link / order:random metatag

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#1938]
[Topic 9728](http://hijiribe.donmai.us/forum_topics/9728), while proposing redundant (IMO) browsing functions, contains a nice idea of introducing random post link/ordering metatag. I think we used to have something like that back in D1, but maybe I'm just being delusional.

What I'm suggesting is:
1) "random post" link, either somewhere in the lower left corner of the post page or in the post subnavbar. The point is to allow easy browsing of random images.
2) `order:random` metatag, or something alike. To allow viewing (`user_post_limit`) random images at once, probably also without any pagination, and, more importantly, to allow combination with other tags.

Single-post random view would be a perfect fit to slideshow mode, but it seems too difficult to smoothly integrate it, at a glance.

Actual `order by random()` query is very expensive; however, postgres offers [offset](http://stackoverflow.com/questions/5297396/quick-random-row-selection-in-postgres) which seems to fit our case. Granted, it has a non-zero chance of returning an image twice, but it's a possibility we can safely ignore on large sets, and on smaller sets we can use `order by random()`. To execute random offset query we need to know the row count anyway, so we can (hopefully) branch the query logic accordingly.

This seems interesting, but may prove difficult to implement, especially if I'm overlooking something again.

**Comment by Type-kun** [comment]
Ok, it seems that `order:random` is pretty much impossible to do properly without it being horribly slow. The only ways I can think of are to pre-generate random offsets and union-all multiple queries using different `OFFSET` each time, but that would mean actually executing the query N times repeatedly; or use ROW_NUMBER analytical function in subquery, and then using `in` on that column, but that'll have the same cost as `order by random()`. Oracle has `rownum` appropriate for that, but bo such luck in postgres. So I give up on that.

Regarding random post link, I have one weird issue - it feels like post distribution isn't exactly random, as certain post come up more frequently then others, even while browsing fairly large sets (600+ images); but that needs proper confirmation and another issue if confirmed.

**Comment by ToksT** [comment]
I implemented it the way Albert mentioned, executing the query repeatedly and putting the random posts together in an array. To activate this you need to manually add &random=true to the end of a post search url.

It might be on the slow side if the user tries it on the main /posts page (since that's 2 million posts). But for queries that have a reasonable number of posts (which are what I intend to use it for) it seems reasonably fast.

**Comment by Type-kun** [comment]
It can get you a lot of duplicates on smaller sets - `rand(count)` can return (0,1,3,1) on `count=4` - if I'm reading the code correctly. Also, perhaps do a union? Should save some query parsing time.

**Comment by ToksT** [comment]
> Also, perhaps do a union? Should save some query parsing time.

Like sticking all the individual queries together into one query with UNION ALL between them? It doesn't seem any faster.

**Comment by ToksT** [comment]
So I tested it on the live site and it's actually pretty slow... it's taking like 8-9 seconds to complete the searches I'm doing, which I think is too slow. If I lower my posts-per-page to 20 it's more like 3-4 seconds, but still.

So instead I tried testing the performance of the originally suggested `order by random()` on my server. Surprisingly, it turned out to be 3-4 times *faster* than this new method of getting a bunch of individual posts and putting them together.

@r888888888 What do you think, can we try going back to `order by random()` to see if it's fast enough? I know you said it was too slow, but were you only testing it on huge queries, like the main /posts page with 2 million posts? That's going to be slow either way ([give it a try](http://danbooru.donmai.us/posts?random=true) with the current implementation), so we may as well disallow order:random for huge queries with over, say, 100,000 posts. For smaller queries I hope it will be fast enough.

**Comment by Type-kun** [comment]
It looks like OFFSET search still requires full scan until the required row, so it's executed as much times as many posts you have. Perhaps, if there are large offsets and many posts, it will total to scanning more rows than actual full scan using random. If there was a way to pass list of offsets to a single query it would actually work better, but it seems impossible to implement even with custom psql extension.

Regarding the implementation, there are some suggestions to create a "random column" and update it periodically. Maybe look that way? It's not truly random of course, but if updated daily it could be of some use.

**Comment by r888888888** [comment]
This query seems faster:

```sql
explain analyze SELECT  "posts".* FROM "posts"  WHERE (true) AND (posts.tag_index @@ to_tsquery('danbooru', E'(''underwear'')')) AND random() < 0.01 LIMIT 20;

Limit  (cost=0.00..108.38 rows=20 width=1094) (actual time=0.275..33.203 rows=20 loops=1)
  ->  Seq Scan on posts  (cost=0.00..380108.12 rows=70142 width=1094) (actual time=0.273..33.189 rows=20 loops=1)
        Filter: ((tag_index @@ '''underwear'''::tsquery) AND (random() < 0.01::double precision))
        Rows Removed by Filter: 20337
Planning time: 2.502 ms
Execution time: 33.272 ms
```

This is versus 1200ms for the order by, and that's with the cache primed. The downside of this query is that it's not really that random. You're not even guaranteed to get back 20 posts if the tag is small enough. Maybe the X could be determined using a function mapping the post count.

**Comment by r888888888** [comment]
Although that query is fast enough that it could be executed in a loop, increasing X with every iteration until you get the number of posts you want.

**Comment by ToksT** [comment]
Oh that seems really good. I expected it to be too clustered towards the higher post ids at first, but since there's no `order by` clause the pseudo-random order the database returns the posts in seems to help prevent that.

Even though I doubt it's truly a random distribution it seems pretty rare for a post to show up more than once, so it's probably good enough.

**Comment by r888888888** [comment]
Actually I think if you set X to something like (20 / post count) the distribution will be fairly uniform. I think the hard part is when you get less than 20 posts. If for example you get 16 posts back, I think you'd need to set X to (4 / post count) and even then the results would be slightly skewed towards the newer posts.

This is hard to do for metatags or multi-tag searches since the post count isn't cached then.

**Comment by ToksT** [comment]
> Actually I think if you set X to something like (20 / post count) the distribution will be fairly uniform.

Implemented it this way

> I think the hard part is when you get less than 20 posts. If for example you get 16 posts back, I think you'd need to set X to (4 / post count) and even then the results would be slightly skewed towards the newer posts.

It seemed like the (blank spots / post count) method was too slow and caused timeouts when I tested it, so for now I didn't do it that way. Even though the way I did it is going to skew the fill-in posts towards newer posts I don't think it will be very noticeable. When fill-in posts are necessary it's only like 1-2.

**Comment by ToksT** [comment]
Seems pretty fast for a lot of searches. Tags with only a few thousand posts or less, certain combination searches, and the main /posts page are really fast. Tags with tens or hundreds of thousands of posts are slower, taking 4-5 seconds. Not ideal but I'd say it's pretty usable now.

**Comment by r888888888** [comment]
Performance will probably be linear to set size since it's essentially a sequential scan.

**Comment by ToksT** [comment]
> Performance will probably be linear to set size since it's essentially a sequential scan.

That's what I expected at first too but it doesn't seem always true. Examples:

`genderswap` has 16k posts, takes 4 seconds
`bat_wings remilia_scarlet` also has 16k posts, but takes less than half a second
`bat_wings` has 25k posts, takes 4 seconds
`remilia_scarlet` has 31k posts, takes 4 seconds

`solo` has 1.1 million posts, takes 4 seconds
/posts has 2 million posts, but takes a small fraction of a second
`underwear` has 212k posts, takes 4 seconds
`smiles has 428k posts, takes 4 seconds

`from_behind looking_back` has 15k posts, takes half a second
`bandages` also has 15k posts, but takes 4 seconds
`from_behind` has 28k posts, takes 4 seconds
`looking_back` has 57k posts, takes 4 seconds

Kind of a weird pattern, where everything either is fast or takes 4 seconds on average (they vary a bit between 3-5 seconds).

**Comment by r888888888** [comment]
That consistency is strange. It sounds like it's hitting a statement query timeout somewhere.

**Comment by ToksT** [comment]
I tested those queries I mentioned earlier on my server this time, and strangely they don't have the same problem of taking 4 seconds. They take less than a second on my server.

> That consistency is strange. It sounds like it's hitting a statement query timeout somewhere.

Any idea what part specifically is timing out? I can't figure it out with my server not doing it, but it must come down to three possibilities:

* The Post.fast_count call
* The main query where it gets most of the posts
* The 3x loop where it fills in the missing spots
