### ISSUE TITLE
Suggestion: Add fields for Japanese names & series name in character wiki

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#1961]
Similar to how **Artist -> Other Names** and **Artist -> Group** function, I am suggesting that character wiki entries should have fields where the user can add the kana/romaji name(s)/Pixiv tags, and series name (respectively).

This might help with automation of character/series tags.

**Comment by ToksT** [comment]
As far as the field for series name mentioned in the OP: I don't know if this is that useful since you can already check this by doing a related tags search, copyright is usually the first or second thing for a character's related tags. And what kind of "automation" would this field be used for?

Anyway if you still feel that it's really necessary then create a new issue, I'm closing this since it was mostly for the Japanese names feature which is fixed.
