### ISSUE TITLE
Hide banned artist info in more places

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2132]
- [ ] Wiki excerpt in post listing
- [ ] Wiki history
- [ ] Wiki page

**Comment by ToksT** [comment]
This is very buggy at the moment. It isn't hidden on:
* wiki page version
* wiki page version diff
* wiki /edit page
* wiki excerpt on post listing
* artist
* artist /edit page
* artist history

In other words, it's only hidden on the wiki page.

**Comment by ghostrigger** [comment]
regarding viewing banned artist entries in the artist db (including urls, histories), well, should be re-enable for builder+ i guess. there's an on-going discussion staring in http://danbooru.donmai.us/forum_topics/9127?page=113 . i'll pull out relevant replies to avoid mixing with other issues.

> ghostrigger said:
also the banned artist entries are obscured including the urls, history in the web interface. surely, this is a good thing against vandalism.

> i didn't check it yet, but is it possible to still edit banned entries in API? for example you discovered new urls or merge the same banned artist with a different name. for people not familiar with API, this might be a little inconvenient since privileged(?) users are also affected (well, at least in builder level). just some personal observations.

> RaisingK said:
>> ghostrigger said: 
>> i didn't check it yet, but is it possible to still edit banned entries in API?

> Works for me.

> ghostrigger said:
good thing API is working. just thinking those unfamiliar with scripting would be at a disadvantage since the web interface is the easiest. just my 2 cents.

> Kikimaru said:
Fuck.

> I use these to visit artists' sites, and occasionally add their new sites/aliases. 
Not happy with this obscuring of information.

> MyrMindservant said:
Same here, I also visited such pages for links to artists' websites. 
Honestly, I don't see a reason why the information should be completely hidden. Artists only benefit from it since it directs people to the websites and pages/accounts where they post their artwork. 
Preventing normal users from editing associated entries makes sense, but I think that it still should be possible for Builder+ users.

> tapnek said:
Same here.
>> MyrMindservant said:

>> Preventing normal users from editing associated entries makes sense, but I think that it still should be possible for Builder+ users.


>True, since normal users can't even see posts from banned artists to begin with.

> iridescent slime said:
Perhaps this is the reason why the banned artist entries were removed. Artists demand their images get taken down; we censor links to their webpages and deny them viewers. Tit for tat.

> I'm not saying this is a good thing, mind you. This is just speculation about why useful information would be made unavailable.

> richie said:
It would have some sense if also all source links from every single banned artist picture were hidden/removed.

> tapnek said:
I think it might be a better idea if Builders and above have access to the artist's info and the source links without using the API to edit while everyone else doesn't.

> Sacriven said:
Me too. 
Builder+ level users should be allowed to see the information. Not to mention that we're knowledgeable enough to not posts these banned artist' works anymore.
