### ISSUE TITLE
Using Docker for easy Installation 

### ISSUE THREAD

**Issue by Rina-Touin** [r888888888/danbooru#2139]
Hi! it would be really helpful for many if the installation guide was to be updated and implementing the Docker, so that Danbooru can be easily installed on many servers using Docker which makes installation easier for many.

The idea came from Discourse http://www.discourse.org/ , a free open source forum https://github.com/discourse They also use Ruby. 

Few referenced pages
https://meta.discourse.org/t/migrating-an-old-discourse-install-to-docker/12439

Docker 
https://github.com/discourse/discourse_docker
https://github.com/discourse/discourse/blob/master/docs/INSTALL.md

**Comment by r888888888** [comment]
Well, here's my first attempt:

https://registry.hub.docker.com/u/r888888888/danbooru/

This is mostly just running the install script on Ubuntu. I've created a simple script in the root home directory to finish configuration. Untested.

It doesn't install any gems except bundler. The idea is that you would check out Danbooru locally and cap deploy it to your docker instance, which will run bundler and install all the gems.

**Comment by r888888888** [comment]
It seems to be against standard practice to have sshd running in a docker container. This has implications for deployment (there are alternative capistrano recipes you can use to deploy to docker containers without ssh) and file distribution (no scp or sftp means some sort of http api needs to be devised).

**Comment by Rina-Touin** [comment]
Hi Albert. it says "404: The page you were looking for is not here..." when i checked your docker url. 

https://registry.hub.docker.com/u/r888888888/danbooru/

So can we use docker to easily install danbooru or we can't ?

**Comment by r888888888** [comment]
@Rina-Touin I've realized I don't need to create a custom Docker image when a Dockerfile suffices. It's in master now. It still needs some work but it's enough to give you a usable image.

**Comment by KarelWintersky** [comment]
Bump. Can I found usable image anywhere?

**Comment by r888888888** [comment]
I've gained a lot more experience with Docker since this issue was created so I can offer some insight.

Setting up Danbooru on Docker is tricky for a multitude of reasons. For one, dealing with all the required services is hard. You will need to spin up PostgreSQL and Memcached and Nginx and the delayed job workers in separate containers, and somehow manage the network connections between them if you don't want to expose everything to the internet. Configuration is hard. The config files could theoretically mounted on the host, but really it should be delegated to whatever orchestration service you use (keep in mind you have to configure not only Danbooru but Postgres and Nginx also). And the orchestration is hard. Whether you use Kubernetes or Swarm. It's almost required because you have to deal with multiple containers at once, presumably on multiple servers. And the current deployment scripts don't know how to deal with containers at all. I honestly believe all of this is more work than just following the install script.

I am experimenting with containerization on the [Danboorus fork](https://github.com/r888888888/danboorus) but that won't be ready for a long time.

The easiest way to set up a Danbooru instance currently is to rent a DigitalOcean droplet or something similar and run the install script line by line.

**Comment by KarelWintersky** [comment]
I installed debian in virtualbox. Then, I run install script line by line.
Installation failed at postgresql section :(

**Comment by KarelWintersky** [comment]
@r888888888 
> install script line by line.

install script is **OUTDATED** and does not work.
