### ISSUE TITLE
Failbooru when editing tags if long tag search

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2315]
Attempting to edit a post's tags usually gives me generic Failbooru page when I have a 2374-char query embedded in the tags parameter (the edit does go through, though).

As in, 
```
http://danbooru.donmai.us/posts/1683648?tags=id%3A951043%2C1597943%2C520774%2C527663%2C543005%2C553786%2C558461%2C563609%2C577299%2C597327%2C600862%2C630781%2C648767%2C675363%2C677427%2C686520%2C687856%2C687858%2C736023%2C744291%2C759191%2C243094%2C317851%2C318391%2C396172%2C409904%2C499589%2C540245%2C913289%2C351538%2C521659%2C828379%2C958654%2C958657%2C964015%2C965290%2C966381%2C976391%2C982251%2C986119%2C987776%2C988191%2C1000521%2C1003229%2C1013024%2C1016770%2C1025120%2C1025487%2C1028194%2C1032328%2C1043997%2C1051653%2C1052665%2C1053681%2C1054209%2C1059567%2C1060834%2C1064165%2C1070027%2C1073977%2C1076373%2C1078482%2C1080770%2C1082339%2C1084092%2C1084293%2C1084847%2C1087047%2C1090782%2C1096311%2C1096840%2C1096841%2C1097595%2C1098601%2C1099730%2C1101537%2C1101816%2C1107539%2C1109170%2C1111063%2C1115584%2C1118640%2C1124411%2C1125951%2C1128067%2C1130904%2C1132618%2C1132909%2C1133107%2C1135779%2C1142549%2C1144838%2C1148859%2C1149021%2C1153304%2C1153450%2C1155528%2C1155529%2C1157789%2C1159155%2C1565159%2C1566482%2C1582223%2C11277%2C549934%2C139282%2C843823%2C930735%2C656128%2C1838429%2C1597956%2C1642970%2C801796%2C1718421%2C1816092%2C1828887%2C1063076%2C813149%2C1718422%2C1806955%2C1089948%2C1799201%2C1799207%2C1799208%2C1799211%2C1799202%2C1799204%2C1801908%2C1490183%2C1490184%2C780032%2C1479857%2C1763421%2C1666433%2C1760479%2C1775907%2C760873%2C578958%2C600168%2C947994%2C1679151%2C1751064%2C1749461%2C1621355%2C1743285%2C1735561%2C745449%2C1587114%2C1148003%2C1148002%2C1609387%2C565111%2C1707871%2C1702196%2C1702195%2C1713638%2C362172%2C611542%2C364231%2C1683648%2C1682674%2C1686801%2C1696343%2C705200%2C499404%2C1671827%2C636921%2C1656097%2C1658058%2C1660475%2C1622110%2C1616871%2C1604312%2C1602907%2C1607514%2C1608157%2C1609529%2C1610209%2C1611515%2C1612339%2C1612463%2C433563%2C523988%2C570749%2C570976%2C672596%2C969144%2C762924%2C766352%2C766354%2C785376%2C793431%2C802196%2C829491%2C831662%2C862632%2C868644%2C892435%2C892447%2C897967%2C900632%2C900975%2C904630%2C904631%2C912432%2C926075%2C945891%2C1161310%2C1164332%2C1167599%2C1171236%2C1171336%2C1171338%2C1172123%2C1175351%2C1192321%2C1193008%2C1199279%2C1199729%2C1204560%2C1205799%2C1206688%2C1209515%2C1210357%2C1211874%2C1212796%2C1218758%2C1219085%2C1220261%2C1220275%2C1227497%2C1245072%2C1250971%2C1261159%2C1266540%2C1267014%2C1267401%2C1268756%2C1269215%2C1280814%2C1282426%2C1283766%2C1288609%2C1293773%2C1299089%2C1302478%2C1312363%2C1320914%2C1323388%2C1324631%2C1326082%2C1327044%2C1342733%2C1345455%2C1352377%2C1353400%2C1356404%2C1356580%2C1363895%2C1366990%2C1369684%2C1378063%2C1380995%2C1381390%2C1381587%2C1389576%2C1393010%2C1394083%2C1398329%2C1398331%2C1407006%2C1409393%2C1414439%2C1415236%2C1416591%2C1434011%2C1434841%2C1439106%2C1444009%2C1444311%2C1448891%2C1453270%2C1455578%2C1455581%2C1455585%2C1459022%2C1471167%2C1475448%2C1475872%2C1481167%2C1484190%2C1491837%2C1495523%2C1504480%2C1510138%2C1512952%2C650850%2C753984%2C763623%2C930553%2C957208%2C970109%2C1075383%2C1535951%2C1346728%2C1547423%2C1564343+status%3Aany
```
leads to a Failbooru of `http://danbooru.donmai.us/posts/1683648` (no 'tags' parameter).

Although the occasional timeout of the posts-with-comments count on my profile (i.e. "1000000 posts") makes me wonder if Danbooru is just having a bad night overall...

**Comment by Type-kun** [comment]
I decided to investigate this error one more time, and it's getting pretty weird. It still happens on danbooru.donmai.us, but I can't reproduce it neither on my local install nor on testbooru.

Due to the way it fails, I assume that POST request goes through (since changes are recorded properly), but nginx doesn't like the response from unicorn for some reason and doesn't deliver it properly. Perhaps it doesn't like `Location` in the redirect being so large? @r888888888 can you take a look at logs? It's quite clearly a configuration issue, but since all 50x errors are redirected to "Something broke" error page, it's impossible to determine anything except error code, which is 502.

Steps to reproduce:
1) Open the [link](http://danbooru.donmai.us/posts/1?tags=id%3A1%2C951042%2C951041%2C951043%2C1597943%2C520774%2C527663%2C543005%2C553786%2C558461%2C563609%2C577299%2C597327%2C600862%2C630781%2C648767%2C675363%2C677427%2C686520%2C687856%2C687858%2C736023%2C744291%2C759191%2C243094%2C317851%2C318391%2C396172%2C409904%2C499589%2C540245%2C913289%2C351538%2C521659%2C828379%2C958654%2C958657%2C964015%2C965290%2C966381%2C976391%2C982251%2C986119%2C987776%2C988191%2C1000521%2C1003229%2C1013024%2C1016770%2C1025120%2C1025487%2C1028194%2C1032328%2C1043997%2C1051653%2C1052665%2C1053681%2C1054209%2C1059567%2C1060834%2C1064165%2C1070027%2C1073977%2C1076373%2C1078482%2C1080770%2C1082339%2C1084092%2C1084293%2C1084847%2C1087047%2C1090782%2C1096311%2C1096840%2C1096841%2C1097595%2C1098601%2C1099730%2C1101537%2C1101816%2C1107539%2C1109170%2C1111063%2C1115584%2C1118640%2C1124411%2C1125951%2C1128067%2C1130904%2C1132618%2C1132909%2C1133107%2C1135779%2C1142549%2C1144838%2C1148859%2C1149021%2C1153304%2C1153450%2C1155528%2C1155529%2C1157789%2C1159155%2C1565159%2C1566482%2C1582223%2C11277%2C549934%2C139282%2C843823%2C930735%2C656128%2C1838429%2C1597956%2C1642970%2C801796%2C1718421%2C1816092%2C1828887%2C1063076%2C813149%2C1718422%2C1806955%2C1089948%2C1799201%2C1799207%2C1799208%2C1799211%2C1799202%2C1799204%2C1801908%2C1490183%2C1490184%2C780032%2C1479857%2C1763421%2C1666433%2C1760479%2C1775907%2C760873%2C578958%2C600168%2C947994%2C1679151%2C1751064%2C1749461%2C1621355%2C1743285%2C1735561%2C745449%2C1587114%2C1148003%2C1148002%2C1609387%2C565111%2C1707871%2C1702196%2C1702195%2C1713638%2C362172%2C611542%2C364231%2C1683648%2C1682674%2C1686801%2C1696343%2C705200%2C499404%2C1671827%2C636921%2C1656097%2C1658058%2C1660475%2C1622110%2C1616871%2C1604312%2C1602907%2C1607514%2C1608157%2C1609529%2C1610209%2C1611515%2C1612339%2C1612463%2C433563%2C523988%2C570749%2C570976%2C672596%2C969144%2C762924%2C766352%2C766354%2C785376%2C793431%2C802196%2C829491%2C831662%2C862632%2C868644%2C892435%2C892447%2C897967%2C900632%2C900975%2C904630%2C904631%2C912432%2C926075%2C945891%2C1161310%2C1164332%2C1167599%2C1171236%2C1171336%2C1171338%2C1172123%2C1175351%2C1192321%2C1193008%2C1199279%2C1199729%2C1204560%2C1205799%2C1206688%2C1209515%2C1210357%2C1211874%2C1212796%2C1218758%2C1219085%2C1220261%2C1220275%2C1227497%2C1245072%2C1250971%2C1261159%2C1266540%2C1267014%2C1267401%2C1268756%2C1269215%2C1280814%2C1282426%2C1283766%2C1288609%2C1293773%2C1299089%2C1302478%2C1312363%2C1320914%2C1323388%2C1324631%2C1326082%2C1327044%2C1342733%2C1345455%2C1352377%2C1353400%2C1356404%2C1356580%2C1363895%2C1366990%2C1369684%2C1378063%2C1380995%2C1381390%2C1381587%2C1389576%2C1393010%2C1394083%2C1398329%2C1398331%2C1407006%2C1409393%2C1414439%2C1415236%2C1416591%2C1434011%2C1434841%2C1439106%2C1444009%2C1444311%2C1448891%2C1453270%2C1455578%2C1455581%2C1455585%2C1459022%2C1471167%2C1475448%2C1475872%2C1481167%2C1484190%2C1491837%2C1495523%2C1504480%2C1510138%2C1512952%2C650850%2C753984%2C763623%2C930553%2C957208%2C970109%2C1075383%2C1535951%2C1346728%2C1547423%2C1564343+status%3Aany)
2) Click "edit", then "submit"
3) "Something broke" appears, location is `http://danbooru.donmai.us/posts/1` without get params, which matches the action in POST.
4) Open the same link [on the testbooru](http://danbooru.donmai.us/posts/1?tags=id%3A1%2C951042%2C951041%2C951043%2C1597943%2C520774%2C527663%2C543005%2C553786%2C558461%2C563609%2C577299%2C597327%2C600862%2C630781%2C648767%2C675363%2C677427%2C686520%2C687856%2C687858%2C736023%2C744291%2C759191%2C243094%2C317851%2C318391%2C396172%2C409904%2C499589%2C540245%2C913289%2C351538%2C521659%2C828379%2C958654%2C958657%2C964015%2C965290%2C966381%2C976391%2C982251%2C986119%2C987776%2C988191%2C1000521%2C1003229%2C1013024%2C1016770%2C1025120%2C1025487%2C1028194%2C1032328%2C1043997%2C1051653%2C1052665%2C1053681%2C1054209%2C1059567%2C1060834%2C1064165%2C1070027%2C1073977%2C1076373%2C1078482%2C1080770%2C1082339%2C1084092%2C1084293%2C1084847%2C1087047%2C1090782%2C1096311%2C1096840%2C1096841%2C1097595%2C1098601%2C1099730%2C1101537%2C1101816%2C1107539%2C1109170%2C1111063%2C1115584%2C1118640%2C1124411%2C1125951%2C1128067%2C1130904%2C1132618%2C1132909%2C1133107%2C1135779%2C1142549%2C1144838%2C1148859%2C1149021%2C1153304%2C1153450%2C1155528%2C1155529%2C1157789%2C1159155%2C1565159%2C1566482%2C1582223%2C11277%2C549934%2C139282%2C843823%2C930735%2C656128%2C1838429%2C1597956%2C1642970%2C801796%2C1718421%2C1816092%2C1828887%2C1063076%2C813149%2C1718422%2C1806955%2C1089948%2C1799201%2C1799207%2C1799208%2C1799211%2C1799202%2C1799204%2C1801908%2C1490183%2C1490184%2C780032%2C1479857%2C1763421%2C1666433%2C1760479%2C1775907%2C760873%2C578958%2C600168%2C947994%2C1679151%2C1751064%2C1749461%2C1621355%2C1743285%2C1735561%2C745449%2C1587114%2C1148003%2C1148002%2C1609387%2C565111%2C1707871%2C1702196%2C1702195%2C1713638%2C362172%2C611542%2C364231%2C1683648%2C1682674%2C1686801%2C1696343%2C705200%2C499404%2C1671827%2C636921%2C1656097%2C1658058%2C1660475%2C1622110%2C1616871%2C1604312%2C1602907%2C1607514%2C1608157%2C1609529%2C1610209%2C1611515%2C1612339%2C1612463%2C433563%2C523988%2C570749%2C570976%2C672596%2C969144%2C762924%2C766352%2C766354%2C785376%2C793431%2C802196%2C829491%2C831662%2C862632%2C868644%2C892435%2C892447%2C897967%2C900632%2C900975%2C904630%2C904631%2C912432%2C926075%2C945891%2C1161310%2C1164332%2C1167599%2C1171236%2C1171336%2C1171338%2C1172123%2C1175351%2C1192321%2C1193008%2C1199279%2C1199729%2C1204560%2C1205799%2C1206688%2C1209515%2C1210357%2C1211874%2C1212796%2C1218758%2C1219085%2C1220261%2C1220275%2C1227497%2C1245072%2C1250971%2C1261159%2C1266540%2C1267014%2C1267401%2C1268756%2C1269215%2C1280814%2C1282426%2C1283766%2C1288609%2C1293773%2C1299089%2C1302478%2C1312363%2C1320914%2C1323388%2C1324631%2C1326082%2C1327044%2C1342733%2C1345455%2C1352377%2C1353400%2C1356404%2C1356580%2C1363895%2C1366990%2C1369684%2C1378063%2C1380995%2C1381390%2C1381587%2C1389576%2C1393010%2C1394083%2C1398329%2C1398331%2C1407006%2C1409393%2C1414439%2C1415236%2C1416591%2C1434011%2C1434841%2C1439106%2C1444009%2C1444311%2C1448891%2C1453270%2C1455578%2C1455581%2C1455585%2C1459022%2C1471167%2C1475448%2C1475872%2C1481167%2C1484190%2C1491837%2C1495523%2C1504480%2C1510138%2C1512952%2C650850%2C753984%2C763623%2C930553%2C957208%2C970109%2C1075383%2C1535951%2C1346728%2C1547423%2C1564343+status%3Aany)
5) Click "edit", then "submit"
6) No error.

**Comment by r888888888** [comment]
It may just be a db timeout that was hidden by the bug in 800f7d9e5f37fd9f19826f3c6a462156f921198b

**Comment by Type-kun** [comment]
It still fails, and it's failing pretty fast for DB timeout, to be honest.

**Comment by Type-kun** [comment]
I'm highly suspicious that nginx complains about "header size":https://forum.nginx.org/read.php?2,188352 but only logs can tell.

**Comment by r888888888** [comment]
That seems to be the problem. Try now.

**Comment by Type-kun** [comment]
Yep, it seems to work fine now.
