### ISSUE TITLE
Associate tags with areas in the image

### ISSUE THREAD

**Issue by mock-** [r888888888/danbooru#2336]
It would be nice to have the ability to (optionally) associate a tag with a geometric area in the image, and have it so when you mouseover the tag, it highlights the associated area, and vice versa. This would be a slightly better way of doing character/item annotations, and could be used to find things that aren't immediately obvious, etc. Ideally it would be a complex shape (or multiple shapes), but a simple rectangle (like annotations) would be a start.

Potentially people could find other uses for that data. Maybe when searching for a tag, the thumbnail could zoom in on the associated part of the image, or maybe it could be possible to search for images where a particular character takes up most of the image. But the basic functionality would have to be there first.

**Comment by Type-kun** [comment]
It would require a relatively complex infrastructure to function properly. Currently, tags for each post are just a space-separated string, indexed for quick search - you can't really get any simpler than that, even normalizing tag-post relationships to separate table would seriously complicate search function, as vertical data isn't really search-ready. 

What you ask for *would* require a relationship table, for storing shape dimensions at very least. That would mean complicating tag editing process (tag string should be synchronized with relationship table). Also searches based entirely on that table are likely to be slow. Additionally, there are various UI problems: how are users going to mark shapes on the image or remove them? How would those shapes be displayed? How are those shapes going to interact with note rectangles already on the image? What happens when user mouse-overs both note and tag shape at the same time?

I can see how that would be useful for annotation/marking purposes, but there are few images that would use that feature, and then there are very few that can't be covered by notes and/or comments - only exceptionally crowded `absolutely_everyone`, probably. Can't decide for Albert or Toks to do or not do something, but I don't really think it's worth the trouble, unless you could implement it in your fork and make a pull request - then it'll be a matter of merging, not the matter of creating.

**Comment by r888888888** [comment]
I've considered using a system parallel to notes for this. But ultimately it's a lot of work (but in terms of implementation and maintaining the tag notes) and the gains are minimal versus inventing a new tag or refining your search query.
