### ISSUE TITLE
broken twitter image upload

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2337]
http://danbooru.donmai.us/uploads/new?url=https%3A%2F%2Ftwitter.com%2FStrangestone%2Fstatus%2F556440271961858051&ref= fails

**Comment by ToksT** [comment]
It seems to happen for tweets that have that "The following media may contain sensitive material." warning. Since the warning hides the image I assume Danbooru can't find the image on the page via normal means. So we'd need a way of detecting the image while it's still hidden.

Alternatively do what the message advises and make an account for Danbooru to use:
>If you'd prefer not to see these warnings, log in to change your Tweet media settings. Don't have an account? Sign up!
