### ISSUE TITLE
Change 'Create New'/show_or_new links for new-style pixiv uploads

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2340]
If a user is uploading from a new-style pixiv URL like `http://i2.pixiv.net/img-original/img/2014/10/13/03/05/51/16520535_p1.jpg`, make the `Create New` link use an old-style URL instead.

Also try to convert to old-style when redirected to the new artist page from a /show_or_new link.

**Comment by ToksT** [comment]
Unnecessary since #2266 was fixed. Even if a new-style url is added to an artist entry, the corresponding `normalized_url` for that url will be the old-style, so it will still work.

**Comment by RaisingK** [comment]
I was not aware that that issue was fixed, but I still think this has merit.  It shows the pixiv username at first glance, which is nice on its own and also helpful when naming a new artist.  I've also noticed two users creating artists with the filename truncated from a new style URL; perhaps this might help.

**Comment by ToksT** [comment]
> I was not aware that that issue was fixed, but I still think this has merit. It shows the pixiv username at first glance, which is nice on its own and also helpful when naming a new artist.

We could just show the normalized url next to the regular url simultaneously. That way it would always display even if the user manually adds a url, rather than only for urls automatically added on artist creation. This way we also avoid losing the information from the original url that's not in the normalized url (which may not matter, but it's better to preserve it in case it helps with debugging or something later).
