### ISSUE TITLE
Feature request: filter / tag artist by country of origin

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#2372]
Since some people only want to see art by Japanese artists, would it be possible to implement a way for users to tag an artist as "from XX country" on their artist wiki entry, and allow filtering to take place in user settings?

**Comment by ToksT** [comment]
Adding a new field when editing artist entries for their country is certainly possible, but filtering posts by this would be harder. The data would need to be mirrored to the post table via delayed jobs which might cause inaccuracies. There's also the performance of this filter to worry about, since it will be applied to all searches done by people that use this feature.

Personally I think it would be easier to just created a new `western_art` tag, and then people that don't like it can blacklist the tag. Doesn't need a new feature to be coded and won't have any bugs or performance problems guaranteed.
