### ISSUE TITLE
source:pixiv/moniker searches don't work for new-style urls

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2373]
New style pixiv urls don't have the artist moniker in them. This means source searches by the artist moniker don't work. The site is just indexing the number that comes right before the filename. So [post 1992264](https://danbooru.donmai.us/posts/1992264) gets returned by a [source:pixiv/46/](https://danbooru.donmai.us/posts?utf8=%E2%9C%93&tags=source%3Apixiv%2F46%2F) search, when it should be returned by [source:pixiv/akt0001203/](https://danbooru.donmai.us/posts?utf8=%E2%9C%93&tags=source%3Apixiv%2Fakt0001203%2F)

Related: #2261

**Comment by ToksT** [comment]
This was discussed a bit starting [here](https://danbooru.donmai.us/forum_topics/11014?page=3#forum_post_100682) and continuing for a couple posts. Basically we could create a new column on posts to store the artist moniker for this search to work. And use delayed jobs to populate it after upload to avoid uploads timing out, while we pray that the delayed jobs don't bug out or something.

**Comment by Type-kun** [comment]
>Basically we could create a new column on posts to store the artist moniker for this search to work. 

Or yet another hidden pseudo-tag. Another column requires additional index, as mentioned in the topic.

Delayed jobs should always try to fill out the blank spots, to avoid consequences of them bugging out, perhaps? So that the next scan would repair posts where previous one couldn't fetch anything. That is, when source domain is `*.pixiv.*`, and when artist_moniker field is blank, AND when bad_id tag is not present, then try to fetch the moniker. Perhaps, limit on the upload date, too, once the initial scans are complete.

**Comment by ToksT** [comment]
> Or yet another hidden pseudo-tag. Another column requires additional index, as mentioned in the topic.

A pseudo tag would not allow wildcard searches. So even though source:pixiv/moniker/ would return posts from a pixiv artist named "moniker", source:pixiv/mon* would not.

It's not a huge deal since wildcards aren't nearly as important with monikers as they are with regular source searches, but might be worth keeping in mind.

**Comment by Type-kun** [comment]
>A pseudo tag would not allow wildcard searches. So even though source:pixiv/moniker/ would return posts from a pixiv artist named "moniker", source:pixiv/mon* would not.

Uh, wait, I was almost positive we already had some "special" tags mixed into every tag strings, carrying additional info but not displayed. After examining the current code, turns out I was mistaken? I think I thought that since I saw #1039 a few years ago...

Either way, maybe it's time to. When I say "pseudo-tag", I mean literally an additional hidden tag in the posts' tag_string, not just search shortcut. It's already indexed to allow wildcard searches. The problem I didn't think of (since I thought f it as already implemented) is how to keep them up-to-date on post edits.

**Comment by ToksT** [comment]
> Either way, maybe it's time to. When I say "pseudo-tag", I mean literally an additional hidden tag in the posts' tag_string, not just search shortcut. It's already indexed to allow wildcard searches.

`tag_string` is not indexed to allow wildcard searches.

If you try to do a search like `*_eyes`, the site will return some results so I see why you'd think wildcard searches are supported. But this is just an approximation and is missing tons of results, it's not actually a wildcard search.

The way it works is it does a wildcard search on the *tags* table for `*_eyes` and takes the top N results (where N = the current user's tag query limit, 2 for basic users, 6 for gold, 12 for platinum+), then does an OR search on the posts table for them. So if I search for `*_eyes`, this is the sql query generated:

```sql
SELECT "posts".* FROM "posts"
WHERE (posts.tag_index @@ to_tsquery('danbooru', E'(''blue_eyes'' | ''red_eyes'' | ''brown_eyes'' | ''green_eyes'' | ''purple_eyes'' | ''closed_eyes'' | ''yellow_eyes'' | ''pink_eyes'' | ''aqua_eyes'' | ''black_eyes'' | ''orange_eyes'' | ''grey_eyes'')'))
ORDER BY posts.id DESC LIMIT 20 OFFSET 0
```

If I was a basic member it would use this query instead:

```sql
SELECT "posts".* FROM "posts"
WHERE (posts.tag_index @@ to_tsquery('danbooru', E'(''blue_eyes'' | ''red_eyes'')'))
ORDER BY posts.id DESC LIMIT 20 OFFSET 0
```

**Comment by ToksT** [comment]
Also, wildcard searches are weird in conjunction with OR searches because of that. You'd expect that `~1girl ~2girls *_eyes` would return only posts that have either (1girl OR 2girls), AND also have at least one *_eyes tag. Instead it returns posts that have (1girl OR 2girls OR at least on eyes tag).

**Comment by ToksT** [comment]
> It's already indexed to allow wildcard searches.

Oh I forget to get to my main point: since these fake wildcard searches rely on doing a wildcard search on the *tags* table, source:pixiv/moniker searches won't work here, since source:pixiv/moniker entries aren't in the tags table.

**Comment by Type-kun** [comment]
Oh, I see. I kind of presumed it was handled naturally by GIN fulltext index, it didn't even occur to me to look how is it implemented. Well, that simplifies things - there's no solution except separate column.
