### ISSUE TITLE
Automatically ban posts that are uploaded for banned artists

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2386]

**Comment by Type-kun** [comment]
On that note, automatically unban the posts when the artist is removed from banned_artists and there are no other banned artists on the post.

**Comment by ToksT** [comment]
> On that note, automatically unban the posts when the artist is removed from banned_artists and there are no other banned artists on the post.

Are you talking about when an admin unbans an artist entry? That already unbans all the artist's posts. Although, I don't think it currently checks the case of there being a second banned artist on the same post currently, it unbans it regardless. Maybe that should be fixed.

**Comment by ToksT** [comment]
>Automatically ban posts that are uploaded for banned artists

Is this only going to be done on upload? Or is it going to be done automatically every time the `banned_artist` tag is added/removed from a post?

If the former, Janitors will still need to manually ban a post if it wasn't uploaded with the artist's tag on it, and manually unban a post if it erroneously had an artist's tag on it during upload. This seems preferable since these cases probably aren't very common.

If the latter, it opens up the possibility of vandalism by someone adding/removing an artist's tag to a post in order to ban it.

**Comment by r888888888** [comment]
Only on upload makes the most sense I think.
