### ISSUE TITLE
Set post source to referer automatically

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2395]
Like #2328 but for tumblr. If the &ref param with the bookmarklet is a http://[artist].tumblr.com/post/[postid] url then set that as the source automatically on upload.

**Comment by ToksT** [comment]
see #2404

**Comment by r888888888** [comment]
I guess a question is whether users are going directly to the image and then using the bookmarklet, or using it from the HTML page. I assume the first is happening since for a long time that was the only way you could use the bookmarklet. Trying to normalize those back to the HTML page is doable, but I don't think the code currently has any concept of doing that.

**Comment by ToksT** [comment]
> I guess a question is whether users are going directly to the image and then using the bookmarklet, or using it from the HTML page. I assume the first is happening since for a long time that was the only way you could use the bookmarklet.

Yeah, I also think a lot of people use it on the image page since the official instructions say to do it that way, and some sites like tumblr don't support uploading from the work page, so they have to use the image page.

> Trying to normalize those back to the HTML page is doable, but I don't think the code currently has any concept of doing that.

I think we can pass the referer to the upload when it is submitted, then have the upload pass the referer to Downloads::File.new via an option, then have a call in after_download that fixes the source to point to the referer, with a conditional for each site.

**Comment by evazion** [comment]
This is now done for all major sites that need it (Twitter, Tumblr, Pawoo, Nijie, and ArtStation).
