### ISSUE TITLE
Pixiv API sometimes returns code 206 errors

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2398]
See http://danbooru.donmai.us/uploads/695783

The message is "対象のイラストは見つかりませんでした" which seems to translate to the work couldn't be found? Should probably trap on this error and just return an null object instead of blocking the upload.

**Comment by ToksT** [comment]
It seems the artist deleted the work quickly after posting it because he made an anatomical mistake and he reuploaded it with the mistake corrected: http://www.pixiv.net/member_illust.php?mode=medium&illust_id=50726250

Presumably this coincidentally happened just as someone was trying to upload it to Danbooru.

The work and all its metadata is gone from Pixiv, but it can still be accessed through the [direct image url](http://i1.pixiv.net/img-original/img/2015/06/05/00/30/47/50725912_p0.png) if pixiv referer is set. Though I think this is temporary and it will become inaccessible after a couple weeks or so.

**Comment by r888888888** [comment]
I guess this is rare enough not to worry about then.
