### ISSUE TITLE
Fix bookmarklet description

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2406]
For most source sites (Twitter/Pixiv/Nico Seiga) it's better now to use the bookmarklet from the HTML page versus the image. The batch uploader also works with Pixiv now.

**Comment by ToksT** [comment]
This isn't true for Pixiv. The bookmarklet does work from the html page, but the preview image on the upload page won't appear. You need to use the bookmarklet from the direct image url for it to appear.

This is because Pixiv is strict with referers. They don't allow Danbooru hotlinking their images. But if the user views the full size first then their browser caches the image, so the preview works.

I think deviantart, twitter, and seiga are the only ones it's currently viable to do this on. Though supporting some more like nijie and tumblr might be possible.
