### ISSUE TITLE
Comment Deletion Changes

### ISSUE THREAD

**Issue by RenimLS** [r888888888/danbooru#2428]
The mod ability to permanently delete comments should be removed, and like how other features operate it should simply remove the visibility of the comment from the majority of users (probably in this case making it only visible to moderators). It should also mark the user who "deleted" the comment.  This prevents potential moderator abuse and maintains accountability of users with the ability to perform deletions.  It also prevents moderators from actively deleting important information that would be needed in judging a user when handing out bans. Furthermore it keeps the record of that comment in the system and thus keeps the IP assigned to it, which is necessary information for performing IP bans.

**Comment by Type-kun** [comment]
@ToksT, does comment count in user profile substracts deleted comments from count? Didn't notice that in the commit.

**Comment by ToksT** [comment]
> @ToksT, does comment count in user profile substracts deleted comments from count? Didn't notice that in the commit.

Hm, I could filter it by is_deleted = false, but I can't test what kind of performance that would have since the database dump doesn't have comments in it. Adding an index on is_deleted may or may not help with any performance problems that may or may not exist, but the comments table is big so I dunno if there might be some kind of issue with adding a big index like that.

**Comment by Type-kun** [comment]
Wait, it seems forum post count doesn't care if post is deleted, so comment counter shouldn't either, so nevermind.
