### ISSUE TITLE
Only show application trace for errors

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2484]
As far as I can see all the lines of the backtrace that have to do with ruby and rails aren't useful information and only clutter up the backtrace, it shouldn't show those.

**Comment by ToksT** [comment]
Actually maybe it would be better to provide both the full trace and the application trace, in two separate tabs. There might be some circumstances where the rails lines are useful.

**Comment by r888888888** [comment]
Which error are you talking about? The exception trace itself has no concept of what part is rails and what isn't, it may just not be immediately obvious.

**Comment by ToksT** [comment]
I'm talking about the errors that get displayed to builder+ users.

Rails has built in functionality for showing only certain parts of a trace: http://api.rubyonrails.org/classes/ActiveSupport/BacktraceCleaner.html

**Comment by Type-kun** [comment]
The default rails backtrace cleaner yields pretty awesome results: https://gist.github.com/Type-kun/9aef8ac8f14205071f0a4f66de275d33

It can be applied by changing line 5 in views/static/error.html to
```
<%- Rails.backtrace_cleaner.clean(@exception.backtrace).each do |b| -%>  
```

Full error stack can be written inside a html comment, so that it's still accessible but not visible.
