### ISSUE TITLE
Add option to disable persistent un-blacklisting

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#2497]
In #2474 persistent un-blacklisting was added mainly for anonymous users who have no means to properly disable the default blacklist (but also for some interested registered users). However, as a registered user I can just remove tags from my blacklist if I want to see them and the things on my blacklist are there because I want them to be hidden by default.

Example: `spoiler` tag.
Let's say I have seen/read all of copyright X, so I unhide `spoiler` posts from the search results for X, but then I search for copyright Y that I don't know much about yet and all `spoiler` posts are shown, which is not what I want. The only indication that that's happening is the zero after the bolded `spoiler` tag, I think.

The only workaround would be to never forget to hide tags again that I've unhidden, always checking the search results or other post listings again after I'm done with something, which is rather unreliable.

Therefore, I'd like to have an option to disable persistent un-blacklisting, returning it to the volatile behavior that it had before #2474 was implemented.

**Comment by r888888888** [comment]
Spoiler has to be the only one where this matters. Others, yes you may be grossed out for a moment but it doesn't ruin anything. And I think persisting the toggle is the intuitive behavior.

**Comment by r888888888** [comment]
How about adding a notice (to every page potentially) that a blacklist has been disabled? It could be added to the default layout.

**Comment by mathrick** [comment]
Not just spoilers, any situation in which blacklists are used for what a blacklist should and used to be, ie. "don't show me X unless I specifically told you otherwise". Carrying this across to completely unrelated searches and posts breaks this expectation completely. It's a useful behaviour for spoilers, or for rating:e, which I've had blacklisted ever since blacklist were added, because I'm totally not interested in seeing porn by default, except for specific searches where I expect the results to be interesting and thus want to show porn too. It also neatly shields me from random links I get from wherever, which might include spoilers (and I won't know before I look at it), or accidentally clicking the stray danbooru URL at work which happens to be porn.

Telling me that a blacklist was disabled is a wonderful non-solution to anything. It's still broken as far as I'm concerned and have to do all the menial work it used to do for me, but now it also tells me that. Persistence really should be distinct from just unhiding a specific blacklist. Adding a checkbox alongside or a link like "(disable)" when you unhide one would preserve the desirable behaviour of both ways, while also making it clear that persistence is, in fact, an option and you can elect to have it.

**Comment by r888888888** [comment]
Maybe spoilers should just always be hidden by default and it can't be deactivated.

**Comment by mathrick** [comment]
...which still does nothing for my `rating:e` use case, locks people into hiding spoilers even if they don't care, and doesn't fix the fundamental issue that "show hidden posts once" and "disable blacklist until I re-enable it" are fundamentally two different operations that should have distinct UI and be clearly communicated. Can we please not pile on unrelated semantics onto a problem caused by overloading semantics in the first place, for once?

**Comment by r888888888** [comment]
Let's drop the attitude. It doesn't help matters any.

What you're proposing clutters up the ui a lot, especially for inline blacklists. Toggling individual blacklists is complicated enough. Being able to toggle them permanently versus temporarily gets even more complicated. Defaulting to temporary disable doesn't seem intuitive to me, and besides there's no reliable way to do that in the web browser. What does temporary mean? Is it time based? Page based? What happens if I have two tabs open?

Maybe this is better:

Show blacklisted previews but obfuscate the image. On the post page give an option to view the blacklisted post anyway, but this doesn't affect blacklists at all. Get rid of any blacklist toggling. If you really want to see a blacklisted post just open it up in a new tab.

This gets rid of the ability to look over blacklists posts at a glance, but is more intuitive to use.

**Comment by mathrick** [comment]
Uhh, I don't understand what "temporary" you refer to. The default I want and the only one I can imagine being useful is the way blacklists have always worked until this change: there's no data saved anywhere. Clicking the displayed blacklist link only (un)hides the DOM nodes and nothing else.

There's one, and only one useful scenario for any kind of permanent toggling I know of, and that's anonymous browsing where there's no account to save the settings for. But I'm not anonymous, and breaking the way blacklists have always worked for that one use-case of people who don't even use the site much seems backwards to me. And likewise it's absolutely not intuitive that clicking once to show the image on a specific post's page will change the results of any and all subsequent searches forever. The proper place to remove blacklists globally is in the account settings, the same place where you add them.

Not a huge fan of obscuring, it makes any kind of quick scan (in particular for tag maintenance purposes) pretty much impossible, and both `rating:e` and `spoilers` are pretty much guaranteed to have exceptions where based on the accompanying tags you want to unhide them on the page you're looking at. I wouldn't mind, however, having back the pink background on unhidden blacklisted thumbnails the way it used to work in the very first implementation. It makes it much easier to identify the toggled items when you unhide on a search result.

As for the UI, why wouldn't showing the option to remember the unhiding when you toggle work? Ie.

**Blacklisted ([Help](#))**

 * [spoilers](#) 3
 * ~~[guro](#)~~ 2
  * [ ] [Disable by default](#)

[Disable all](#)

Makes it explicit that there's such an option (although I still don't understand *why* you'd want it, could you give an example of a non-anonymous user wanting to toggle blacklists on and off, but wanting to remember that toggle across searches?), doesn't clutter the UI for blacklists which are not unhidden (as you'd expect to be the norm for blacklists), and makes it opt-in for people who want it, rather than forcing everyone to be surprised by the behaviour with no way out.

**Comment by kittey** [comment]
Persistent blacklist toggling was removed in Danboru 2.100, so this issue is obsolete.
