### ISSUE TITLE
Exclude empty commentary from searches

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2502]
If all of an artist commentary's text fields are null, blank, or whitespace-only, exclude it from `/artist_commentaries.json` results.

Alternatively, add another search parameter to do the same, like how you can hide empty results on Tags searches.

**Comment by evazion** [comment]
#3150 fixed it so that commentary fields can't be null or whitespace-only, so only blank fields need to be excluded.

#3253 adds a search parameter for filtering deleted commentaries if you choose, but leaves them in the results by default. We're not completely consistent on whether search pages include deleted results by default, but I think more pages do include them that don't.
