### ISSUE TITLE
Feature request: search for posts updated by user in post search

### ISSUE THREAD

**Issue by mseymour** [r888888888/danbooru#2552]
We already have the facility for looking at individual user's tag updates via [/post_versions?search[updater_id]=1](http://danbooru.donmai.us/post_versions?search%5Bupdater_id%5D=1)

It would be useful to be able to filter posts depending on if a specific user updated it, so for instance if I wanted to see what posts that I updated which were uploaded by Albert, I would be able to do so.

The token I would suggest to use would be `tagupdater:*` or `tagger:*`, based on the existing `noter` and `noteupdater` tokens.

**Comment by r888888888** [comment]
Would an asynchronous process that sends you a dmail with all the matches suffice?

**Comment by ToksT** [comment]
> Would an asynchronous process that sends you a dmail with all the matches suffice?

Then you wouldn't be able to use tag scripts or see the thumbnails of the posts at a glance.

Maybe the dmail could contain a link to a search like [id:1,2,3,4,5](http://danbooru.donmai.us/posts?tags=id%3A1%2C2%2C3%2C4%2C5) with the ids of the results so you could view it in the regular post view. But that wouldn't work if there are tons of results because it would go over the limit for characters in a url.

**Comment by r888888888** [comment]
Could persist the ids and just come up with a unique token to execute the search. IME direct post id searches are fast, even at 1000+ ids.
