### ISSUE TITLE
Option for old blacklist behavior

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2568]
Judging by http://danbooru.donmai.us/forum_topics/9127 , half of users like the new blacklist behavior, while other half prefer the old way (hiding thumbnails completely). I think this calls for a user option.

**Comment by r888888888** [comment]
I'm pretty sure this can be done with custom stylesheets, correct?

You can just override .post-preview.blacklisted-active to hide it.

**Comment by Type-kun** [comment]
Indeed, but there just seemed to be enough dissatisfied users to make switching back easier.

**Comment by Zelinko** [comment]
I want to keep an option within the settings to be able change it back

**Comment by ToksT** [comment]
> I'm pretty sure this can be done with custom stylesheets, correct
 
> You can just override .post-preview.blacklisted-active to hide it.

Does the new blacklist style have practical benefits over the old one or is it just a visual change?

If the change was supposed to make tag scripting easier then it's unnecessary as that's what I added disable all blacklists for. Besides almost all of the time you're tag scripting you need to see the thumbnail to be sure that you're not mistagging it, you can't do that if the thumbnail is a black box.

If it was supposed to let users know that the current page has posts that are blacklisted then it's unnecessary - the Blacklisted section of the sidebar let's you know that and it's hard to miss.

If it was supposed to reduce the number of clicks someone has to make by allowing them to click a thumbnail without first disabling the blacklist, then I don't see who would use that - if someone blacklists something they find gross they're not going to want to see the full size image until they've looked at the thumbnail to make sure it's okay.

I guess it's just a visual change, but since the majority opinion seems to be that it looks bad compared to the old style it would probably be better to revert to the old style, and people that like the new style can use custom css for that.

**Comment by r888888888** [comment]
I just don't think such an obscure visual change that affects a dozen users is worth a user preference setting.

I'm just going to revert everything except the change to persistence.
