### ISSUE TITLE
Remove leading hyphens from tagged filenames

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2612]
Numerous people have complained about filenames starting with `--` breaking their shell scripts. Either removing these or replacing with something neutral like `_` or even square brackets should work fine.

**Comment by r888888888** [comment]
How does it break shell scripts?

**Comment by kittey** [comment]
`--` introduces long options for most shell commands, so passing the filename as an argument results in something like `grep: unrecognised option '--kousaka-tamaki-to-heart-2-drawn-by-kyougoku-shin--d34e4cf0a437a5d65f8e82b7bcd02606.jpg'`. Starting the filename with a single dash results in the same problem because then it’ll be interpreted as a bunch of short options: `grep: invalid option -- 'k'`

Said numerous people could use `--` (just two dashes) to mark the last argument or prefix the filename with `./`, but nobody ever does that. :)

**Comment by r888888888** [comment]
fixed
