### ISSUE TITLE
Invalid encoding issue with artist commentaries

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2617]
It causes a character to be appended to the end.

**Comment by Type-kun** [comment]
What's surprising is that XML or JSON commentary version, or even the commentary itself (under the post),  doesn't show anything of the sort. The weird character only appears when output to the textarea happens - it doesn't even happen for titles, neither translated nor original. It seems to appear only in descriptions, and only if it's not empty. However, there is http://danbooru.donmai.us/posts/2402842 - it does appear in original description but not in translated, even though both are empty.

**Comment by reiyasona** [comment]
> However, there is http://danbooru.donmai.us/posts/2402842 - it does appear in original description but not in translated, even though both are empty.

@Type-kun This is even more confusing ...

Just tested [post #2402842](https://danbooru.donmai.us/posts/2402842) and [post #2413015](https://danbooru.donmai.us/posts/2413015) in Chrome (Chromium) and the invalid UTF-8 character � is not displayed.

**Comment by Type-kun** [comment]
@r88888888 was there any updates to the server software around a week ago? RoR or Postgresql update maybe? I don't see anything changed in the source code of either danbooru-related projects, so...

Also, here are clearer steps to reproduce:
* open any post with artist commentary while logged in, in any non-chromium based browser
* click "Add artist commentary" to call up the dialog
* you'll see the character already in the dialog textareas
* if you view the page source, the character is in the respective textareas even before loading up the dialog

**Comment by Type-kun** [comment]
Actually, disregard that. This was going on at least since June 23rd - see http://danbooru.donmai.us/artist_commentary_versions?search%5Bpost_id%5D=2250230 - maybe there are even earlier version, please search the database for trailing � in commentary versions to find the earliest case.

So I guess it's either ragel parser introduction or one of the gems updated along this it. Can you disable it on testbooru and check if it still happens with http://testbooru.donmai.us/posts/11 ?

**Comment by Type-kun** [comment]
@r888888888 Out of curiosity, how did ragel `parse` function even influence whatever was written to textareas? I still don't see it going through `format_text` anywhere, and it seems the only place where `parse` is used.

**Comment by r888888888** [comment]
It was concatenating a \0 to the end of the string to make parsing easier. I didn't realize it was modifying the original string.

**Comment by Type-kun** [comment]
Ah, so that's it, ragel was modifying the original string when `format_text` was called. So when it did output of the commentary to the block below the post, strings in the commentary object were changed, and second output to the textarea showed `0x00` appended. That's also why titles were not affected, only descriptions. This sure is a stab in the back after getting used to immutable strings :3
