### ISSUE TITLE
comment search: InvalidColumnReference for body+comm metatag

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2628]
Attempting to search comments with `comm:RaisingK` and something in the Body field raises an InvalidColumnReference exception:

`ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list LINE 1: ...uery('''x''')) AND (creator_id = 13506) ORDER BY comments.i... ^`

[Like so](http://danbooru.donmai.us/comments?commit=Search&group_by=comment&search%5Bbody_matches%5D=x&search%5Bis_deleted%5D=false&search%5Bpost_tags_match%5D=comm%3ARaisingK&utf8=%E2%9C%93)

**Comment by Type-kun** [comment]
Ok, this is pretty fun. When searching for comments of user 1 containing "test", the query ends up like this:
```
SELECT COUNT(*) FROM "comments" 
INNER JOIN "posts" ON "posts"."id" = "comments"."post_id" 
WHERE (true) 
  AND (body_index @@ plainto_tsquery('''test''')) 
  AND (posts.id IN 
      (SELECT DISTINCT "comments"."post_id" 
         FROM "comments" 
         WHERE (true) 
           AND (body_index @@ plainto_tsquery('''test''')) 
           AND (creator_id = '1')  ORDER BY comments.id DESC)
       );
```
Error itself is caused by that rogue  `ORDER BY comments.id DESC`. however, that's only part of the more serious problem: the weirdest thing here is that all `where` conditions are repeated in the inner select from comments. The inner select itself is coming from the following line in `post_query_builder`:

```
relation = relation.where("posts.id IN (?)", Comment.where("creator_id = ?", commenter_id).select("post_id").uniq)
```
...while the rest of condition were defined in `Comment.search`. 

`Comment.search` calls `Comment.post_tags_match` which in turn calls `PostQueryBuilder`. I'm pretty sure that for some reason, _whatever relation `q` has during `Comment#post_tags_match` is passed as default relation to `Comment.where`_. 

@r888888888 how is that even possible? Does ActiveRecord use some sort of a class variable for relations? I tried to override it using `Comment.all` and `Comment.all.reset`, but it all seems to fail.

**Comment by Type-kun** [comment]
Looks like anonymous scope was created somehow. Equivalent to http://apidock.com/rails/ActiveRecord/Relation/scoping

Solved using `Comment.unscoped`, but perhaps more general solution should be used to avoid similar mistakes in the future.
