### ISSUE TITLE
Create a User Report accessible to all users

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2647]
Reference [topic #13090](http://danbooru.donmai.us/forum_topics/13090) (genesis of idea) and [topic #13112](http://danbooru.donmai.us/forum_topics/13112) (prototyping of idea).

Can be done in steps:
- [x] Step 1: Modify the current Mod/Admin report to something that is visible to all users except only updated on a weekly basis instead of on demand.  Include all user levels, bounded by the last month of data and cutoff values as suggested in [forum #118632](http://danbooru.donmai.us/forum_posts/118632).

>    Toks said:
> These reports have existed for years actually, they're on a page called the mod dashboard.  I think its limited to mods because of performance reasons. It's configurable with options like how far back to count changes and what levels of users to include.
> 
> BrokenEagl98 said:
> Could a report that is only updated like once a week (or month) be made available to regular users?
> 
> Type-kun said:
> Yes, even if updated daily, it shouldn't be much of a strain on the server. It wouldn't be configurable though, dates would have to be fixed.
- [x] Step 2: Add in missing categories (pool, artist commentary, forum topic, forum post, tag implication, tag alias, bulk update request, post appeal, comment).

> Toks said:
> It's missing pool changes and artist commentary changes though. Probably not hard to add but performance should be tested.
- [x] Step 3: Increase the granularity of the reports by breaking down the actual events that are occurring.

> See  [forum #118632](http://danbooru.donmai.us/forum_posts/118632) for details.
- [x] Step 4:  Aggregate the data on a weekly basis to enable historical tracking of change trends.

> Type-kun said:
> Also, thinking about it further, would this report make more sense if updated daily and discarded (as currently suggested), or monthly and stored? At a glance, second way seems to be more useful and fun to follow. Not only the change history can be seen this way (think of all the graphs that could be built with that), but data could also be aggregated over a few months if necessary, while placing relatively little load on the server. Maybe even go further and store weekly data, automatically aggregating 4 last weeks by default.

**Comment by r888888888** [comment]
I'm going to just open up the report for everyone to see. It is vulnerable to DOS attacks but this will just be a temporary measure to reveal what the report is currently and ways in which it can be improved or optimized. I don't believe it reveals any data that isn't already public.

I'm not sure what the requirements for archival are. Are simple HTML snapshots sufficient or is more structured data required. The latter would make reporting easier but then you get into issues with schema changes, shifting requirements, etc.

**Comment by BrokenEagle** [comment]
Best to ask @Type-kun for the requirements since he's the one that had the idea for data archival and trend tracking.

**Comment by Type-kun** [comment]
> I'm not sure what the requirements for archival are. Are simple HTML snapshots sufficient or is more structured data required. The latter would make reporting easier but then you get into issues with schema changes, shifting requirements, etc.

I vote for the structured storage. Aggregate data weekly, store it, then build reports based on it on demand. Moreover, I'd say that weekly data should be stored entirely, without any rows discarded as "insignificant". It increases data size, but it's still not that much compared to say post versions, it's well-distributed by nature so it should index well, and since it will be offloaded anyway that shouldn't be an issue at all. 

One benefit of such approach is that everything can be calculated retroactively. We can fill the history back to the start of Danbooru right away, and if the requirements change drastically it can be regenerated anyway. 

Assuming we have weekly data stored, we can create the user promotion report. It's the primary objective anyway, but if we work with aggregated data, it's possible to filter and aggregate it further. So, the report would have the following parameters at least:
  * minimum and maximum user levels
  * period (start and end dates, can be easily derived from week+year data)
  * cutoff (optional, maybe just defaulting it will suffice)

The most important is undoubtedly the possibility to specify a custom period. This will make the tool actually useful for locating promotion candidates. That's also the reason why the data should be stored entirely. If some user uploads 14 images weekly while cutoff is 15, aggregating over 4 weeks would show that user with 56 uploads instead of discarding him.

However, I'm not sure what the stored columns should be. Current report posted in the forum became pretty advanced, pretty much impossible to generate with SQL query or two, since it relies heavily on the difference between versions. All this can be transferred to ruby, especially since the script source is available and the logic is described at the forum, but which columns are actually useful remains an open question yet. Though I agree that some of those are necessary, for example knowing whether note change is body change or a simple move/resize - I do the latter sometimes with note assist script, but that doesn't mean I have to show up in report as a proficient translator due to amount of changed notes.

Additionally, some columns don't work with stored aggregate data. Namely, "errors", which is calculated as a difference between basic version and current version. Its value depends on time when it's calculated and will change if regenerated, so it's not exactly a good metric to store.

----

In addition to creating a promotion report, stored aggregated data would allow to create activity graphs over time - weeks as X axis, metric as Y. Some variants:

* Specific user activity graphs, available from user profile. Visual representation of user activity could be very helpful when deciding promotions or demotions.
* Collective multi-line graphs, showing multiple competing top users on the same graph. This serves no practical purposes other than being e-penis, but due to nature of danbooru this can work as incentive for users to become more active. 

Granted, the metrics for the graphs would have to be selected carefully, but if done properly it could look very nice :3

**Comment by r888888888** [comment]
Any feedback about the current report?
