### ISSUE TITLE
Periodically redirect janitors+ to the random mod queue

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2651]
Once an hour should be enough. If they only have to review 5 posts it's not a great burden.

**Comment by kittey** [comment]
I’m not janitor+, but I can imagine that feature being quite annoying. For example, if someone is reading a series pool and all of a sudden he’s being redirected to the random mod queue. That may lead to quick and incorrect dis-/approval decisions just so that he can resume reading the series.

Randomly picking posts might also be a problem for posts that are part of a series pool or have parent/child posts, which usually would be displayed next to each other.

**Comment by Type-kun** [comment]
Slowly reading pools will get incredibly fun :3  On a serious note, turn it off after some work is done for the day. Or maybe show a notice instead. Redirect is effective, but pretty brutal if you're in the middle of something.

**Comment by r888888888** [comment]
That's the cost of being a janitor. Maybe start with once a day instead to see how well (or not) it works.

**Comment by Type-kun** [comment]
The more I think about it, the more I feel that a notice, similar to "you have mail" or "update your account", would work better. It doesn't interrupt whatever the user is currently doing, but is obtrusive enough that it's impossible to ignore. 
* First, show it with "remind me later" option to close; 
* Show it again after 10 minutes (or 30 if we go with once-a-day), but without an option to close;
* If the approver is still consistently browsing the site while ignoring the message, then force-redirect can be done, but not before that.

Also, like I said earlier, if an approver have already judged with the queue enough, then the message should not be shown. Same if the queue is short enough to not require every approver looking through it.

**Comment by r888888888** [comment]
I guarantee that people would just ignore a notice like that. And maybe that's valuable information to capture and for pruning active janitors. But I want to see how much real disruption this change would cause first.

**Comment by r888888888** [comment]
wontfix i think the notice is good enough if its annoying

**Comment by Type-kun** [comment]
It's a very good start. Will be more effective with central notice instead of flash, too. 

Though relying on a cookie is problematic, it's easily hackable with a single change. Storing the data in session (it's protected at least) and/or database would be better. This would also allow more complex logic, like force people to check 5 posts per day instead of 1. 

Also, while unlikely, there should be a check that queue is not empty. It'll get pretty frustrating otherwise.
