### ISSUE TITLE
Tie supervoters to votes instead of favorites

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2652]

**Comment by Type-kun** [comment]
That's a good idea because this can't be hijacked unlike the favorites one, but vote data is erased after 3 months, isn't it? Because of that, I think that supervoter selection will tilt towards whatever is popular in the current anime season rather that matching first user taste. Also, if the admin goes to vacation for a month or two, selection will get pretty screwed.

**Comment by r888888888** [comment]
This will probably be another ticket but I think the concept of a Curator should be generalized so that the supervoters are tied to them rather than me specifically.

I don't mind a recency bias. The bias is already worked into the current algorithm.

**Comment by r888888888** [comment]
fixed
