### ISSUE TITLE
Implement anti-voters

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#2653]
This would be the opposite of super voters. Anti voters would tend to upvote anything I downvote. They could theoretically be used to identify bad posts. Need to research to see if this produces any useful information.

**Comment by BrokenEagle** [comment]
There would need to be some deception involved if this were to become a thing. I can't speak for everyone, but I always look at the score when voting to ensure it counted my vote.  If someone were to figure out they are an anti-voter, they'd probably hold back on voting until that status goes away.

What could be done is to have the score be incremented, and then have a timeout after an hour or so that goes back and decrements the the score. Vice versa for if they unvote that post.

**Comment by r888888888** [comment]
The real score should be obfuscated. Reddit does this for various reasons, vote manipulation being one of them.

**Comment by r888888888** [comment]
in practice this doesn't seem to give very reliable results. canceling.
