### ISSUE TITLE
cap development deploy does not deploy local code

### ISSUE THREAD

**Issue by hachi** [r888888888/danbooru#2669]
`bundle exec cap development deploy` does not install the code in the local work tree, nor in the current branch, nor in the local master branch:

It informs me:

```
INFO [726c4c7f] Running /usr/bin/env echo "Branch master (at 70fef49) deployed as release 20160911115510 by hue" >> /var/www/danbooru2/revisions.log as danbooru@localhost
```

But that doesn't match any of my local work tree or my commits in the local repo:

```
danbooru@booru:~/danbooru$ git branch
* develop
  master
danbooru@booru:~/danbooru$ git rev-parse master
f41c019abba167918f83a40109114190a8ce83f0
danbooru@booru:~/danbooru$ git rev-parse develop
f41c019abba167918f83a40109114190a8ce83f0
```

Yes I have a single local change that I'm trying to deploy committed to both branches, but it keeps deploying based on some other marker.

I see nothing in config/deploy/* that makes this branch selection happen
There are no references to git branch 'master' or 'HEAD' anywhere that I can find in the source code.

**Comment by Type-kun** [comment]
When you run cap deploy, it clones from current git repository specified in config - look at `config/deploy.rb`, my guess is that it still points to `set :repo_url,  "git://github.com/r888888888/danbooru.git"`. So, the suggested workflow is to fork the repo, set it in `deploy.rb`, commit the changes, push them, then run cap deploy so it can pull from web. 

On my development machine, I've overriden this by simply rsyncing local copy over `/var/www/danbooru2/current` after deployment, since this is much faster than full deploy anyway and I didn't have time nor resolve to properly find out how cap works. However, looks like capistrano can be set up to clone from local repos, too - see http://stackoverflow.com/questions/5532323

As for using different branches, see http://stackoverflow.com/questions/1524204/

I guess this causes your other issue, too.

**Comment by r888888888** [comment]
I think I'm going to change the instructions to prevent people from trying to deploy the code locally because that is a deployment process that is atypical and causes confusion. When I want to run Danbooru locally I just use rails server. I don't use capistrano at all.

Capistrano is only useful when you want to deploy a production instance to a remote server hosted on a VPS or EC2 or something similar. In such a case, you're going to start the capistrano deployment process from your laptop or desktop computer, which will pull the code from Github and deploy it to the remote server. Whatever local changes you have will not be deployed unless you've committed the changes and pushed them to Github.
