### ISSUE TITLE
Ragel DText can't handle Unicode characters in URLs

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2683]
Paste this into a DText box and hit preview:

```
"7893":/posts?tags=approver:葉月
"7893":[/posts?tags=approver:葉月]
http://danbooru.donmai.us/posts?tags=approver:葉月
```

The output looks like this:

> [7893](http://danbooru.donmai.us/posts?tags=approver):葉月
> "7893":[/posts?tags=approver:葉月]
> [http://danbooru.donmai.us/posts?tags=approver](http://danbooru.donmai.us/posts?tags=approver):葉月

When it should be like this:

> [7893](/posts?tags=approver:葉月)
> [7893](/posts?tags=approver:葉月)
> http://danbooru.donmai.us/posts?tags=approver:葉月

**Comment by Type-kun** [comment]
Not just URLs, mentions don't work as well. That's because default `graph` machine in ragel in single-byte. Looking at [UTF-8 spec](https://en.wikipedia.org/wiki/UTF-8#Description), [this link](http://ragel-users.complang.narkive.com/ujOlEvru/ragel-hex-codes-on-x86-64) and the output of unicode2ragel.rb, I think it should be pretty simple to create a machine which represents all valid utf-8 byte sequences:

```rl
utf8 = 0x00..0x7F 
          | 0xC2..0xDF 0xB0..0xBF
          | 0xE0..0xEF 0xB0..0xBF 0xB0..0xBF
          | 0xF0..0xF4 0xB0..0xBF 0xB0..0xBF 0xB0..0xBF;
```

(untested, but should work fine). This includes ALL valid utf8 sequences, including non-printable, but it's a good place to start at least. most control characters can be removed with `utf8 - cntrl`, the rest is scattered across the specs but can be found if necessary.

**Comment by Type-kun** [comment]
Pfhah, looks like I actually DO need a vacation, or maybe a week of sick leave. The correct sequence for 2nd+byte in utf is `0x80..0xBF`, not `0xB0..0xBF`. Either way, I tried out creating a utf8graph machine using the following:

```
utf8graph = (0x00..0x7F) & graph
          | 0xC2..0xDF 0x80..0xBF
          | 0xE0..0xEF 0x80..0xBF 0x80..0xBF
          | 0xF0..0xF4 0x80..0xBF 0x80..0xBF 0x80..0xBF;
```

...and it passes with flying colors, both old tests and new I added for utf8 cases. Will make a pull request soon.

**Comment by r888888888** [comment]
fixed
