### ISSUE TITLE
Pool descriptions should be versioned.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2684]
Pool descriptions currently aren't stored in the version history. This permits vandalism. `is_active`, `is_deleted`, and `category` aren't versioned either, although those are of lesser importance.

**Comment by BrokenEagle** [comment]
In the meantime, I've stored all of the pool descriptions locally, just in case something does happen.

**Comment by BrokenEagle** [comment]
Since the description seems to be [versioned now](http://danbooru.donmai.us/pool_versions.json), should this issue be closed...?

On another note, should the extra information be visualized somehow on the HTML interface...?  It'd probably be too much to show the whole description, but I noticed that there is now a new boolean field called "description_changed" that could be shown instead. 

Should a new issue be created for that?

**Comment by r888888888** [comment]
fixed in 4859a803c6eaf7f0a09898bceedd5be3e0c3acec
