### ISSUE TITLE
Releases are not described since 2.103.0

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2685]
We're currently at 2.105.0, but release notes for 2.104.0 are still in draft, tag for 2.105.0 is not created at all, and we're 93 commits ahead since last version change...

I'll also take this chance to apologize for messing up tag on 2.104.0. Looks like Github attaches the latest tag to whatever commit is made with web interface - perhaps because no other commit yet was tagged with 2.104.0 back then?

**Comment by r888888888** [comment]
To be honest, now that the git hash is displayed on the web site I've been leaning towards not versioning stuff anymore.

**Comment by BrokenEagle** [comment]
One benefit to still having versions is being able to indicate which points in the code history are more stable as opposed to in the middle of a bug fix...

**Comment by evazion** [comment]
Version numbers were never useful to me, they never had much meaning since the site operates on a rolling release basis.

How about tagging each deployment by release date though? This would help with #2742, since it would make it possible to compare changes since last deployment (e.g. `20161030..master`), or changes between deployments (e.g. `20161024..20161030`).

**Comment by Type-kun** [comment]
Hmm, how about showing commit date along with hash? Is it viable? Not gonna be terribly accurate since you can deploy a week after commiting, but it's easier to track than hash.
