### ISSUE TITLE
pixiv_id/pixiv parsing doesn't account for https

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2695]
`pixiv_id` is not parsed if the URL uses https; the parse_pixiv_id patterns in /app/models/post.rb need `https?`.

**Comment by BrokenEagle** [comment]
I believe this can be done by replacing all of the 'http' and 'https' substrings in all of the URL regexes with '(?:http|https)'.  At least that's how I do it...

**Comment by Type-kun** [comment]
>I believe this can be done by replacing all of the 'http' and 'https' substrings in all of the URL regexes with '(?:http|https)'. At least that's how I do it...

`https?` suggested by RaisingK is enough. It reads as mandatory `http` part plus optional `s` character.

**Comment by evazion** [comment]
Submitted PR #2699. There is already code for parsing illust ids in [Sources::Strategies::Pixiv#illust_id_from_url](https://github.com/r888888888/danbooru/blob/dbf1a385502fcafcbabcf71ecbcbdb53da718c02/app/logical/sources/strategies/pixiv.rb#L300-L334). It just has to be refactored so that `parse_pixiv_id` can call it.

**Comment by evazion** [comment]
Here's a BigQuery giving the list of pixiv posts with bad pixiv ids:

https://docs.google.com/spreadsheets/d/1KN0Q72xQMfj3n7ESAGHp4yJsvOXhqY1cSbUMVRnCXbc/edit?usp=sharing

```
SELECT
  id,
  CONCAT("http://danbooru.donmai.us/posts/", STRING(id)) AS url,
  pixiv_id,
  source
FROM [danbooru-data:danbooru.posts]
WHERE REGEXP_MATCH(source, r'pixiv\.net') AND pixiv_id = 0
```

There are ~850 such posts, ~500 of which are https urls. These posts will need to be resaved after this issue is fixed to update their ids. Most of the rest look like random bogus junk.

**Comment by SD-DAken** [comment]
Of the ~350 http urls there are a lot of pixiv user's profile images and background images which are (or at least were at the time of the upload) valid, but have no associated pixiv_id (see also issue #2460). There are also some comic.pixiv.net entries that also have no pixiv_id as well as some novel cover pages that are linked to the novel and have no separate pixiv_id.

The rest are either unique urls (from events etc.) or invalid:
https://bigquery.cloud.google.com:443/savedquery/879791906425:850a0d5cd785458e981477060bd4406d
