### ISSUE TITLE
Bogus results on non-matching URL searches for Artists

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2696]
When searching for certain domain URLs and there is no match, it always returns the same results which don't actually have matches.  To see an example of this, check the following URLs:

http://danbooru.donmai.us/artists?name=http://twitter.com/doesntexist
http://danbooru.donmai.us/artists?name=http://seiga.nicovideo.jp/user/illust/2
http://danbooru.donmai.us/artists?name=http://www.nicovideo.jp/user/2
http://danbooru.donmai.us/artists?name=http://ask.fm/doesntexist
http://danbooru.donmai.us/artists?name=https://www.facebook.com/doesntexist
http://danbooru.donmai.us/artists?name=https://www.youtube.com/c/doesntexist
http://danbooru.donmai.us/artists?name=https://www.biglobe.ne.jp/~doesntexist/
http://danbooru.donmai.us/artists?name=https://www.plurk.com/doesntexist
http://danbooru.donmai.us/artists?name=http://weibo.com/2

Compare and contrast with:

http://danbooru.donmai.us/artists?name=http://www.pixiv.net/member.php?id=2
http://danbooru.donmai.us/artists?name=http://img.pixiv.net/img/doesntexist/
http://danbooru.donmai.us/artists?name=http://doesntexist.blog.fc2.com/
http://danbooru.donmai.us/artists?name=http://doesntexist.deviantart.com
http://danbooru.donmai.us/artists?name=http://doesntexist.tumblr.com
http://danbooru.donmai.us/artists?name=http://doesnt.exist.com

That's all I could think of... there might be more.

Edit:

Added some more that I found.  Will add others when I find them.

**Comment by evazion** [comment]
IIRC this is due to the directory-stripping algorithm that the artist finder uses. Here's albert's description from [topic #279](http://danbooru.donmai.us/forum_topics/279). It still works essentially the same way to this day:

> Here's out Find Artist works:

> When you click on Find Artist, Danbooru takes the URL and matches it against every artist URL. If it finds any, it stops and returns the matches. If it doesn't find any, Danbooru will chop off everything after the last slash (including the last slash), so http://site.com/img/001.jpg becomes http://site.com/img. If it still doesn't find anything, it'll chop off another directory, so http://site.com/img becomes http://site.com. At this point Danbooru will probably find a bunch of results (this is what happens when you search for an unknown artist hosted on http://sakura.ne.jp for example).

The root problem is that this algorithm assumes that a) most art comes from personal blogs or websites and b) these sites include the artist's name in the URL, as a subdirectory or a subdomain. Neither assumptions have been true for many years now. Most art nowadays comes from sites like Pixiv/Tumblr/Twitter/dA that don't include the artist's name in the image URL.

Nevertheless this algorithm has been shoehorned into working for sites like Pixiv via various hacks:

* For sites like Pixiv that don't include the artist name in the URL, we make up a so-called normalized URL that *does* include the artist name, then match against that.  See http://danbooru.donmai.us/artists/8690.json for an example: `http://i4.pixiv.net/img-original/img/2016/09/29/20/05/03/59222831_p0.jpg` is normalized to `http://img.pixiv.net/img/ccz67420/` for the artist finder.
* There's [some additional normalization here](https://github.com/r888888888/danbooru/blob/8e17b4936ac542e7ae296d40e9f9d411e6da4f7d/app/models/artist_url.rb) for certain other sites to make the URL matching process work for them too.
* For certain domains, we stop the directory stripping process when we reach them without finding a match. This is the problem here, for something like http://twitter.com/doesntexist the matching doesn't abort, instead it blindly returns everything matching `http://twitter.com/*`.

So the easy fix is to include your list of domains as more special cases in [Artist::find_all_by_url](https://github.com/r888888888/danbooru/blob/20779d52d07696177057fe1846a83f0d31b496e2/app/models/artist.rb#L31-L40").

The hard fix would be to forget all this directory-stripping and URL matching nonsense. For most sites it's unwanted and not used, in fact we have to work around it. It'd be much simpler to just store Pixiv/Twitter/Tumblr/etc usernames in artist entries and look them up directly instead of trying to do directory-stripping or URL matching.

**Comment by BrokenEagle** [comment]
> Evazion said:
The hard fix would be to forget all this directory-stripping and URL matching nonsense. For most sites it's unwanted and not used, in fact we have to work around it. It'd be much simpler to just store Pixiv/Twitter/Tumblr/etc usernames in artist entries and look them up directly instead of trying to do directory-stripping or URL matching.

Would such a scheme be expandable by users like moderators, or would it have to be implemented programatically? The advantage of the former is that it would be more responsive to change. They could create or edit new entries, and set the format for creating URLs.  Something like:

`Twitter:`
`AccountVariables: string`
`URLFormat: "https://twitter.com/%s`

`Biglobe:`
`AccountVariables: string,string`
`URLFormat: "http://%s.biglobe.ne.jp/~%s`

The above would create something like a site dropdown menu in the Artist edit dialogue for all users, and allow users to create one or more entries of various types.

**Comment by Type-kun** [comment]
>The hard fix would be to forget all this directory-stripping and URL matching nonsense. For most sites it's unwanted and not used, in fact we have to work around it. It'd be much simpler to just store Pixiv/Twitter/Tumblr/etc usernames in artist entries and look them up directly instead of trying to do directory-stripping or URL matching.

How would that handle those personal domains/subdomains, though? I'd say, proper rules for image aggregators should be implemented - easy way you mentioned. I don't think there's too many of those, and after some refactoring it can be made be pretty readable, too.

Storing usernames is another option, but that requires changes to multiple search and edit algorithms, separate structure to describe types of allowed sites, and I don't see how that would handle personal sites or the aggregators that are not described yet. Maybe some combination with url listing could work?

@BrokenEagle, it should be programmatic, because unfortunately handling regexp is waaay beyond the abilities of 99% of userbase - too easy to break, too hard to learn. After we do this, you can always open an issue or a pull request for more sites.

**Comment by evazion** [comment]
PR #2703 addresses this for twitter. Didn't do the other domains because I haven't tested them out yet.

**Comment by evazion** [comment]
> How would that handle those personal domains/subdomains, though? I'd say, proper rules for image aggregators should be implemented - easy way you mentioned. I don't think there's too many of those, and after some refactoring it can be made be pretty readable, too.

Basically I think the directory-stripping + URL matching algorithm is only necessary for unknown sites. For sites where we're able to get the artist's username - which we already do for several sites - I think it would be simpler if we were able to avoid URL matching and looked up the artist's username directly.

To give an example: try tracing the artist finding process for `Artist.url_matches('https://mobile.twitter.com/bkub_comic/status/782880825700343808')`. First it goes through these urls:

```
https://mobile.twitter.com/bkub_comic/status/782880825700343808
http://mobile.twitter.com/bkub_comic/status/782880825700343808/
http://mobile.twitter.com/bkub_comic/status/
http://mobile.twitter.com/bkub_comic/
http://mobile.twitter.com/
```

...which fails, so then it makes an API call to Twitter (!?) so it can start again with this url:

```
https://twitter.com/bkub_comic
http://twitter.com/bkub_comic/
```

...which finally matches. But if artist entries stored twitter usernames then this process could just be "parse `bkub_comic` from the url then look up which artist entry has twitter username `bkub_comic`". Simple.

> Storing usernames is another option, but that requires changes to multiple search and edit algorithms, separate structure to describe types of allowed sites, and I don't see how that would handle personal sites or the aggregators that are not described yet. Maybe some combination with url listing could work?

Storing usernames would require changes in a lot of places, but hey, that's what makes it the hard fix. I propose it because the site already knows how to get usernames for Pixiv, Twitter, dA, plus a few others, so it's a waste not to store this info that we already collect.
