### ISSUE TITLE
Install script enhancements

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2707]
First of all, there's a line in the install script which assumes the version of postgresql:

```
curl -L -s $GITHUB_INSTALL_SCRIPTS/postgresql_hba_conf -o /etc/postgresql/9.1/main/pg_hba.conf
```

It's pretty much ignored in Jessie, since 9.4 is default there. Version should be determined using something like `pg_config --version | egrep -o '[0-9]{1,}\.[0-9]{1,}'` instead.

Additionally, if version happens to be 9.5 or above, then r888888888/test_parser should be cloned, built and installed, or at very least a notice about that should be displayed. Otherwise database deployment will fail later.

Also, perhaps it's better to use `sites-available` and `sites-enabled` for nginx, instead of `conf.d`, though I'm not too sure about that.

**Comment by r888888888** [comment]
Instead of checking the version for test_parser I think it makes sense to always install the Github version and simply not install postgresql-contrib.

**Comment by r888888888** [comment]
Addressed in e496ac1ed6f8d89b810fab78644fbb096a3c0a83

**Comment by Type-kun** [comment]
Hm, wasn't removing contrib from install list a bit too radical? At the very least, it contains `pg_tgrm` which is, IIRC, currently used in artist search. It also contains extended gin and gist capabilities which we might have relied on, as well. Besides, it might be already installed.

There are nice one-liners for version check, relying on `sort -V`: http://stackoverflow.com/a/4024263/1375470 - since INSTALL is basically a bash script, `verlt` and `verlte` functions can be copied verbatim. Debian wheezy supports `sort -V` so it can be used safely.

**Comment by evazion** [comment]
Some other install issues worth mentioning:

* The site breaks if memcached isn't running. Non-Debian hosts don't start memcached on installation like Debian does, so it's easy to overlook. And some Debian hosts seem to have problems with connecting to memcache via localhost instead of 127.0.01.

* So maybe fallback to `MEMCACHE = MockMemcache.new` if memcached isn't running? That ought to be good enough for dev purposes.

* ffmpeg and mkvmerge are required for ugoira conversion but aren't listed in the dependencies. The test suite fails without them too.

* Pixiv uploading fails if you don't configure your Pixiv credentials.

* You can run a dev server via `rails server` or `bundle exec unicorn -c config/unicorn/development.rb`, but you have to remember to do `bundle install` and `rake db:create` and `rake db:migrate` first.
