### ISSUE TITLE
Ragel dtext can't handle [[|_|]]

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2708]
`|_|` and `||_||` are valid tags but ragel can't handle them inside wiki links: `[[|_|]]` or `[[||_||]]`.

Go to http://danbooru.donmai.us/wiki_pages/8795/edit and hit preview for a test case.

**Comment by BrokenEagle** [comment]
This is very similar to the issues I noted on the [Danbooru 2 Issues Topic](http://danbooru.donmai.us/forum_topics/9127?page=131#forum_post_118996) ([forum post](http://danbooru.donmai.us/forum_posts/118996)), which still doesn't appear to be fixed.

Basically, there's a difference in how the DText preview function works, and how the DText render function works.  The render function works fine for the above tags |_| and ||_||  (check the [actual wiki](http://danbooru.donmai.us/wiki_pages/8795) to confirm), however the DText preview is where the error lies.

**Comment by Type-kun** [comment]
>Basically, there's a difference in how the DText preview function works, and how the DText render function works. 

That's to be expected, since two different parsers are used: new for preview, old for rendering. the former is enabled partially to catch differences and bugs like that.

**Comment by Type-kun** [comment]
As for the bug itself, it's due to https://github.com/r888888888/dtext_rb/blob/master/ext/dtext/dtext.rl#L136-L137 - first rule wouldn't match if there's a pipe character inside double brackets, second rule wouldn't match unless there's any non-pipe character before the pipe. Ragel is still moonspeak to me (and I repeatedly fail to find any decent documentation), but if rules can be applied in order, then it'll be enough to apply `aliased_wiki_link` first, and change `basic_wiki_link` to use `nonbracket` instead of `nonpipe`, then it would match anything in `[[...]]` unless it matches `[[...|...]]`.

**Comment by BrokenEagle** [comment]
I see what you mean about the code... it's by far the strangest code I've ever seen.  I had always wondered where the other DText parser was located.  I'm guessing that the one in the Danbooru repository is the preview version, and the one in the DText repository is the rendering version...?

It makes it difficult figuring out exactly how the textile links are being parsed.  I've [emulated the parser in the Danbooru repository](https://github.com/r888888888/danbooru/blob/master/app/logical/d_text.rb#L81-L104) to test which external links in the wikis are dead/alive, but I'm already running into differences between the DText previewer and renderer. (I.e. links are invalid when presented by the preview function, but work fine when presented with the actual HTML page.

**Comment by r888888888** [comment]
I'm not even sure if ||_|| should be valid syntax. How should that be parsed with the current rules? That could be a page about | with _|| as the alias. Or it could be a page about ||_ with | as the alias.

**Comment by r888888888** [comment]
Honestly if these are the only exceptions it's easier just to hard code them in as edge cases.

**Comment by evazion** [comment]
http://danbooru.donmai.us/tags?search[name_matches]=*|*&search[order]=count. 14 tags, 5 bigger than 100 posts, `|_|` being the only really large one.

IMO the `|` should be a forbidden character in tags to avoid conflicts with this syntax.

Otherwise the rule could be that tags may start or end with `|`, but not contain a `|` in the middle. This wouldn't work for [[`\||/]]` or `[[<|>_<|>]]` or `[[||_|| | silly face]]` though.

**Comment by Type-kun** [comment]
> it's by far the strangest code I've ever seen.
Then you shouldn't look at C code that's generated from that .rl file :3

> I'm guessing that the one in the Danbooru repository is the preview version, and the one in the DText repository is the rendering version...?

It's the other way around. Separate repository is ragel-based; it looks unusual but should work much, much faster, since it translates to pure C and uses state machine instead of regexp, mostly consuming the string sequentially.

>IMO the  |  should be a forbidden character in tags to avoid conflicts with this syntax.

way too radical for something as insignificant as wiki shortcut, IMO. You can always use full link syntax if you need to.

@r888888888, one way I see is to disallow pipes in both tag and alias for `aliased_wiki_link`. i.e. `[[nonpipebracket+|nonpipebracket+]]`, set `basic_wiki_link` to match `[[nonbracket+]]`, and swap them in the `inline` scanner so that `aliased_wiki_link` matches first. Judging by documentation, scanner will choose based on longest match first - and both will match exactly the same string; in that case, it chooses the entry which comes first. That will not work for `len|arc` tag, though, and might break existing cases where pipe was used in the description... 

Maybe make another link shortcut, something like `[[[]]]`, that explicitly never searches for alias and simply links whatever's inside as a wiki?

**Comment by Type-kun** [comment]
> it's by far the strangest code I've ever seen.
Then you shouldn't look at C code that's generated from that .rl file :3

> I'm guessing that the one in the Danbooru repository is the preview version, and the one in the DText repository is the rendering version...?

It's the other way around. Separate repository is ragel-based; it looks unusual but should work much, much faster, since it translates to pure C and uses state machine instead of regexp, mostly consuming the string sequentially.

>IMO the  |  should be a forbidden character in tags to avoid conflicts with this syntax.

way too radical for something as insignificant as wiki shortcut, IMO. You can always use full link syntax if you need to.

@r888888888, one way I see is to disallow pipes in both tag and alias for `aliased_wiki_link`. i.e. `[[nonpipebracket+|nonpipebracket+]]`, set `basic_wiki_link` to match `[[nonbracket+]]`, and swap them in the `inline` scanner so that `aliased_wiki_link` matches first. Judging by documentation, scanner will choose based on longest match first - and both will match exactly the same string; in that case, it chooses the entry which comes first. That will not work for `len|arc` tag, though, and might break existing cases where pipe was used in the description... 

Maybe make another link shortcut, something like `[[[]]]`, that explicitly never searches for alias and simply links whatever's inside as a wiki?

**Comment by evazion** [comment]
> Maybe make another link shortcut, something like [[[]]], that explicitly never searches for alias and simply links whatever's inside as a wiki?

This still has ambiguity. Would `[[[saw]]]` parse as a link to the general tag `saw` or a link to the artist named `[saw]`? Would `[[[[saw]]]]` parse as `[saw]` or `[saw` plus a trailing `]`?

`{` and `}` are problematic too, should `{{:}}}` mean link to the tag `:}` or the tag `:`?

> way too radical for something as insignificant as wiki shortcut, IMO. You can always use full link syntax if you need to.

I claim it's easier to rename problematic tags than to go to great lengths trying to accommodate them. It's not that many tags and it's hardly worse than the limitations that already exist (i.e. tags can't contain `*` or `%` or `,` or leading `~` or `-`).

**Comment by Type-kun** [comment]
>This still has ambiguity. Would  [[[saw]]]  parse as a link to the general tag  saw  or a link to the artist named  [saw] ? Would  [[[[saw]]]]  parse as  [saw]  or  [saw  plus a trailing  ] ?

Well, we could go for something else entirely like `![[...]]`. doesn't solve `[saw]` problem, but currently it would break `[[...]]` notation either way.

> I claim it's easier to rename problematic tags than to go to great lengths trying to accommodate them. 

The only think `|` is breaking is shortcut aliasing, while the rest of forbidden symbols break tag searches, so the case is a bit different.

**Comment by r888888888** [comment]
I think I second the idea of just making these into aliases. It's just a side effect of adopting Textile's syntax instead of something more verbose but consistent. There are too many exceptions in the <10 post range to accommodate them into the parser.
