### ISSUE TITLE
Artist Creates/Renames Should Check for Conflicting Wiki Pages

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2717]
A user recently DMail'ed me about an issue in which he created an artist with the same name as an ambiguous tag with an existing wiki.  The overall effect was it created an artist in the general category and tied the existing wiki page to that artist.  

The fix wasn't hard but a bit convoluted.  It involved renaming the artist first, and then renaming the wiki back (since renaming the artist renames the wiki).

I've replicated the issue on Testbooru which can be seen with the following links.

http://testbooru.donmai.us/artists/5
http://testbooru.donmai.us/wiki_pages/6

**Comment by r888888888** [comment]
I would argue you never want to create an artist for an existing wiki page and that you should be forced to either rename the wiki page or rename the artist first.

**Comment by r888888888** [comment]
An attempt to update this in 2a5343b8cfd6a209f78b79638980f9e9759596ec

**Comment by evazion** [comment]
Isn't the actual conflict when the artist name is already taken by a general, copyright, or character tag? Whether that tag has a wiki page or not doesn't really matter, it conflicts either way. IMO the validation should be that the tag corresponding to the artist entry must be an artist tag.

Also, I think enabling tag autocomplete in the artist name field would make it easier to detect conflicts when naming artists.

**Comment by nonamethanks** [comment]
I was about to open an issue on something related to this, but reverse: creating a wiki instead of an artist page and then having to go through hoops to delete/move the wiki so that creating the artist page is possible.

It's apparently not uncommon to end up hitting this problem - I just fell for it again and I've spoken with several other builders who routinely fall for this, because it's not immediate to tell apart a wiki or artist creation page if one is not completely focused on spotting the differences, as muscle memory often kicks in before you can think.

Is it feasible to allow an artist page to overwrite or merge into a wiki page with a checkbox if the first try at submitting fails for such a reason? Maybe only allow this if the tag is already an artist tag, as to avoid accidentally merging into gentags or other categories.

**Comment by evazion** [comment]
Moved the bug with conflicting artist/wiki entries to #4107.
