### ISSUE TITLE
[Feature Request] Related tags page for HTML.

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2750]
Seems like there's a demand to see related tags outside of editing a post.

See [forum topic #13349](http://danbooru.donmai.us/forum_topics/13349) for the full conversation.

Plus, there's plenty of room in the Tags submenu for additional entries.

While we're on this topic, would it be possible to expand the results to more than 25, or are there performance reasons why this couldn't be done?

**Comment by evazion** [comment]
Thoughts on this:

* Instead of a separate page (or in addition to I guess), I think the related tags list in the sidebar for searches should be divided into character/copyright/artist/general lists. The current sidebar is pretty useless, it's flooded with too many common gentags. It should be as simple as searching a copyright to see the related characters.

* Looks like calculating related tags by category basically just finds 300 random posts and counts up the tags (see [1] and [2]). So to include it in the sidebar would require caching the calculation. Also adding the sidebar would maybe have to be done in javascript, since doing it serverside could block the page load.

* It looks like the results are just truncated to 25 after processing, so increasing that shouldn't hurt performance, although I don't know how good the results would be given the low sample size.

[1]: https://github.com/r888888888/danbooru/blob/master/app/logical/related_tag_calculator.rb#L10-L12
[2]: https://github.com/r888888888/danbooru/blob/master/app/logical/related_tag_calculator.rb#L72-L92

**Comment by BrokenEagle** [comment]
Maybe conditionally cache the results whenever a singular tag gets searched and set a value like "updated_at".  Whenever a singular tag gets searched, it would check the "updated_at" value, and if it's been less than 24 hours, will pull from the current cached results.  Otherwise, it would generate a new set of results and set the "updated_at" value.

**Comment by Type-kun** [comment]
>Maybe conditionally cache the results whenever a singular tag gets searched and set a value like "updated_at". Whenever a singular tag gets searched, it would check the "updated_at" value, and if it's been less than 24 hours, will pull from the current cached results. Otherwise, it would generate a new set of results and set the "updated_at" value.

It's already happening, related tags are stored in tag table and updated periodically. 

Basic solution is in PR #2826, improvements are welcome.
