### ISSUE TITLE
unable to register an account with a blank email

### ISSUE THREAD

**Issue by mindcrimes** [r888888888/danbooru#2760]
attempting to register on my test booru with a blank email, I get the error "ERROR: duplicate key value violates unique constraint "index_users_on_email" DETAIL: Key (email)=() already exists."
Running debian wheezy with postgresql 9.5

**Comment by Type-kun** [comment]
@r888888888 this actually happens everywhere including testbooru. Didn't check the main booru but I strongly suspect it's the same. It doesn't look like anything was changed in the user model itself, so I strongly suspect that rails begun sending blank form fields as empty strings rather than nils at some point. Either `before_save` function should be written to reset blank email to `nil`, or one of the gems to nilify blanks should be used if this somehow affected other places.
