### ISSUE TITLE
ArtStation upload integration

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2769]
We should integrate support for uploads from ArtStation.com. Discussion in http://danbooru.donmai.us/forum_topics/13057.

**Comment by BrokenEagle** [comment]
I left a [comment on the Danbooru forums](http://danbooru.donmai.us/forum_topics/13646?page=3#forum_post_126375), but basically, 47% (481/1023) of the Artstation images are the sample size. Since getting the fullsize image isn't the most intuitive, it's likely this trend will continue on until this issue get fixed.

**Comment by r888888888** [comment]
I thought someone was working on a branch for this but if it hasn't been tackled yet by anyone I can look into it.

**Comment by BrokenEagle** [comment]
More info [on the forums](http://danbooru.donmai.us/forum_topics/13057?page=2#forum_post_126515).  

The primary note though, was in addition to /large/ links, the URL rewriter should also work on **/medium/** and **/small/** links. Admittedly, those links are less likely to be used, but they should be handled correctly just in case.

**Comment by BrokenEagle** [comment]
Forgot to mention, but not all **/original/** links work, with the "largest" size being **/large/**.  This needs to be detected somehow.

See the wiki, [Artstation samples](http://danbooru.donmai.us/wiki_pages/82713) for more information.
