### ISSUE TITLE
Hide API key on user page

### ISSUE THREAD

**Issue by bugmen0t** [r888888888/danbooru#2785]
Your API key is something you very rarely need to look up on the site, as usually you'll have it in your script already. However, it gives full access to the site as your account, and it's not obvious how it might be changed. Therefore, having it on your user page is pretty much like having your password there in plain text, which makes me somewhat uncomfortable when I see it. So this is a (hopefully simple) feature request: On your own user page, if you have generated an API key, instead of showing it there, have a link to a separate page that shows the key, and provides an option to regenerate it as well.

**Comment by BrokenEagle** [comment]
Would it be good enough to hide it by default with some kind of Javascript, and have some kind of toggle to make it visible...?  

That'd probably be a lot easier to implement than a completely new page, making it much more likely to get addressed in a timely fashion...

**Comment by bugmen0t** [comment]
That was actually the first thought I had, but then I thought you really almost never need to see it so there's no point having it in the page and appear for a fraction of a second. Having it hidden by default would be an improvement for sure, and probably enough, but it doesn't seem it would be that much harder to add a new page. But yeah, if it were just hidden I'd still be happy.

**Comment by evazion** [comment]
PR #2788 moves it to a separate page, adds key regeneration/deletion options, and requires you to reenter your password to view or change your key.

The password confirmation step is important because otherwise if someone gets into your account they could steal your API key and use it to retain backdoor access to your account.

**Comment by bugmen0t** [comment]
That looks great, thank you!

**Comment by BrokenEagle** [comment]
@evazion 

Not sure it's necessary, but if you want someone to test it out, you could throw it up on your Devbooru...

**Comment by evazion** [comment]
@BrokenEagle: updated http://devbooru.evazion.ml:3000/ to commit aa5e651.

Also I should note that this also makes it possible to view/change your API key using the API itself. You have to include your password for confirmation though. The calls are

    view key: POST /users/1/api_key/view.json?user[password]=your_password
    regenerate key: PUT /users/1/api_key.json?user[password]=your_password
    delete key: DELETE /users/1/api_key.json?user[password]=your_password

**Comment by BrokenEagle** [comment]
@evazion 

Finished my initial testing and found a couple points of note:

1. When regenerating the API key from the web interface, it sends 2 subsequent calls to change the API key.  An HTTP sniffer was used to determine this.
https://img42.com/ThLYd

2. This isn't directly related, but there were a ton of .js and .css files being pulled instead of just a monolithic .js and .css (It's probably related to your setup). Determined from both the HTTP sniffer and the page source code.
https://img42.com/mL6PW

3. API calls to the regenerate function only yields a 204 response instead of a 200 response, so it was impossible to determine the new API key without going back the the web interface and refreshing the page.
https://img42.com/heH9b

Just as a final aside, the necessity of a password to view the API key when you are passing the very same API key forward seems a bit superfluous.  Additionally, shouldn't it be a "200 OK" response instead of a "201 Created" response...?

Send:
`POST http://devbooru.evazion.ml:3000/users/11/api_key/view.json?user[password]=password&api_key=UIQgL9-xhjCcu67rVLqZEINNhPo_Dgj9iIaxWjeF7mo&login=builder`

Response:
`201 Created`
`{"id":5,"user_id":11,"key":"UIQgL9-xhjCcu67rVLqZEINNhPo_Dgj9iIaxWjeF7mo","created_at":"2016-12-20T21:12:38.540-05:00","updated_at":"2016-12-20T21:12:38.540-05:00"}`

**Comment by r888888888** [comment]
Hmm, 1 is probably caused by the js hook being run twice so one event triggers twice. 2 is just a side effect of running in development mode, in production mode everything is concatenated together.

**Comment by evazion** [comment]
Yeah I don't know what's up with it triggering twice. It does it on my devbooru but not on my local machine.

> API calls to the regenerate function only yields a 204 response instead of a 200 response, so it was impossible to determine the new API key without going back the the web interface and refreshing the page.

This is really a sitewide issue. The Rails default is to just return `204 No Content` for PUT requests and not return the new data. Danbooru overrides this for a handful of calls (post updates are one, don't remember what else), but most calls follow the default of returning nothing. The best way to fix it would be to find a way to override it sitewide.

> Just as a final aside, the necessity of a password to view the API key when you are passing the very same API key forward seems a bit superfluous.

Consider a situation where an XSS exploit allows an attacker to embed malicious javascript into some page on the site. Search github for "XSS", I've found several such exploits in the past. In that scenario the attacker could use javascript to make a `POST /users/11/api_key/view.json` call when you view the page and steal your API key. Requiring password confirmation for the API call prevents this.

Technically this is only necessary in a browser session when you're logged in using cookies, not when you're using an API key, but it was simplest to just require it all the time however you're logged in.

**Comment by BrokenEagle** [comment]
> Technically this is only necessary in a browser session when you're logged in using cookies, not when you're using an API key, but it was simplest to just require it all the time however you're logged in.

Yeah, that's what I was thinking of when I wrote that.  It unfortunately reduces the use cases of the view API key function to just getting the metadata such as the dates...  It's not such a big deal for myself though, since I'm more likely than not to change the API key from the web interface anyways...
