### ISSUE TITLE
Give Moderator+ Option to Prevent Comments From Being Downvoted

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2799]
Efforts from Moderators to control the conversations on posts should not be curtailed via comment downvoting.

See Danbooru [forum #124463](http://danbooru.donmai.us/forum_topics/9127?page=144#forum_post_124463) for the original request.

Admin accounts already have their comments protected.  This would be similar to Issue #2757 where the DMail filter was removed for Moderator accounts where it already existed for Admin accounts.

**Comment by BrokenEagle** [comment]
There was some pushback on the [Danbooru forums](http://danbooru.donmai.us/forum_topics/9127?page=144#forum_post_124470) from Type-kun:

> To be frank, I don't like that ALL my comments are immune to downvotes now. It's actually somewhat restricting, since making bad jokes or controversial statements feels like abusing my authority.

Therefore, we should instead give Moderator+ accounts the option (like a checkbox) to make their comments downvote-proof instead of making that the default.

**Comment by BrokenEagle** [comment]
Related to the above comment, the following comes from OOZ662 in the Danbooru 2 Issues Topic:

> On the topic of mod/admin comment voting, I make plenty of doofy and/or "regular user" comments that should be subject to score. I've seen other sites (most notably Reddit) allow "staff" level accounts to flag certain comments as being "official business" which marks them in a special way and/or keeps them visible. I'm not sure how hard tha'd be to code in, but I'd imagine it being a checkbox next to "No Bump" that would add something below the timestamp denoting that the comment is "official" (no decently clear words or short phrases come to mind right now) and make it immune to voting.

**Comment by evazion** [comment]
PR #2804 adds a 'post as moderator' checkbox. I call these comments sticky comments, for the sake of having a name. Stickied comments are always visible and are highlighted. They can still be downvoted, but it has no effect.

I did it this way so that mods can sticky existing comments that may have already been downvoted. Mods can also sticky other people's comments. This is mainly intended so that mods can sticky old warnings given by other mods, but it's also allowed to sticky regular users' comments, in case that's useful.
