### ISSUE TITLE
Standalone IQDB page

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2833]
Discussion: http://danbooru.donmai.us/forum_topics/13630

> Since Danbooru has it's own IQDB engine available to registered users, it'd be nice if there was a standalone page like http://iqdb.org where this functionality could be accessed, outside of the Uploads page or the Find Similar function.

**Comment by BrokenEagle** [comment]
I added a pull for the standalone page that handles the case of post ID or URL as an input.  It would still be nice however to add support for local files.

I see a few ways to do this:

1. Convert the file to a thumbnail and host it somewhere
a. Temporarily on Danbooru
b. Temporarily on another 3rd party site
2. Modify IQDBS so that it can take file input from Danbooru
a. Add support for POST endpoint and multipart file encoding

1.a might be the simplest to implement, but it depends on how much space is available for thumbnails.  I can't imagine that these thumbnails would need to be stored for more than an hour though.

**Comment by evazion** [comment]
This exists at https://danbooru.donmai.us/iqdb_queries and it now supports files.
