### ISSUE TITLE
Restrict name change requests back to admin-only

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2843]
It's fine to display the chain of previous names in the user profile, but the change request itself contains a message that can be sensitive or private since it was supposed to be directed to admin.

**Comment by evazion** [comment]
http://danbooru.donmai.us/user_name_change_requests/210 is linked but still private, it's only visible to the original requester or admins.

PR #2842 would make the `/user_name_change_requests` listing open to members instead of admin-only, and it would include reasons there too, but only for  admins or the original requester.

**Comment by Type-kun** [comment]
Ah, ok, I was under impression it was open for everybody now.
