### ISSUE TITLE
Link to Managing Saved Searches Difficult to Find/Use

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2847]
From the [saved searches thread](http://danbooru.donmai.us/forum_topics/13612?page=2#forum_post_125774).

Basically, the link is difficult to find and/or use, as it is currently a multi-step process. I proposed reverting the link and placing a **&raquo;** next to it that would instead link to **search:all**, which seemed to be acceptable.  It would look like the following:

[Saved searches](http://danbooru.donmai.us/saved_searches) [»](http://danbooru.donmai.us/posts?tags=search%3Aall)

**Comment by r888888888** [comment]
I don't like that because searching is the common use case and it's being given the smallest visual footprint. Maybe invert the behavior so that the arrow goes to the manage page. That's a fairly novel UI quirk that isn't used anywhere else on the site though so it's not exactly intuitive.

I will play around with the design to find some sort of compromise. Maybe reprising the styling of subscriptions is the right idea.

**Comment by BrokenEagle** [comment]
Yeah... the primary reason I suggested the above format is because it does mirror how some of the data items in the Information section on the Posts page are displayed, particularly the Uploader and Source data items.
Example:
...
Uploader: [BrokenEagle98](http://danbooru.donmai.us/users/23799) [»](http://danbooru.donmai.us/posts?tags=user%3ABrokenEagle98)
...
Source: [pixiv.net/member_...](http://www.pixiv.net/member_illust.php?mode=medium&illust_id=60957365) [»](http://danbooru.donmai.us/posts?tags=source%3Ahttp%3A%2F%2Fi2.pixiv.net%2Fimg-original%2Fimg%2F2017%2F01%2F15%2F22%2F40%2F31%2F)
...

Still, I think any kind of link to manage Saved Searches that doesn't require a tag search first with the **search** metatag would suffice for most users.
