### ISSUE TITLE
Account deletion should remove name change requests

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2851]
As users deleting the account often seek to leave as little of their presents on the site as possible, having their username history on full display in the profile isn't exactly helpful. It also stands true for "Name changed" feedbacks.

**Comment by evazion** [comment]
I'm leery about deleting data so PR #2852 would just hide change requests and feedbacks for deleted accounts. It assumes that anyone with a username of `/user_[0-9]+~*/` is a deleted account, which is not entirely correct since registering accounts matching that pattern is not prevented. I don't know how else to detect deleted accounts though.
