### ISSUE TITLE
Improve saved search usability

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2921]
Now that saved searches are more or less fleshed out, it's about time to work on usability. Here's a few issues and suggestions:

- [x] https://danbooru.donmai.us/saved_searches doesn't seem to be linked anywhere, which is actually a disaster since it's the only place allowing to rename categories and delete saved searches. 

- [x] Saved searches excerpts in user profiles are listed on order of last category update or something like that. It would make more sense to list categories alphabetically, uncategorized first. Otherwise a category jumps up in the listing as soon as a search is added to it, and I prefer my profile layout to be static so that I can get all the relevant info from a quick glance. I've seen similar requests on the forum, too.

- [x] It would be great if https://danbooru.donmai.us/saved_searches allowed to directly add new searches to the category. Actually, it would be ideal to have an "edit" button for categories, allowing both to rename the category and modify/add/remove the searches, maybe move them as well.

- [ ] Can category refresh time be somehow displayed in the profile excerpts? I often find myself wondering whether the saved search is stale or there is really no new posts. Also, perhaps add a manual refresh option for gold+/platinum+? Enable it after an hour from last refresh, for example.

- [x] There's no easy way to access individual searches from a saved search category. Subscription tag combinations were listed in the profile as far as I remember, perhaps do the same for saved search categories? If it's considered too much clutter, it's possible to put this info into collapsible boxes and tie them to category listing - http://puu.sh/uGTV1.png in this place in the profile.

- [x] Since it's impossible to save the same query under different categories, when searching for the already saved tag combination, "save search" button in the post listing should be replaced with "edit saved search" and "delete saved search".

- [x] When saving a search, the category auto-completion ignores user input. Even if you press some random keys, the suggestions will always list all of your saved search categories in apparently random order. The auto-completion suggestions should only list categories that contain whatever you entered and the results should be listed alphabetically.

**Comment by kittey** [comment]
> https://danbooru.donmai.us/saved_searches doesn't seem to be linked anywhere, which is actually a disaster since it's the only place allowing to rename categories and delete saved searches. 

It’s linked in the bottom left when viewing any of your saved searches, or more precisely, whenever the tag search contains `search:`. I don’t think it’s a good idea to have it only in there.

The auto-complete suggestions when saving a search should also be more sensible. I took the liberty to update Type-kun’s post so that we have only one list.

**Comment by Type-kun** [comment]
Ah, right, I've overlooked it. Sorry, I'm down with a cold, so I can't concentrate properly. Either way, yes, it should be featured more prominently.

The problem with autocomplete that after fixing it you'll have to remember what your search categories are called, to input a first letter. Maybe there's something like a combobox in jqueryui? A control emulating `input` and `select` combination? I'm sure I've seen something like that somewhere on the web.

**Comment by evazion** [comment]
> It would be great if https://danbooru.donmai.us/saved_searches allowed to directly add new searches to the category. Actually, it would be ideal to have an "edit" button for categories, allowing both to rename the category and modify/add/remove the searches, maybe move them as well.

IMO it should work like this:

- [ ] At the bottom of each category, have an text input with an `Add` button that adds a new search to that category. It should be done with ajax so you can bulk add multiple searches without reloading the page.
- [ ] The `Edit` link next to each search should change the search to an input box, to allow you to edit the search inline without loading a new page. A category dropdown should also appear for changing the category.
- [ ] The `Delete` link should also be an ajax update that deletes the search without reloading the page.
- [ ] Each search in a category should have a checkbox beside it. You should be able to check multiple searches and bulk delete or recategorize all of them at once.

> Can category refresh time be somehow displayed in the profile excerpts? I often find myself wondering whether the saved search is stale or there is really no new posts. Also, perhaps add a manual refresh option for gold+/platinum+? Enable it after an hour from last refresh, for example.

I think it should be displayed in a "last updated" column in the `/saved_searches` listing. And really it ought to update by itself such that manual refreshing isn't needed. The site could automatically schedule a refresh whenever an outdated saved search is viewed. Most people will hit refresh every time they notice an outdated search anyway, so the site may as well do it automatically.

**Comment by evazion** [comment]
And as long as we're wishlisting:

- [ ] The `Save search` button should be near the search box. The current way it's shoved in between the thumbnails and the paginator is horrible. It could go in the sidebar, but I think making the `Go` button next to the search box into a [dropdown button](https://v4-alpha.getbootstrap.com/components/dropdowns/#split-button-dropdowns) would be better. I don't know if jqueryui has a widget for this though.

    Another idea would be to have a "Save this search" link inside the autocomplete box.

- [ ] There should be a keyboard shortcut for saving a search. I've been using `shift+S` for this in my userscript.

- [ ] Often when viewing a post I want to save the artist. It would be nice if you could save or unsave tags straight from the tag list. The tag list should also indicate which tags you have already saved.

- [ ] There should be a way to toggle `/saved_searches` between gallery view (the thumbnail view currently in your profile), inline list view (the "compact" view in `/tag_subscriptions`), and detailed list view (the current view in `/saved_searches`). Gallery view should be the default, as checking for new posts is the most common activity.

- [ ] It might be nice if thumbnails in a saved search gallery had a caption beneath indicating a) the saved search that it matched and b) when it was uploaded. When you have 100+ artists in one category, it becomes difficult to tell which post is by which artist, and how recently it was posted.

Really, instead of putting saved searches in profiles, I think the front page itself should default to showing a mix of your recently updated saved searches, popular posts, recent posts, recent pools, etc. You should be able to immediately see "what's new on Danbooru?" without having to navigate to a bunch of different places.

**Comment by r888888888** [comment]
It's probably time to create a separate model for categories, which is what I should have done in the first place.

**Comment by evazion** [comment]
How about making categories into a `text[]` array? Each saved search would then have a list of categories in the same way that a post has a list of tags.

**Comment by r888888888** [comment]
That's interesting.

Listbooru's responsibilities could be reduced to just executing, caching, and perhaps aggregating searches. This removes a lot of the data duplication that's annoying to deal with right now. I think with the long term goal of offloading post versions there's no problem with handling saved searches almost entirely from inside the main Postgres database.

The only problems with that: producing a list of all the tags used by a person. Some people have hundreds of saved searches.

**Comment by evazion** [comment]
I think the query would be something like this: http://www.sqlfiddle.com/#!15/16e3be/20/0

```sql
-- get the set of all saved search categories used by a given user. unnest explodes an array into a set of rows.
SELECT DISTINCT category FROM saved_searches, unnest(categories) as category WHERE user_id = 20;
```

Not sure how expensive that would be, but it could always be memcached if it's too slow.

**Comment by Type-kun** [comment]
> Really, instead of putting saved searches in profiles...

Not "instead of", please. I don't browse new or popular, I'm generally only interested in things I've already subscribed for. Having them in profile gives me instant feedback if there was anything new, since I remember the thumbnails from the last time.

> How about making categories into a  text[]  array? Each saved search would then have a list of categories in the same way that a post has a list of tags.

Interesting indeed, but why? Currently categories serve to split up saved searches and group them together. I don't really see a reason to put a saved search into multiple groups, since it'll just appear in both then? Besides, a model for category should probably exist anyway, because it can and should have more properties that just a name - last update time and being private or public, for example.

**Comment by r888888888** [comment]
Most of these issues will be addressed in da06bee0ab19c683a278a787e9c87b78d7ec3993

**Comment by evazion** [comment]
> Interesting indeed, but why? Currently categories serve to split up saved searches and group them together. I don't really see a reason to put a saved search into multiple groups, since it'll just appear in both then? 

A use case is categorizing your artists by the things they draw - which copyrights, which characters, hentai vs nonhentai, comics vs noncomics, so on - so that when you have hundreds of artists you can organize them.

Danbooru's basic concept is that things are categorized using tags. I think everything should operate on that principle.

> Besides, a model for category should probably exist anyway, because it can and should have more properties that just a name - last update time and being private or public, for example.

IMO those things should be properties of individual searches. AFAICT on listbooru saved searches are shared between users, such that updating a search for one person updates it for everybody. So categories don't really have a singular update time, only individual searches do.

> Not "instead of", please. I don't browse new or popular, I'm generally only interested in things I've already subscribed for. Having them in profile gives me instant feedback if there was anything new, since I remember the thumbnails from the last time.

There are several issues with saved searches being in your profile:

* You have to scroll past your stats/uploads/favorites, when you just want to check subscriptions.
* Profiles can be slow to load, because they're counting up all these stats you don't care about. (approval count is the main bottleneck, since it's not indexed or cached).
* Some people have complained about the extra clutter saved searches add to their profile.
* But other people want more thumbnails for each category.

Therefore I think they should go somewhere other than your profile. Basically I think `/saved_searches` should default to the thumbnail view your profile currently shows, with a way to toggle to the current list view when managing your searches.

As for the front page: think of Pixiv, or even Youtube. Their front pages aren't just whatever crap happened to be uploaded in the past few minutes. That would be terrible, yet it's what we do.

**Comment by Type-kun** [comment]
> A use case is categorizing your artists by the things they draw - which copyrights, which characters, hentai vs nonhentai, comics vs noncomics, so on - so that when you have hundreds of artists you can organize them.

Hm, I sort of get it, but I can't imagine what thumbnail view would look like. Would searches still get separated by category and aggregated as they are now, but simply with a possibility of search being in multiple categories?

Also, about refresh time: if it's a saved search property rather than a category property, then just show a range. `(least recent datetime) - (most recent datetime)` would still be much better than no info at all. Individual refresh times could be displayed on the detailed listing.

> There are several issues with saved searches being in your profile:

Well, profile load time wasn't ever an issue for me, and it's easier to click top-left-most button and scroll down once than click through a maze of links to finally get a look at `/saved_searches`. I suppose you could counter that with displaying saved searches at front page, but then it would have to be reworked heavily. In fact, since there's a split in the userbase (some don't want it, other want more), it might be better to make such things configurable once they are implemented, rather than disable them forcefully for everybody. It's more work, but part of why I absolutely love Danbooru is flexibility.

**Comment by r888888888** [comment]
I will look into displaying the timestamp sometime in the future once all of this gets deployed and unused data gets cleaned up. Listbooru would have to somehow store that data and it doesn't currently.

**Comment by r888888888** [comment]
I've tried moving the save button to the sidebar (and adding some other useful searches in the process).

**Comment by johnsmith1980** [comment]
According to evazion's forum post, the Save button was "moved to the new '+' dropdown next to the search box."
But I'm not seeing that + dropdown?  I tried disabling all my Greasemonkey scripts and still don't see it. I'm on Firefox 52.

**Comment by r888888888** [comment]
Have you tried shrinking the font size? Maybe it's overflowing and it's just hidden.

**Comment by Type-kun** [comment]
It was the custom CSS, see http://safebooru.donmai.us/forum_posts/128858.
