### ISSUE TITLE
Tumblr download strategy downloads incorrect file.

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#2938]
ref: https://danbooru.donmai.us/forum_topics/9127?page=167#forum_post_128752

Apparently tumblr sometimes returns different files for the same URL. When downloading this file

 * http://68.media.tumblr.com/ff41206113b69a05283784a121a9190a/tumblr_okf33cpXvt1v2gw9ko1_1280.png

you get a PNG or a JPEG, depending on which server you get for http://68.media.tumblr.com.

I guess the way to deal with this would be to do a DNS lookup, get all the IPs for http://68.media.tumblr.com, download it from each one, then choose the file that is best.

**Comment by BrokenEagle** [comment]
As [discussed on Danbooru](http://danbooru.donmai.us/forum_topics/9127?page=168), I'm not sure there is a plausible method to guarantee that all of the IPs for a site can be retrieved, dynamically or otherwise.  The server IPs returned seem to be regional, and I've also read that IPs can be rotated around daily and maybe even hourly.

**Comment by BrokenEagle** [comment]
It seems that some Tumblr links contain the MD5 hash of the full-size image.  This can potentially be used to download the correct fullsize image.  If a comprehensive list of 68.media.tumblr.com servers is documented, it would be interesting to see if the "correct full-size image" could always be downloaded.

**Comment by evazion** [comment]
I haven't seen any reports of this still happening, so I'm going to close this as fixed by #3178.
