### ISSUE TITLE
Add Moebooru Rewrite for Sample Images

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2942]
From the [Danbooru forums](http://danbooru.donmai.us/forum_topics/13646?page=9#forum_post_128891):

> Rignak said:
> 
> Isn't there a way to make the bookmarklet download the full-sized image when a sample from yande.re is given ? It works when the url is in files.yande.re/jpeg/[...].jpg and upload the files.yande.re/image/[...].png but not with files.yande.re/sample/[...].jpg.

This might be a little tricky as it's impossible to know from just the sample image URL whether the full-size URL is a PNG or JPG.

**Comment by evazion** [comment]
Fixed in 958a9f5. This turned out to be tricky indeed. We can't always get the extension from the API because Konachan's API doesn't have the `file_ext` field (but it does have `file_url`), while Yande.re's API doesn't always have the `file_url` (it's not present when the post is deleted). Yande.re also doesn't return anything when doing a `md5:<hash>` search for a deleted post. So in the worst case we have to fall back to testing both the .jpg and .png files to find the one that works.
