### ISSUE TITLE
Add New Pixiv Image Scheme Into Download/Rewrite Strategies

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2946]
From the [Danbooru forums](http://danbooru.donmai.us/forum_topics/9127?page=169#forum_post_128969):

It seems like the Pixiv URL image format is fluctuating between two image URLs.

1. https://i1.pixiv.net/img-original/img/2017/03/23/00/14/58/62048340_p0.jpg
2. https://i.pximg.net/img-original/img/2017/03/23/00/14/58/62048340_p0.jpg

(1.) works, but (2.) is broken because the regexes most likely fail on the "i.pximg.net".

**Comment by r888888888** [comment]
Kinda messy but should be fixed in b391e6e9e11fd2b5a40c79f0816983aafe95301e

**Comment by evazion** [comment]
This needs to be reopened. This format:

* https://i.pximg.net/img-master/img/2014/05/15/23/53/59/43521009_p1_master1200.jpg

isn't detected. This is used in manga gallery samples. Rewriting to

* https://i.pximg.net/img-original/img/2014/05/15/23/53/59/43521009_p1_master1200.jpg

doesn't seem to work.

**Comment by Type-kun** [comment]
https://danbooru.donmai.us/posts/2679655 also doesn't have it's url correctly rewritten in the post model. It seems to be the same problem as mentioned above, with url being https://i.pximg.net/img-master/img/2017/04/03/07/05/01/62230807_p1_master1200.jpg.

**Comment by evazion** [comment]
Come to think of it, posts already have the parsed pixiv id in the `pixiv_id` field. It would be simpler/more robust to use that for generating the sidebar link. Only catch is that gallery pages can share the same ID, but the sidebar link currently doesn't account for that anyway.

I also think it would be more useful to render the sidebar link as `Source: pixiv #1234` rather than truncated as `Source: pixiv.net/member_...`.
