### ISSUE TITLE
Subscriptions section in profile should be removed

### ISSUE THREAD

**Issue by chinatsu-chan** [r888888888/danbooru#2956]
Since subscriptions are now merged, the 'Subscriptions:' section underneath the Saved Searches one should be removed.

**Comment by Type-kun** [comment]
Were they already migrated to saved searches automatically? I kinda missed the moment, since I migrated manually.

**Comment by r888888888** [comment]
They were not migrated automatically, since I expected many of them to be from users who no longer use the site.

**Comment by Type-kun** [comment]
Hm, then gradually phasing them out might be better. Forbid to create new subscriptions, don't show them in profiles unless there's any, etc.

**Comment by kittey** [comment]
In addition to Type-kun’s suggestion, maybe show a nag-box like the one for the mod queue: mention that the user still has subscriptions and that they’re not being updated anymore since March 2017; link to a relevant wiki page; ask about migrating subscriptions to saved searches and present the options “Migrate all subscriptions”, “Delete all subscriptions” and “Hide this for 20 hours” or something like that. Try to word it in a way that users who already migrated but didn’t delete their subscriptions don’t get confused.
