### ISSUE TITLE
Automated tags requiring file access are removed when editing posts moved to asset server

### ISSUE THREAD

**Issue by Type-kun** [r888888888/danbooru#2960]
Related to #2500 and #2943. When file is edited, some tags are always re-evaluated and added or removed based on post information (see `add_automatic_tags` in post model). Checks for `animated_gif` and `animated_png` in particular access the file to read image metadata and find out whether the post is animated. The problem is, when file is moved to asset server and is not actually present on server anymore, checks fail, and decide that image is not animated, so `animated_gif` and `animated_png` are removed from tag list on every edit.

**Comment by evazion** [comment]
I've mentioned this before, but I think `animated_gif` and `animated_png` should run only on post creation. Actually `video_with_sound` already works this way, since it's handled during upload instead of in `add_automatic_tags`.

This would be a change in that these tags would no longer be locked from editing: people could remove them and they wouldn't be readded again. That might be better though. An image could have multiple frames and not be animated if the frames are identical, just like how a video can have an audio track but not be `video_with_sound` if the track is silent.

Something else about autotags I just realized: they run every time the post is saved (unless it's updated with things like `update_column` or `update_attribute` that skip validations). Approving a post saves it, so approving can have the side effect of adding autotags in the approver's name.
