### ISSUE TITLE
Concurrency Issues With Creating New Users

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2970]
A user recently created 3 accounts with the exact same name by creating each account within a second of each other.

- [User #512293](http://danbooru.donmai.us/users/512293)
- [User #512294](http://danbooru.donmai.us/users/512294)
- [User #512295](http://danbooru.donmai.us/users/512295).

1. Does having the same name for multiple accounts break anything?
2. Can the above be avoided somehow, or at least curtailed?
3. Does the creating of any other instance have the same issues, i.e. Posts (same MD5 hash), Wiki Pages, Artists, Aliases, Implications?
4. If so, would that break anything?

Regardless, some kind of check should be run to see if any of the above has occurred previously, and then decide what to do with the duplicate entries...

**Comment by Type-kun** [comment]
>Can the above be avoided somehow, or at least curtailed? 

Unique constraint on DB should do the trick, it's the only reliable way... is what I would usually say, but we actually DO have unique index already:
```CREATE UNIQUE INDEX index_users_on_name ON users USING btree (lower((name)::text));```
I honestly have no idea how is that even possible; postgresql should have not allowed this. Unless there's some sort of invisible unprintable unicode chars involved, I'm baffled.

**Comment by evazion** [comment]
I encountered this in #2808 while trying to import a dump of the users list. The only explanation I can think of is that `db/structure.sql` is lying and the production database doesn't actually have the uniqueness constraint.

I know that `db/structureq.sql` is incorrect for a few other things: certain columns like flag reasons are apparently `varchar(255)` instead of `text`, which creates unexpected limitations. `/tag_aliases.json` has a phantom `reason` field that is not in the schema, which I assume comes from `tag_aliases` actually being a child table of the old `tag_aliases` table from Danbooru 1. Also there are a couple `bank_balances` and `bank_transactions` tables in `structure.sql` that aren't in the app.

**Comment by evazion** [comment]
> Does having the same name for multiple accounts break anything?

Things like `user:<name>` may not look up the right account, which is problematic because a few of these accounts do have uploads. 

> Does the creating of any other instance have the same issues, i.e. Posts (same MD5 hash), Wiki Pages, Artists, Aliases, Implications?

Any column that doesn't have a unique index in `db/structure.sql` can have duplicates. It would be useful to make a list. Many models have `validates_uniqueness_of` validations, and some perform `exists?` checks in certain places, but these things aren't reliable. Checking for uniqueness at the rails level is inherently racy, if you spam actions quickly enough you can bypass these checks.

**Comment by r888888888** [comment]
There is no uniqueness constraint and doing a query I can find 170 dups based on name.

The problem with adding a constraint is figuring out what to do with these first.

**Comment by r888888888** [comment]
I've run a fix to rename some of the dup accounts so a migration should be fine going forward. The duped accounts have been renamed to dup_$oldname_$userid.
