### ISSUE TITLE
More options for artist search page

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#2994]
The artist search page only offers Name and Order fields.  Please also add creator, is_active, is_banned, and empty_only.

**Comment by evazion** [comment]
`is_active` and `is_banned` are supported but they're undocumented. Artist search is strange in that the Name field supports metatags:

* name:\<artist name>
* group:\<group name>
* other:\<other name>
* status:banned
* status:active (excludes deleted *and* banned artists)
* http:// (url search)

To be consistent with this, `creator` and `empty_only` should be metatags, but I think metatags are the wrong approach. They're undocumented, this style is unlike every other search page, and it's broken in several ways (things like `-status:banned` or `name:*blah* status:active` don't work).

So IMO these metatags should be dropped so that artist search works like everything else. I don't know if any API users are using them though. Anyone?

**Comment by evazion** [comment]
BTW creator and empty_only have a couple bugs:

* artist.creator is inconsistent with artist_versions in a lot of cases. See hammer_(sunset_beach): the artist entry says dean exia created it, but according to artist_versions it was freefunctor. I think after the Danbooru 2 migration, artist.creator_id was set to however edited the artist first.

* empty_only returns artists with a post count of zero, but that excludes cases where the tag doesn't exist or has a negative post count.

**Comment by BrokenEagle** [comment]
I use the artist controller frequently including the above sets of metatags. Could there be a crossover period (like with the IQDB controller) before the old way becomes deprecated...?  

Additionally, a notice would be nice on when this changeover occurs, both when the new method becomes available as well as when the old method becomes obsolete.

**Comment by evazion** [comment]
> I use the artist controller frequently including the above sets of metatags. Could there be a crossover period (like with the IQDB controller) before the old way becomes deprecated...?

Well I guess it doesn't hurt to leave them in, so I'll leave it alone. They're just kind of redundant to have now.

We should probably hash out on the forum what the API deprecation policy should be. Even with a deprecation period, I'm not sure how much time people would need or even how to make sure everyone is notified about upcoming changes.
