### ISSUE TITLE
Document how to make this work on Windows.

### ISSUE THREAD

**Issue by AraHaan** [r888888888/danbooru#3044]
I have a laptop with 4 GB of memory that runs Windows 7 Ultimate x64 SP1. Would be nice if there was resources explaining exactly what all I need to get this to work locally. There is also things like mingw and cygwin but they do not have sudo because of the ``administrator`` stuff windows has.

**Comment by AraHaan** [comment]
@r888888888 what is the status on documenting the process for windows users?

**Comment by AraHaan** [comment]
Dam wrong button... I hate iPhones sometimes.

**Comment by Type-kun** [comment]
At the very least, it was possible to run danbooru on Windows box about a year ago or so, since @ToksT used to develop under Windows. 

Installing on Windows is undocumented yet, but you can look at https://github.com/r888888888/danbooru/blob/master/INSTALL.debian to get the general idea. Most of this also applies to setting up dev instance under Linux, which is also underdocumented as I've mentioned in #3041. It also gets much easier to do once you have general understanding of how Rails work; Danbooru repository itself is a practically ready-to-run rails app. 

At the very least, you have to:
* clone the repository to some directory; you'll do everything in that same directory later
* install rbenv with `2.3.1`
* install postgresql, create postgresql user `danbooru` and database `danbooru2`, make sure you can login to db from localhost as `danbooru` without a password, or see below for db config.
* copy `/script/install/danbooru_local_config.rb.templ` and `/script/install/database.yml.templ` to `/config/danbooru_local_config.rb` and `/config/database.yml`
* change `/config/database.yml` so that it includes at least the following directives for every section, in addition to what's the default:
```
  username: danbooru
  encoding: utf8
```
* If you made the database use a password for `danbooru`, include it as well.
* Assuming you don't use nginx frontend (unnecessary for development purposes), pretty much everything under `shared` visible from the outside should be in  `/public/` so that rails server could serve it. That means you must create `/public/assets`, `/public/data`, `/public/data/preview` and `public/data/sample`.
* You'll have to deal with `secret_token` and `session_secret_key` somehow. Under linux it was enough to create `~/.danbooru` for your current user and run `openssl rand -hex 32` to populate both files, but you can't do it like that on windows. Either set environment variables `SECRET_TOKEN` and `SESSION_SECRET_KEY` before running the server, or fix `/config/state_checker.rb`.
* Carefully read the `/config/danbooru_default_config.rb`. You'll need to to override some methods in `danbooru_local_config.rb`. Overriding means creating you own method inside `class CustomConfiguration` with the same signature but different behavior. For example:
```
    def shared_dir_path
      "/home/Type-kun/danbooru/shared"
    end
```
* install memcache, imagemagick (this is a separate quest) and 

That should do for the minimal prerequisites. Now go to the directory where you cloned the repository, run `bundle install` - make sure to look for check logs to see if everything installed properly, I might have missed some dependency since I'm writing this from memory. Then run `bundle exec rake db:create db:migrate`, and if it executes fine, then `bundle exec rails server`. After that you should be able to access your development instance on `http://localhost:3000`.

**Comment by Type-kun** [comment]
Oh, also, since postgresql we use is 9.5, you'll need to build the `test_parser` module somehow. https://github.com/r888888888/danbooru/blob/master/INSTALL.debian#L53-L55 is how it's done under linux provided you have all the necessary packages installed. Under Windows, err, I have no idea to be honest. You'll need mingw/gcc toolchain to compile it at the very least; then see https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules and/or google "postgresql build extensions under windows". It also seems possible to compile using MSVC, but the process for mingw looks much simpler.

**Comment by r888888888** [comment]
Honestly, I would investigate running it in a Linux VM. I'll happily accept PRs to improve Windows support but it's not a subject I'm actively interested in investigating.

**Comment by AraHaan** [comment]
As much as you are recommending an VM. I have to work it in Windows because of the amount of free memory would be drained so much that danbooru would not be able to run on the VM itself because it would do 1 of 2 things.

A: overload the memory causing the entire system to crash.

B: The VM itself would stop working because of lack of hard disc space. I got about 1 gb left on an 250 gb faulty hitachi hdd on my Inspiron 1545 that I have no $$$ to replace nor any $$$ to hack the bios to have it be able to read more than 2 TB of hdd space (includes from USB drives) and over 8 GB of memory (I plan to get it 2 8 gb ddr3, or (if it can support it) 2 16 gb ddr4).

This is exactly why windows support is necessary.

**Comment by Type-kun** [comment]
I actually run it under VM at home. It takes about 850MB ram at peak, I think, but HDD space is more of an issue in your case.

Either way, I'm pretty sure it is possible to run under windows, even if it's not easy. You can try and document your struggles so that we can create a comprehensive guide for others.
