### ISSUE TITLE
related tags for drum_master_(granblue_fantasy) is broken

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#3087]

**Comment by evazion** [comment]
Mentioned [here](https://danbooru.donmai.us/forum_topics/9127?page=186#forum_post_131665), the cause is that related tags doesn't queue update jobs when there are more than 200 pending jobs.

**Comment by BrokenEagle** [comment]
Does that mean with all of the reupload's "delete old files" jobs, that related tags won't update at all for the foreseeable future...?

**Comment by evazion** [comment]
The code is [here](https://github.com/r888888888/danbooru/blob/f93cd11fb5ecc8df49118476f265bee643e6f912/app/models/tag.rb#L683-L699). If a tag has fewer than 1000 posts, and there are more than 200 jobs, then the related tags won't be updated. Presumably this is to prevent backlogs, but the assumption that >200 jobs means a backlog is not true any more.

IMO this limit should just be removed. I've never noticed any backlogs caused by related tags, so this limit doesn't seem necessary.
