### ISSUE TITLE
Searching for artist gives error.

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#3090]
```NoMethodError exception raised

    undefined method `any?' for nil:NilClass
    app/views/artists/_summary.html.erb:20:in `_app_views_artists__summary_html_erb__97776720987715323_69863887287460'
    app/views/posts/partials/index/_excerpt.html.erb:16:in `block in _app_views_posts_partials_index__excerpt_html_erb___659743732848412149_69863913549500'
    app/views/posts/partials/index/_excerpt.html.erb:7:in `tap'
    app/views/posts/partials/index/_excerpt.html.erb:7:in `_app_views_posts_partials_index__excerpt_html_erb___659743732848412149_69863913549500'
    app/views/posts/index.html.erb:38:in `_app_views_posts_index_html_erb__4491769002938517082_69863913072480'
    app/controllers/posts_controller.rb:16:in `index'
```

I get this error when I search for an artist using the latest commit.

**Comment by evazion** [comment]
I suspect you're encountering some problem with memcache. Check that your memcache setup is working, and check your logs for cache-related errors.

**Comment by Iratu** [comment]
It seems to only happen with some artists, I've checked my memcached and it seems to be working just fine.

**Comment by evazion** [comment]
Try taking out the `rescue` clause [here](https://github.com/r888888888/danbooru/blob/f38810bd1cfdbb8f935f4f3f2d5f065822fd0d48/app/logical/cache.rb#L19-L21) and seeing what error you get.

**Comment by evazion** [comment]
Nevermind, I can reproduce it now. This happens when an artist has a post has a source that is `NULL` instead of the empty string.

https://danbooru.donmai.us/posts?tags=tonogai_yoshiki
https://danbooru.donmai.us/posts?tags=puyo
https://danbooru.donmai.us/posts?tags=soejima_shigenori

Posts with `NULL` sources:

https://danbooru.donmai.us/posts/1553250
https://danbooru.donmai.us/posts/1657265
https://danbooru.donmai.us/posts/1652670
