### ISSUE TITLE
Twitter commentary links

### ISSUE THREAD

**Issue by chinatsu-chan** [r888888888/danbooru#3162]
When fetching twitter commentary two changes for links would improve things.

First, links external from Twitter that are shortened with t.co should be replaced with the _actual_ link.

Second, @mentions to other users on Twitter should be replaced by a hyperlink to the Twitter user. For example @google should turn to "@google":[https://twitter.com/google] (may not format correctly on github but works on actual commentary)

Here's the Danbooru bb code for that:
`"@google":[https://twitter.com/google]`

**Comment by evazion** [comment]
It looks like Twitter's API contains an `urls` field mapping http://t.co shortlinks to the actual links. This is good because otherwise we'd have to do HTTP requests to resolve http://t.co links.

Also the link to the tweet itself should be removed. This link is not in the `urls` field; it's in the `media` field instead.

**Comment by evazion** [comment]
Here's a few test cases:

* https://twitter.com/pockypretz11/status/841529345201995776
* https://twitter.com/Kanekiru/status/869216600225918977
* https://twitter.com/noizave/status/875768175136317440
