### ISSUE TITLE
Add two-person approval requirement on post replacements with low similarity matches

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3196]
The idea was brought up in the [Danbooru forums](http://danbooru.donmai.us/forum_topics/14063?page=2#forum_post_132886), and it seems like there is a lot of desire for such a feature amongst approvers, including a couple Admins/Moderators.

One option would be to use Danbooru's IQDB server and if a post replacement does not meet a certain similarity requirement, then it would be sent to a queue where it would wait for the approval from a second approver.

However, to avoid false misses, it would be best to make sure that [Issue #2 on IQDBS](https://github.com/r888888888/iqdbs/issues/2) is resolved since this feature would rely on it.

**Edit:**

Additionally, the message that DanbooruBot leaves behind with post replacements could be updated to include the similarity rating.

**Comment by Type-kun** [comment]
I'm not sure how reliable IQDBS would be for that task. ImageMagick has built-in comparison tool that results in two-color image highlighting the differentiating areas; I've thought about analyzing it instead, and also displaying it for review process, so that the approver, be it the same person or someone else, wouldn't have to search for differences manually. Though this might be a challenging task from a technical standpoint.

**Comment by evazion** [comment]
> ImageMagick has built-in comparison tool that results in two-color image highlighting the differentiating areas; I've thought about analyzing it instead, and also displaying it for review process, so that the approver, be it the same person or someone else, wouldn't have to search for differences manually. Though this might be a challenging task from a technical standpoint.

I'm experimenting with this. The idea is to add an image comparison page that 1) allows one to quickly flip between images to spot differences by eye 2) highlights differences between images with ImageMagick, and 3) possibly includes other info like filesize, resolution, EXIF metadata, which is sometimes useful to know.

The challenges are that:

* We want to be able to compare remote files, files on the local filesystem, and files hosted on S3.

* Finding the right sensitivity level is tricky. If it's too sensitive then jpeg artifacts will create differences all over the place. But if it's lowered enough to ignore jpeg artifacts, it may miss subtle revisions, and detecting subtle revisions is the whole point. This is problematic when it comes to having hard similarity requirements.

**Comment by BrokenEagle** [comment]
Yeah, but can  ImageMagick be used automatically or does it require manual intervention.  If it's the latter, than it would absolutely hinder any large scale replacement efforts like those that went on with the Tumblr replacement fiasco.  Doing that all manually would have completely burned out the approvers.

However, I do know that IQDBS can be used automatically, which is why I suggested it.  Just a suggestion, but why not use IQDBS as the first line of defense, and only use ImageMagick if the similarity score for IQDBS doesn't meet a certain threshold.  From what I've seen, image samples usually meet the 90% similarity threshold on IQDB.org.

**Comment by evazion** [comment]
> If it's the latter, than it would absolutely hinder any large scale replacement efforts like those that went on with the Tumblr replacement fiasco. Doing that all manually would have completely burned out the approvers.

Like I said, that's the trouble. What is desired is something sensitive to minor differences in content but not to differences in jpeg artifacts or resolution. ImageMagick has several [builtin similarity metrics](https://www.imagemagick.org/script/command-line-options.php#metric), ranging from a simple "how many pixels are different?" to more advanced metrics that, frankly, I don't entirely understand. Finding the right algorithm is a nontrivial problem.

IQDB is not a great fit because it scales everything down to 128x128. From IQDB's point of view, revisions such as [this](https://danbooru.donmai.us/posts/2721535) and [this](https://danbooru.donmai.us/posts/2721953) are indistinguishable. IQDB could prevent replacing images that aren't similar at all, but it's not sensitive enough to detect revisions, and I think detecting revisions is the main concern.

**Comment by r888888888** [comment]
Hard problem. I'm against two person approval because it's better to optimize the most common case, which is that a replacement is valid and you don't need secondary approval. If the fear is that an image might be lost, an alternative system of backups could be devised instead.

Finding some sort of satisfactory answer to programmatically determining if two images are similar is a necessary step before implementing any sort of checks on replacement.

**Comment by Type-kun** [comment]
Instead of secondary approval, we could still employ ImageMagick's diff capabilities to let the approver spot the differences quickly and check if they're serious enough to be considered a revision. It would still require downloading the new image, but it can be done when approver starts the replacement process. Once the diffs are calculated, we can offer the approver different views - old/diff/new side-by-side, old/diff overlay and new by side, old/new overlay changing back and forth every second, etc. This way we trust the approver, but let them spot the diffs instantly instead of straining their eyes on every image.

Additionally, said diffs could be stored, and similar views can be offered for anyone willing to check and revert.

**Comment by hakusaro** [comment]
I voiced my thoughts on this in [this thread](http://danbooru.donmai.us/forum_posts/137857), the summary being that a clientside diff would be good. The advantage is that, assuming an uploader is trusted, a clientside diff would be easier to implement, cause no additional server load, and could potentially be dropped in faster. It's an extra dependency for sure, but a few lines of JS and a new partial could go a long way.
