### ISSUE TITLE
Viewing certain image returns blank page with "undefined method `data' for nil:NilClass"

### ISSUE THREAD

**Issue by Cerzel** [r888888888/danbooru#3220]
As the topic says. I'm trying to view http://danbooru.donmai.us/posts/2750277 and it just returns the page as so: https://vgy.me/rSwRzN.png
I'm using Opera. I've tried refreshing, force refreshing, and viewing it in Firefox, all to the same results. It does work in Internet Explorer (but I don't have flash for that so it won't play the video). I've turned ublock off and that didn't help, and I don't have any scripts for Danbooru or NoScript, or anything else that I can imagine is interfering with it. I haven't had problems with any other images.

**Comment by BrokenEagle** [comment]
Chrome 59 and Firefox 54 are working for me with the above-mentioned post.

**Comment by evazion** [comment]
Mentioned here: https://danbooru.donmai.us/forum_topics/9127?page=189#forum_post_132523

Viewing the original ugoira is broken because the frame data is missing. It works if you're viewing the webm because you have samples on.

Someone just needs to replace the post with a dummy file then replace it back with the ugoira to force the frame data to be redownloaded.

**Comment by Type-kun** [comment]
Hm, I wonder how this kind of thing happens. If we fail to record ugoira frame data, upload should fail as a whole, not leave partially uploaded broken posts.

**Comment by evazion** [comment]
Someone replaced a non-ugoira with a ugoira, and post replacements at that time didn't save the new frame data in that case. That has since been fixed.

**Comment by evazion** [comment]
Fixed by Mikaeri replacing the file for this post.
