### ISSUE TITLE
Give moderators ability to see who has voted up/down on a post

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3251]
A user contacted me in regards to their belief that another user was targeting them due to a recent preponderance of downvoting on that user's uploads.  I was about to tell that user that a moderator could look into that, but I discovered that the only tool they currently have is the upvote/downvote metatags.  That's fine if there is a list of potential culprits, however if that turns up nothing, than there is currently limited recourse.  That's why moderators should be able to click something, maybe something under **History**, that lists all of the users that have voted on a post and what their IPs are.

To limit the potential abuse a moderator might take upon another user that upvotes/downvotes their own uploads, maybe limit that function to everyone but themself, i.e. they can see upvotes/downvotes on all uploads but their own.

**Comment by r888888888** [comment]
a targeted report would be more useful because in the scenario you describe the mod would have to open up a bunch of posts and try to figure out if there are any patterns.

some thoughts:

* given `x` is the set of all posts a suspected vandal downvoted, and `y` is the set of all posts uploaded by a specific user, what is the jaccard index? 
  * not sure if this is the best metric. a vandal who downvotes a lot of things but also happens to downvote `y` a lot would not rank high in this. this is more for finding targeted downvoting.
  * alternative: aggregate all the down votes by count. this data could still be misleading though. the number may appear high but if the uploader has a crapload of uploads this value would need to be normalized somehow.
* for a specific user, find all the downvotes on their uploads and run the above analysis.

**Comment by BrokenEagle** [comment]
OOZ662 recently made a comment on Danbooru related to this issue ([forum #137236](http://danbooru.donmai.us/forum_posts/137236)).

Basically, comment voting should also be considered when it comes to a user maliciously downvoting another user's comment.s

**Comment by r888888888** [comment]
There's a link to generate this report now.
