### ISSUE TITLE
Batch bookmarklet doesn't work on certain Twitter URLs

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3254]
[Brought up by Sacriven on Danbooru](http://danbooru.donmai.us/forum_topics/9127?page=196#forum_post_134420).

Below is an example Twitter url where the batch bookmarklet only pulls up the first image.

https://twitter.com/aoimanabu/status/892370963630743552

**Comment by evazion** [comment]
So apparently that is a so-called extended tweet - a tweet longer than 140 characters. You can tell because the response includes `trucated: true`. It looks like these tweets have to be handled differently, by passing `tweet_mode=extended` and taking the urls from the `extended_entities` field instead of the `entities` field.

https://dev.twitter.com/overview/api/upcoming-changes-to-tweets
https://twittercommunity.com/t/retrieve-full-tweet-when-truncated-non-retweet/75542/9
