### ISSUE TITLE
Twitter usernames should be case insensitive

### ISSUE THREAD

**Issue by akunohomu** [r888888888/danbooru#3259]
https://danbooru.donmai.us/artists/51509

Lists Twitter URL as `https://twitter.com/mataro_777`; artist's username is actually `https://twitter.com/MATARO_777`; doing a URL search with that `https://danbooru.donmai.us/artists.json?search[name]=https://twitter.com/MATARO_777` gives no results because danbooru only does case-sensitive search. Incorrectly entered Twitter URLs can therefore make it hard to match up a Twitter post to a danbooru artist tag.

**Comment by BrokenEagle** [comment]
This should also be done for all case-insensitive sites.

1. Any site where the artist ID is encoded into the URL automatically could be included since all domain names are case-insensitive.

- Tumblr
- Deviantart
- Artstation
- FC2
- Sakura.ne.jp
- Biglobe

2. Any site where the path must be all lower case to work.

- Pixiv
- Nicovideo
- Tinami
- Nijie
- Weibo
- Youtube (username case insensitive)

3. Any site where the path and/or the artist ID and is case insensitive

- Pawoo
- Twitter
- Facebook
- BCY
- Plurk

For any of the above, the search term and the stored site could both be converted to lowercase for comparison.

Also, in contrast to the above, the below must keep case sensitivity.

4. Sites where case matters

- Drawr
- Stickam

One thing that might help with the above would be to finally store the usernames and ID's per site as discussed in #2696.  Case-sensitivity of the username would play a part in any such scheme.

**Comment by evazion** [comment]
Was fixed in 461ddbf017 for Twitter, the issue of case sensitivity in general remains unsolved.
