### ISSUE TITLE
Remove leading whitespace on pool names

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3263]
I first noticed this issue on Danbooru, before testing it on Testbooru.

http://testbooru.donmai.us/pools/6.json

The above pool was created with 5 leading and trailing spaces in the pool name.  As can be seen, it removes all but one of the leading spaces.

On a side note, the body was also created with 5 leading and trailing spaces, which are both still there.  Though I don't know exactly what the proper behavior should be here...? 

http://testbooru.donmai.us/pools/7.json

I created the above as a test case, with 65535 spaces before and after the body, although I could have gone much much higher.  It appears as if nothing is wrong from the HTML view, however viewing the page source  or the JSON/XML will show all of the whitespace.  I imagine that the above could potentially be maliciously used...?  Of course, the same also probably holds true for wiki pages, forum posts, comments, etc.

**Comment by evazion** [comment]
Pool names should probably have the same restrictions that tag names do ([1]), except for not allowing Japanese. No leading/trailing underscores, no consecutive underscores, no names consisting entirely of underscores. Maybe no names consisting entirely of digits either, since `pool:1234` is ambiguous (it could mean `pool #1234` or the pool named `1234`).

And as for leading/trailing whitespace, really whitespace ought to be trimmed on save from nearly every text field across the site. It doesn't hurt really anything, but it's not desirable either.

[1]: https://github.com/r888888888/danbooru/blob/87b0dc3ae3eb01cf324dfe3b7e35953eacf187a0/app/logical/tag_name_validator.rb
