### ISSUE TITLE
Connection throwing Http 403

### ISSUE THREAD

**Issue by NNowakowski** [r888888888/danbooru#3273]
Good morning,
I'm developing a Discord bot which is pulling random pictures from Danbooru and displays them in chat.
It is developed in Java and used to work fine.
However in the last weeks it stopped working.
Everytime it's trying to get the response from the Danbooru site it receives a Http 403 response:
```java
java.io.IOException: Server returned HTTP response code: 403 for URL: http://danbooru.donmai.us/posts.xml?tags=chartags:1&random=true
```
What could be the cause of this?
If I'm trying to open the page in my browser it works fine.
Trying to get the content with cUrl on the server seems to work correctly aswell.
Am I missing something? Did Danbooru change anything in the last weeks?

**Comment by Type-kun** [comment]
Check the message returned by the server along with the code? It's quite hard to diagnose otherwise, being a generic "forbidden" code.
Other that that, try setting user agent and referer to something viable, if you didn't already. I think danbooru started using cloudflare recently, so that might be the cause.

**Comment by NNowakowski** [comment]
@Type-kun Oh my ... Thanks a ton!
I was expecting that it would pick up the User-Agent of the server by default, which would have worked since cUrl on the server worked aswell.
I now set it manually and ... everything works again!
To think that it was only this small detail missing.
Thank you!
