### ISSUE TITLE
Image replacements not working on corrupted images

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3290]
I replaced all of the corrupted pixiv posts in http://danbooru.donmai.us/forum_posts/135533, but the full sizes are still corrupted 9 hours later, even with hard refreshes...

**Comment by RaisingK** [comment]
Nope, they're still broken... but not necessarily the same way?

http://danbooru.donmai.us/data/4a4da0827394992a7fd9f68bc7de08bc.jpg can't be displayed at all, while https://s3.amazonaws.com/danbooru/4a4da0827394992a7fd9f68bc7de08bc.jpg shows a little at the top.  Same deal with https://s3.amazonaws.com/danbooru/78dc5cdafadc77a009dbfee7ccd78257.jpg and http://danbooru.donmai.us/data/78dc5cdafadc77a009dbfee7ccd78257.jpg.

post #9070's full size URL has "/cached/" (http://danbooru.donmai.us/cached/data/baccd4849b94edee5e642a6c978a48a6.jpg), and it and the amazonaws have the same corruption... but http://danbooru.donmai.us/data/baccd4849b94edee5e642a6c978a48a6.jpg isn't corrupted.

**Comment by r888888888** [comment]
I think the problem is in [upload.rb:215](https://github.com/r888888888/danbooru/blob/master/app/models/upload.rb#L215). If you're trying to replace a file with itself (i.e., the md5 doesn't change) then it won't overwrite it. I'm fairly sure we don't need this check? MD5 dupes will be detected beforehand.

**Comment by RaisingK** [comment]
I tried another round of replacements.  For some reason, most worked but not all--http://danbooru.donmai.us/posts/9070 and http://danbooru.donmai.us/posts/2216853 are still corrupt.

**Comment by r888888888** [comment]
I processed these manually and am not noticing any obvious errors.

**Comment by RaisingK** [comment]
Are those two posts still corrupt for you, too?

**Comment by r888888888** [comment]
9070 wasn't backed up to S3, I guess because the MD5 didn't change. I can add some logic to force a backup for replacements. It will take some time for the Nginx proxy cache to expire, however.

2216853 also looks correct on donmai.us and the S3 version was corrupt, so I think that's the same problem.
