### ISSUE TITLE
Add fifth category tag type for metatags

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3292]
Brought up in the [Danbooru Forum](http://danbooru.donmai.us/forum_topics/14372).  Related to #2358, but a lot more straightforward.

Basically, there was a strong desire expressed for a fifth category of tags which would encompass all metatags (but not those used with a semicolon ":").  See [Tag Group:Metatags](http://danbooru.donmai.us/wiki_pages/87398) for a mostly complete list on what tags would qualify.

The advantage of grouping tags like this is that it moves those tags out of the sea of blue (all general tags) from those that don't care about them, while highlighting them to those that do want to see them.

The thought was to have this category be placed beneath the **General** category in the tag list, which would be right above the **Information** section, thus grouping all of the different meta-information about an image in the same general vicinity.

**Comment by Type-kun** [comment]
I see no harm in that. It also will be useful for things like our missing tags report, since it needs the list of tags to be excluded from processing, and those tags are generally the same that will be included in the new category.

Also, if the new category is created, changing tags to and from it should be restricted to builder+ regardless of tag count.

**Comment by BrokenEagle** [comment]
The initial suggestion for the 5th tag category was "Technical", but that was confusing as well.  The term that generally became accepted was "**Meta**", which isn't quite "metatag" and so should hopefully avoid some of that confusion.
