### ISSUE TITLE
Commentary - Markup tags don't work inside nested quotes (for hyperlink text)

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#3295]
Commentary fetcher can sometimes fetch text inside a hyperlink, e.g. 
"[b]Text text[/b]":(http hyperlink)
This causes the markup tags to show as regular text.

**Comment by r888888888** [comment]
But there's a pretty simple workaround for this, isn't there? Just move the bold tags outside.

**Comment by BrokenEagle** [comment]
Yeah... specifically using you're example, you should use a bracketed textile link.  Otherwise the textile link parser will pick the trailing [/b] as part of the URL.

`[b]"Text text":[http hyperlink][/b]`

There really isn't advantage that I can see to parsing the text portion of a textile link.  The only possible usecase would be if you wanted to apply a style markup to only a portion of the text, however given the added complexity this would add to the parser, I'm not sure it'd be worth it for such a limited application.

**Comment by Kikimaru** [comment]
@r888888888 @BrokenEagle  
I was hoping it might be possible for you to change the detection in your code.  
Having to rewrite the commentary isn't fun when there might be 5-6 links in bold text.

**Comment by r888888888** [comment]
If it's just commentaries that have this problem maybe we can write a bot or script to fix them automatically?

**Comment by evazion** [comment]
This is the same issue as https://github.com/r888888888/dtext_rb/issues/25. The bug is that DText recognizes inline markup in basic links but not in bracketed links. `"[b]foo[/b]":http://example.com` works but `"[b]foo[/b]":[http://example.com]` doesn't.

The problem with just moving the bold tags outside is that it wouldn't work for things like `"foo [b]bar[/b] baz":http://example.com`.

**Comment by r888888888** [comment]
I've implemented the inline parsing for bracketed textile links in the dtext gem.
