### ISSUE TITLE
"No site key specified." on Testbooru

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3315]
Brought up by nonamethanks on Discord.

Basically, users are no longer able to create accounts on Testbooru for testing...

http://testbooru.donmai.us/users/new

**Comment by r888888888** [comment]
Fixed

**Comment by Iratu** [comment]
I'm getting this error as well on the booru I host, may I ask what the fix for this was?

**Comment by evazion** [comment]
At the moment you have to signup for Recaptcha and set `RECAPTCHA_SITE_KEY="..."` and `RECAPTCHA_SECRET_KEY="..."` in your `.env.local` file. See https://developers.google.com/recaptcha/intro and https://github.com/ambethia/recaptcha#rails-installation.

#3411 will fix this so that Recaptcha is optional.
