### ISSUE TITLE
Disallow creation or renaming of artist names with Unicode characters

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3328]
They aren't allowed as tags anyways, but as of now can still be used as the artist name.

Recent example:

http://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=158313

**Comment by evazion** [comment]
Really artist names should follow the same rules as tag names, meaning other things like asterisks, leading/trailing underscores, and consecutive underscores should also be disallowed.

The question is what to do with existing invalid artist entries. There are quite old deleted artists that have Japanese names, see [here](https://danbooru.donmai.us/artists?page=909&search%5Bis_active%5D=false&search%5Border%5D=created_at). IMO they should be hard deleted, otherwise these corner cases will still need to be dealt with.

**Comment by r888888888** [comment]
fixed
