### ISSUE TITLE
Forum threads should be responsive on mobile

### ISSUE THREAD

**Issue by hakusaro** [r888888888/danbooru#3354]
Title says it all. Currently, the layout is compressed such that half of the screen is occupied by the post author and time, while the other half has the thread content. These two boxes should be stacked.

Screencap:

![img_3374](https://user-images.githubusercontent.com/532647/32508432-886751ce-c3a7-11e7-9b75-b79420d00839.PNG)

**Comment by BrokenEagle** [comment]
I developed some custom CSS that does exactly this ([topic #1234](http://danbooru.donmai.us/forum_topics/14077)).

![image](https://user-images.githubusercontent.com/21149935/32560783-5bee0ce2-c45f-11e7-8289-3f423ec72eec.png)

In addition to stacking them, it also throws a box with rounded edges around the forum post to help better segregate forum posts.

As an addition to the above, the following is what most of the tables look like with that custom CSS.

![image](https://user-images.githubusercontent.com/21149935/32560909-aa55acdc-c45f-11e7-88ac-1456474c239f.png)

So instead of having horizontal lines on tables for rows, it stacks each row's cells on top of themselves.
