### ISSUE TITLE
Autocomplete issues with tag "/\/\/\" 

### ISSUE THREAD

**Issue by Kikimaru** [r888888888/danbooru#3356]
When using the autocomplete, the tag `/\/\/\` will stop showing whenever user inputs Backslash  `\`
i.e. autocomplete doesn't show for
`/\ , /\/\ , /\/\/\`
Tested in Firefox & Chrome.

**Comment by BrokenEagle** [comment]
This isn't an error.  Since #3104, the backslash needs to be double-escaped, i.e. ``\\``.  So for your above example, you would need to type out /\\/\\/\\.  This is because the backslash is used to show a literal star "*".  Check out the beginning of [Help:Cheatsheet](http://danbooru.donmai.us/wiki_pages/43049) for details on this.
