### ISSUE TITLE
Change order of categories in tag lists

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3364]
Currently tags are listed in the order of copyrights, characters, artists, general tags, then meta tags. But when a post has a lot of characters, you have to scroll down to find the artist tag. Likewise, when a post has many general tags, you may have to scroll down several screens to see the meta tags. This somewhat defeats the purpose of making things like `*_request` tags more visible.

I argue that tag lists should be listed in order of artists, copyrights, characters, meta tags, then general tags. This would place the sections roughly in order from smallest to largest.

**Comment by BrokenEagle** [comment]
Would like to see this hashed out on the forum if possible since this effects all users.  I created [topic #14679](http://danbooru.donmai.us/forum_topics/14679) to that effect.  I know the going thought with **Meta** tags at least is that they would be next to the **Information** section since both sections have a high correlation.

**Comment by Type-kun** [comment]
I'd prefer metatags to stay at the bottom.

**Comment by evazion** [comment]
Fixed in 975d42c9ac2aae38d6c90046c318526bfeb17896.
