### ISSUE TITLE
"Fetch source data" on /uploads/new doesn't fetch artist tag

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3368]
Example: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=65899177
On https://danbooru.donmai.us/uploads/new pressing "Fetch source data":
![](https://i.imgur.com/aSnpYu0.png)
The tags are all fetched correctly
![](https://i.imgur.com/XAiCH46.png)
But the artist tag is not displayed.
Curiosly enough, on page reload the artist tag (and the other tags) shows up correctly without need to fetch the data again.

**Comment by BrokenEagle** [comment]
You need to manually click the **Artist** button next to the **Source** field.  Since Firefox doesn't clear the field data upon page refresh, the Javascript detects the **Source** field filled and so auto-clicks the **Artist** button.

**Comment by evazion** [comment]
The fix should be:

* Make the call to `/source.json` return the artist entry along with the rest of the source data, so that we don't have to make a separate call to `/artists/finder.json`.
* Automatically trigger `Fetch source data` whenever the source field changes (so it triggers when you paste in an URL).
* Automatically trigger `Find similar` as well.

**Comment by evazion** [comment]
I'll leave the idea of triggering `Find similar` automatically when you paste an URL into the source field to future work, since it's a bit out of scope here.
