### ISSUE TITLE
Adjust the Z-index of HTML elements as needed

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3383]
Reported on the [Danbooru forum](http://danbooru.donmai.us/forum_posts/139395):

> fossilnix said:
> 
> The search field shows on top of the popped-out tag box ([Screenshot](https://i.imgur.com/hFmJPyw.png))

![image](https://user-images.githubusercontent.com/21149935/32975644-251551c4-cbbe-11e7-8c56-ce3c2e914835.png)

The dialog boxes have a Z-index of 999, so at least the above-reported issue could be fixed by changing the z-index of the pop-out search box from 1000 to 998.

I left the issue generalized as there could potentially be other conflicts like the above that need to be looked for and adjusted.

**Comment by evazion** [comment]
I lowered the `z-index` to 1. I think it just needs to be high enough to render above post thumbnails, and 1 is enough for that.

To explain what's going on here: `z-index` is necessary because thumbnails (`artist.post-preview` elements) have `position: relative`. Apparently positioned elements render above non-positioned elements unless you use a z-index to override it (see [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_without_z-index)). The reason that `artist.post-preview` has `position: relative` to begin with is because of #2223.
