### ISSUE TITLE
Safebooru: Two tag searches fail for members

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3387]
On Safebooru, two tag searches show an empty paginator for member-level users. See [hatsune_miku twintails](https://safebooru.donmai.us/posts?tags=hatsune_miku+twintails), for example.

The bug is the way that `rating:s` is added to the tag string in `Post.fast_count`. This may put the user over their tag limit. `Post.tag_match` raises a `SearchError`, `fast_count` catches the error and returns zero, which results in an empty paginator.

The same bug happens on Danbooru if a member-level user enables the `Deleted post filter` account setting. Adding `-status:deleted` to a two tag search puts them over their tag limit.

The quick fix would be to say `CurrentUser.without_safe_mode { Post.tag_match(...) }` inside `fast_count`. But I think it'd be better to split `Post.tag_match` into two methods, one method for contexts where current user settings apply, and one method for contexts where they don't.

EDIT: I was wrong, `CurrentUser.without_safe_mode { Post.tag_match(...) }` wouldn't work because we'd still hit the tag limit. The easiest fix would be to make `rating:s` and `-status:deleted` not count against the tag limit.

**Comment by BrokenEagle** [comment]
It was reported on [topic #14710](http://danbooru.donmai.us/forum_topics/14710) that this issue also exists when using the pool metatag, however in this case it seems like it's only 1 tag that sets this but off instead of 2.  However, in this case it's weird as it seems to only be an issue on Danbooru and not Safebooru.  Also, when I add the `safe_mode=true` URL parameter on either Danbooru or any of its subdomains, the issue goes away as is the case with Safebooru.  No idea what's going on with this one here...?

**Comment by evazion** [comment]
Opened #3390 for that bug. It's similar in that they're both a result of `Post.fast_count` returning 0 in certain cases, but for different reasons.
