### ISSUE TITLE
Add a way of marking artist urls as outdated

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#3388]
Sometimes a URL no longer points to a valid resource but it's still useful to keep around for record keeping.

**Comment by BrokenEagle** [comment]
I've thought up a schema that should forestall the need to overall the user interface.

- To mark a URL as outdated, prepend it with the minus sign **'-'**
This would be through the URL string that is sent through the POST or PUT request when creating or updating an artist.  Since having a '-' in front of the **http/https** schema is invalid, it can serve as a marker that the URL is outdated
- The URLs would be still stored in the ``artist_urls`` without any '-' prepending it as normal
Instead, the presence or absence of the '-' would be a signal for how to set a boolean that would need to be added to the ``artist_urls`` model, e..g. ``is_outdated``.
- When URLs are rendered in the HTML edit view, they will prepend all URLs that are outdated with a '-'
- Change how URLs are rendered in the HTML show view when ''is_outdated'' is true
Show just the link text without creating an actual link.  Another option on top of that or besides that could be to have a strikethrough going through the link

Example(s):
1. No link: ``http://www.example.com``
2. Strikethrough: ~~http://www.example.com~~
3. Both: ~~``http://www.example.com``~~

Just for reference, I've been doing (3) a lot when marking links as bad in the wiki.

Since **artist_versions** already uses some different colorizations and strikethroughs, a different visualization scheme would need to be employed to show when the ``is_outdated`` attribute is flipped for a URL, but that's something that can be come up with later if needed.

**Comment by r888888888** [comment]
I like it. My only other thought is, being able to automatically identify outdated URLs would be useful. For Pixiv or Twitter it should be possible to add a callback on artist save to validate all the urls.
