### ISSUE TITLE
Certain daily maintenance tasks not running

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3413]
Certain daily maintenance tasks don't seem to be running:

* Post disapprovals aren't being pruned: http://danbooru.donmai.us/posts?tags=status%3Adeleted+age:>40d

* Negative tag counts aren't being fixed: https://danbooru.donmai.us/tags?limit=500&page=1388&search[hide_empty]=no&search[order]=count.

* Cached post counts on tag aliases aren't being updated. Some aliases, `saber_extra -> nero_claudius_(fate)` for example, don't show up during autocomplete because their cached post count is zero. See http://danbooru.donmai.us/tag_aliases/15127.json.

* The [/cache/tags.json](http://danbooru.donmai.us/cache/tags.json) dump appears out of date. The most recent tag is from 2017-10-09.

I think generating `/cache/tags.json` may be the culprit. If there's some exception writing that file then the remaining tasks may not run.

**Comment by BrokenEagle** [comment]
Might it be useful to write a mod action for the daily maintenance task for cases like this?  The list of functions in it could be wrapped in an exception handler that writes a mod action upon an error.  With it more visible like this, it would allow users to more easily catch when there is a disruption in the process instead of having to rely on secondary or tertiary effects.

**Comment by evazion** [comment]
Any kind of logging would help. Another idea would be to run tasks as delayed jobs, that way failures would show up in the delayed jobs index. It would also mean that a failure in one task wouldn't prevent others from running.

**Comment by r888888888** [comment]
Running it manually seems to have worked, including all the steps before it up to the upload prune. Maybe there was a bug that was fixed in the recent deployment.
