### ISSUE TITLE
Deleting a post doesn't clear parent's "parent" status

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3419]
If I delete an only child post, its parent keeps its "parent" border until I remove/readd the parent/child link.

**Comment by evazion** [comment]
https://github.com/r888888888/danbooru/blob/feb3ec07500586e0e9d3dc5594414f3b59766349/app/models/post.rb#L1369-L1388

This happens when the `Move favorites to parent?` option is used.

The cause is that `give_favorites_to_parent` also moves the votes, and moving the votes has the side effect of reloading the post (to get the new score). But reloading the post wipes out the `is_deleted_changed?` flag, which is used by `update_parent_on_save`.

**Comment by evazion** [comment]
Fixed in acd49be. A better fix would be to not call `reload` inside `Post#vote!` / `Post#unvote!`, but that's difficult to avoid without duplicating code.
