### ISSUE TITLE
Failure to find artist for certain Twitter URLs

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3422]
URL: https://twitter.com/gulp5959/status/929679299002621955

Artist entry: https://danbooru.donmai.us/artists.json?name=gulp5959
Artist URL: https://twitter.com/Gulp5959
Normalized artist URL: http://twitter.com/Gulp5959/

Using the bookmarklet on the tweet above doesn't find the artist. It doesn't match because the normalized URL in the artist entry isn't lowercase.

This happened because inside `ArtistUrl#normalize`, we do `Sources::Site.new("https://twitter.com/Gulp5959").normalize_for_artist_finder!` to normalize the URL, which *would* lowercase it, if it worked. Except it doesn't, because the Twitter source strategy doesn't recognize URLs that don't contain a status ID.

**Comment by nonamethanks** [comment]
@evazion it seems this wasn't fully fixed. It is only matching correctly for artists whose link lists have been refreshed - ones with mixed case twitter links still won't match until their links are resaved.

Example: any of this user's tweets https://twitter.com/GiriGiriii/media don't match his existing artist entry (https://danbooru.donmai.us/artists/160859)

Even though this artist was created recently (in the last ~12 hours), it still won't match it. I'm not editing it because otherwise it'd stop being a useful example as the link refreshing can only be reproduced once per artist, so I'll leave that to you so you can observe the bug.

**Comment by nonamethanks** [comment]
Ah sorry, pinging @r888888888 too because I just noticed it was him who committed the fix for this.

**Comment by r888888888** [comment]
I've reverted and deployed this for now since it was breaking the artist finder.
