### ISSUE TITLE
Broken dtext in ban reason

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3423]
The dtext links used in the feedback for http://danbooru.donmai.us/users/355153 are broken in the ban message displayed on their profile.

**Comment by BrokenEagle** [comment]
Am I reading them wrong, or did you use the textile links backwards?  The text goes in quotations, and the link goes after the semicolon.

**Comment by RaisingK** [comment]
ShadowbladeEdge's ban, not mine.  I was just comparing the message on the feedback page with the message on the profile page.  You're right, the text should be in quotes... and that's how it is in the feedback... but swapped in the ban message?

**Comment by BrokenEagle** [comment]
Yeah, @evazion noticed that the JSON had some extra newlines where there shouldn't be...

**Comment by evazion** [comment]
http://danbooru.donmai.us/bans/4575.json
http://danbooru.donmai.us/user_feedbacks/10021.json

User error. The messages differe because ShadowBlade got the DText backwards in the ban message, then updated the user feedback afterwards to fix it.

I'd say the bug is that user feedbacks give no indication of when they've been edited.

**Comment by evazion** [comment]
Added a "Updated N minutes ago" notice on edited feedbacks. We don't track who edited a feedback, so that can't be shown. Also, I left out the 5 minute grace period that edited comments/forum posts normally have, so the edit notice is always shown.
