### ISSUE TITLE
Accept the search[id] param in all controllers

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3430]
Currently only a subset of controllers support the `search[id]` URL param. This should be extended to all controllers.

The syntax should also be extended to work the same way that the `id:<N>` metatag does. That is, in addition to `search[id]=1,2,3`, `search[id]=>42`, `search[id]=<42`, and `search[id]=1..10` should also be supported.

**Comment by BrokenEagle** [comment]
+1 to the above feature.  It facilitates being able to process and filter records en masse with JSON, and then displaying the results as HTML rather than having to use multiple show or index pages.

Additionally, the results of a filtering action could be stored for later processing as a set of IDs.  Then those records could be retrieved en masse at a later time with considerably fewer network requests.

Those are just a few use cases, but there's probably more.
