### ISSUE TITLE
Make Enter key accept current tag during autocomplete

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3532]
During autocomplete, if you partially type a tag, let's say `fate`, then press down to select `fate_(series)`, then press `Enter`, it will submit the search `fate`. Instead `Enter` should complete the tag, the same way the `Tab` key does.

This is how autocomplete works on other boorus. Indeed, I've heard some people say they didn't know you could press `Tab` to autocomplete a tag. I believe this is the reason behind many frequent missed searches.

Note that this is the default behavior of the autocomplete library already, but for some reason it was patched out in dbe4a7ebf.

**Comment by r888888888** [comment]
Maybe I just need to get used to this scheme but this feels like a usability downgrade to me, especially when editing tags. I think part of the problem is autocomplete is sorted by post count versus closest string match, so you can get into situations where maybe I want to search X but autocomplete has selected XY. I have to press Esc to abort the autocomplete and then enter has the expected behavior. Maybe the results returned by autocomplete need to be sorted more intelligently.
