### ISSUE TITLE
Yukinoshita.donmai.us is down

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3535]
The read replica (yukinoshita.donmai.us) is down:

> could not connect to server: Connection refused Is the server running on host "yukinoshita.donmai.us" (104.237.154.176) and accepting TCP/IP connections on port 5433?

This is causing failures on any search or pageload that uses `Post.fast_count`.

**Comment by r888888888** [comment]
So a quick postmortem about what happened:

I enabled streaming replication after the upgrade to Postgres 9.6. Unfortunately this doesn't work too well with log archiving since it won't process the WALs unless it's in rebuild mode. This meant the logs weren't being pruned and it quickly filled up the disk on yukinoshita. For now I've disabled the log archiving since, worst case, I can just bring up the replica from a backup.
