### ISSUE TITLE
Add expiration to alias/implication/BUR requests

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3580]
Discussed on Discord.  Currently, there are 218 pending bulk update requests, 72 pending tag alias requests, and 65 pending tag implication requests.

https://danbooru.donmai.us/bulk_update_requests?page=11
https://danbooru.donmai.us/tag_aliases?page=4
https://danbooru.donmai.us/tag_implications?page=4

The current setup isn't working as demonstrated by the huge backlog, and rather than overwhelm the Admins with an apparently monumental task, it would instead be better to have an expiration on these requests (like 2 months).  If it's not approved in that time period, then it will automatically be rejected.

Also, I don't know how much communication there is in regards to these requests on the forums amongst the Admins, but it might also be helpful to have a function that would allow an admin to signal their unwillingness to either approve or disprove a request.  In that manner, it would be similar to how the current moderation queue works for posts.  I'm not sure how visible such a metric should be, but maybe for Admins it would list the name of the Admin(s) that showed disinterest, and for everyone else it would show the number of Admins.

In addition to the above, maybe have a function that Dmails all Admins that haven't yet touched a request when it falls within a certain number of days of expiration (like 3 days).  I know that some Admins may not want to receive such DMails during certain time periods when they are less active due to IRL, so maybe also give them an ability to opt out.  If that also gets added, then it might be useful to display such information somewhere for all Admins to see, indicating the number of active and inactive Admins, maybe in the Admin's console.

- [ ] Add expiration function to all request types
- [ ] Reject all requests that fall outside the designated time frame
- [ ] Add disinterest mechanic to all request types
- [ ] Dmail all Admins that have yet to mark disinterest before expiration

**Comment by Type-kun** [comment]
Hmm. Well, one thing I can say about it is that I often don't approve the requests because I want more input from other admins or powerusers. I clearly say that in the topic, but of course it gets buried by other approved/rejected requests, and no input is given. It's rather hard to say how to mend that without changing the system drastically.

**Comment by evazion** [comment]
Yeah, I suspect things go unapproved more often out of uncertainty than disinterest. I'd suggest a couple things:

* Have DanbooruBot bump the thread a week or so before it expires. I think it'd be useful to notify everybody involved, not just the admins. This would remind everyone to make their final arguments and give a +1 if they don't want it rejected. Otherwise I think we'd get a lot of "hey, my request was suddenly rejected even though nobody was against it, please go back and approve it".

* Add a way to +1 forum posts (like the way you can on Github). I think it'd help if it were easier to see how many people supported/opposed a given idea. Often there are requests I agree with but don't say anything because I don't want to spam +1 replies on everything.

* Maybe some way to mark threads as resolved/unresolved (similar to open/closed issues). Approved or rejected requests would be marked as resolved and wouldn't show up in the forum listing by default. This way they wouldn't bury other threads.

**Comment by r888888888** [comment]
I like the idea of pruning old requests.

I like the idea of bumping the thread (perhaps at a random interval so they don't all bump at once) by the system user to notify pending actions.

Just adding :+1: support probably isn't enough. Tag changes can radically affect usability, and so many users will probably want to express disapproval without an explicit explanation of why. 

I generally think the squeaky wheel gets the grease. If a change is badly needed, more people will chime in on the necessity. But maybe the people with relevant knowledge aren't necessarily reading the forum when the change is proposed. 

So this is kind of a wild idea, but what about creating some sort of notification system so that when a change for tag X is proposed, whenever someone searches for X they get a notice that a change is under discussion. They can click through, read the arguments, and vote on whether they support it or not. 

Is trying to get more people involved a bad idea? They might not understand the system or norms. And maybe realistically there isn't much they can add that can't already be researched by more objective users.

**Comment by BrokenEagle** [comment]
> So this is kind of a wild idea, but what about creating some sort of notification system so that when a change for tag X is proposed, whenever someone searches for X they get a notice that a change is under discussion.

This wouldn't work as well as one might think.  I can't speak for anyone else, but I generally only search using no more than several tags myself.  Perhaps instead it should trigger off both tag searches AND tag edits.  That way, those that are adding or subtracting that tag a lot will also get pinged so that they can contribute.  Maybe to ease the load on the DB limit it to only the previous X months of tagging.

> Is trying to get more people involved a bad idea? They might not understand the system or norms. And maybe realistically there isn't much they can add that can't already be researched by more objective users.

I think that if the +1 system gets implemented, you'll find that a lot more users are using that then responding to the thread themselves, so there's probably not too much to worry about.  If we find that it does become a problem, we can always scale it back.  It could be very effective though, but we won't know unless we try.

**Comment by BrokenEagle** [comment]
This has already been fixed by forum voting and retiring old aliases/implications.
