### ISSUE TITLE
Minor issues with commentaries of tumblr ask posts

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3586]
Some quick examples for easier explanation:

https://danbooru.donmai.us/posts/3067626
Commentary fetched:
![](https://i.imgur.com/kUSH8rp.png)

https://danbooru.donmai.us/posts/3067625
Commentary fetched:
![](https://i.imgur.com/F2MyKrE.png)

There are two problems here that should be easy to fix:
* the first and most evident is that the placeholder "image" for the actual image inside the response body is not stripped
* the second is that the title for these posts, which is the question of the ask post, should be preceeded by something like "<account name|anonymous> asks: ", to make the commentary more intelligible.

**Comment by evazion** [comment]
Fixed in b185efb / 80219a0.

I'm not sure about the best way to handle `<img>` tags. Right now it just replaces the image with its alt text. That's mainly for DeviantArt, since on DeviantArt artists tend to use a lot of emoticons in their commentaries and stripping them completely can lose meaning.

I changed it to turn `<img>` tags into links, like this:

![image](https://user-images.githubusercontent.com/8430473/38159048-888d092a-3466-11e8-89b7-123c51c5f494.png)

Which still maybe isn't desirable in this case, but I'd rather leave the link in so the user can decide if it should be removed or not.
