### ISSUE TITLE
Post replacement: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by RaisingK** [r888888888/danbooru#3593]
Attempting to replace post #2250515, post #2350497, or post #2496208 yields:

    Errno::ENOTTY exception raised
    Inappropriate ioctl for device
    app/logical/remote_file_manager.rb:17:in `distribute_to_archive'
    app/models/post.rb:136:in `distribute_files'
    app/models/post_replacement.rb:82:in `process!'
    app/models/post.rb:1489:in `block in replace!'
    app/models/post.rb:1487:in `replace!'
    app/controllers/post_replacements_controller.rb:11:in `create'

The associated tag/source changes show up in the tag history, though they're marked as obsolete.

**Comment by evazion** [comment]
It's failing on `Net::SFTP.start`. I think the sftp connection is trying to request a password on stdin, which fails because stdin isn't a terminal. This gives the same ENOTTY error:

```bash
ruby -r 'net/sftp' -e 'Net::SFTP.start("localhost", "user")' < /dev/null
```

Not sure why it would be requesting a password. Maybe something with the ssh credentials is wrong? In any case, #3577 changed it to set the `non_interactive` flag, which will prevent it from asking for passwords.

The tag changes showing up in the tag history is because of #2972. Saving the post failed, so the changes weren't applied, but they were still sent to the post version archives before the save failed.

**Comment by r888888888** [comment]
I can SSH and SFTP to the other server from both servers fine.

**Comment by evazion** [comment]
What about connecting to raikou1 / raikou2 from sonohara / hijiribe?

**Comment by r888888888** [comment]
I've just added them.

**Comment by r888888888** [comment]
I also neglected to configure the storage manager. I'll add that now.

**Comment by evazion** [comment]
@RaisingK try again, should be fixed now.

**Comment by RaisingK** [comment]
Yep.
