### ISSUE TITLE
Javascript broken on post show pages

### ISSUE THREAD

**Issue by evazion** [r888888888/danbooru#3596]
Hiding the `data-uploader` data attribute broke this line:

https://github.com/r888888888/danbooru/blob/e006380567c0652ea35d4b2b5598e4d025b5d82a/app/assets/javascripts/blacklists.js#L150

**Comment by evazion** [comment]
Went ahead and pushed a temp fix. This will break `user:<name>` blacklists though. The `data-uploader` attribute would have to not be hidden for those to work.

**Comment by BrokenEagle** [comment]
Speaking just for myself, but I would like to see the ``data-uploader`` attribute somehow make it's way back to the post index.

It allows for me to at a glance determine which posts are one's that I've uploaded.  This goes into my calculations on how much I'll upload for a certain copyright or artist at any one time.  Additionally, I can quickly spot posts that I haven't uploaded so that I can check their tags and rating.  In general though, it's just nice to be reminded which posts are my uploads, since as it currently stands I'm unsure, which will basically force me to check the tag history every time I want to know, which is very laborious and unwieldy.

However, if the ``data-uploader`` attribute isn't brought back, at least I would like to see a ``data-is-user-uploader`` attribute added to posts, so that the above functionality can at least be preserved.  Since it'd only be visible to the user, it wouldn't conflict at all with the recent paradigm of not having the uploader necessarily be given credit for all to see.

**Comment by r888888888** [comment]
Exposing the uploader to everyone on the thumbnail defeats the purposes of the changes.

It should still be visible to moderators.

What about just exposing top tagger? In most cases it's identical.

**Comment by BrokenEagle** [comment]
Eh, well I'm sure that exposing the top tagger would be sufficient for most.

Also, I don't think it would hurt too much to highlight a user's own uploads with a ``data-is-user-uploader`` boolean attribute.  As it stands right now, I'm having to make calls to the API to get that information anyways with a user script.  But if not, then I can live with at least having that.

**Comment by evazion** [comment]
For blacklists and CSS purposes, it'd be sufficient to have a `data-uploader-id` attribute.

Looking up usernames for every thumbnail can take 20-100 memcache calls per pageload. The cost isn't that big, but it's not zero either. It'd be nice to avoid looking up usernames if they're not otherwise exposed.

**Comment by r888888888** [comment]
I've added uploader id and top tagger id in 485c3b01c7d809b5a83d96955d069b8bf0d87c29.
