### ISSUE TITLE
Unable to view images on Hijiribe/Sonohara when Danbooru domain is blocked

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3603]
From the [Danbooru forum](http://danbooru.donmai.us/forum_topics/9127?page=229):

> OniTea said:
> 
> Looks like after this fix thumbnails and images are forced to be from https://danbooru.donmai.us/ even if I'm currently on hijiribe\sonohara.
> Is it possibly to revert this, since danbooru.donmai.us is blocked in my country, while hijiribe\sonohara not. (So I can enter the site now, but can't see any image at all).
> VPN is always a way, but I'm trying to use it as less as possibly.

> Apox said:
> 
> I second this, I would be really happy if you guys have solved this problem ASAP as well. Thanks.

**Comment by evazion** [comment]
Related to #3599.

**Comment by evazion** [comment]
We want to be able to set this base url something like this:

```
StorageManager::SFTP(host, base_url: "#{request.protocol}://#{request.host}/data")
StorageManager::SFTP(host, base_url: "#{root_url}/data") # alternatively
```

So that the base url uses the host and protocol from the current request. That way if you're on https://sonohara.donmai.us, the base url will be https://sonohara.donmai.us. Problem is we can't access the `request` object outside of controllers/views, unless we put it in a global somewhere.
