### ISSUE TITLE
URL addons stripped when comments are created/edited

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3652]
Brought up by OOZ622 on Discord, and validated by myself on Testbooru.

http://testbooru.donmai.us/posts/12
http://testbooru.donmai.us/comments/25

Basically this affects commenting when navigating a pool or a post search.  The user either has to start the navigation over or go to the previous page.

**Comment by BrokenEagle** [comment]
Using the above example, when sending a tag edit to Danbooru with a PUT, it also sends the following the following data item...

``tags_query: pool:1``

...which the posts controller uses to redirect back to the URL.
https://github.com/r888888888/danbooru/blob/master/app/controllers/posts_controller.rb#L120

This was seen in the redirect response (HTTP 302) where the header contained...

``Location: http://testbooru.donmai.us/posts/12?tags=pool%3A1``

However, the comment edit/creation PUT/POST does not include a tag_query field, or really any URL addon field, and so when it redirects it can only send it back to the post as shown in that header response.

``Location: http://testbooru.donmai.us/posts/12``

There are two possible solutions to this...

1. Include the tag fields and other URL addons like it does with tag edits
2. Add/Replace the comment in place without reloading the page

**Comment by evazion** [comment]
https://github.com/r888888888/danbooru/blob/9cafffd20ad3a8e60bb52432b79fd372647b44c0/app/controllers/comments_controller.rb#L30-L43

We could use [redirect_back](http://api.rubyonrails.org/classes/ActionController/Redirecting.html#method-i-redirect_back) here instead of `redirect_to`. This would avoid the need to pass all the url params in manually. Actually, we could probably use this in the posts controller too.

It would also mean that replying from the /comments page keeps you on the /comments page, which I think would be nice.

**Comment by evazion** [comment]
Fixed in 83b96b4. Commenting in place would be better still, but it's more involved so I'll leave that for future work.
