### ISSUE TITLE
Deviantart commentaries fail fetching

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3654]
Examples:
https://danbooru.donmai.us/posts/3089593
https://danbooru.donmai.us/posts/3090262

Trying to fetch the commentary fails.

Network console shows the following:
```json
  {
    "success": false,
    "message": "undefined method `downcase' for nil:NilClass",
    "backtrace": [
        "/var/www/danbooru2/releases/20180416234708/app/logical/sources/strategies/deviant_art.rb:65:in `profile_url'",
        "/var/www/danbooru2/releases/20180416234708/app/logical/sources/site.rb:8:in `profile_url'",
        "/var/www/danbooru2/releases/20180416234708/app/logical/sources/site.rb:54:in `to_h'",
        "/var/www/danbooru2/releases/20180416234708/app/controllers/sources_controller.rb:9:in `show'",
        ......
    ]
  }
```

**Comment by evazion** [comment]
We were trying to fetch http://fav.me/dc8ykdg in order to get the work's uuid, but that page was returning a 403, even though it works in the browser. The [developer docs](https://www.deviantart.com/developers/errors) mention that requests that don't use HTTP compression may return a 403, so I enabled compression and now it seems to work.

I'm not sure why HTTParty wasn't using compression already. I think it's supposed to by default. The fact that we have to handle it manually may be a HTTParty bug.
