### ISSUE TITLE
Add timeout to prevent stuck uploads from remaining in limbo forever

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3659]
Quick example that happened to me yesterday and has been stuck on "processing" since then: https://danbooru.donmai.us/uploads/1815783
I just ended up reuploading the post, so even if it did succeed now (which seems unlikely), it'd fail anyway.

There should ideally be a timeout after which these uploads forcefully fail, to prevent them from being stuck forever.

**Comment by evazion** [comment]
As explained in #3700, what was happening was that if downloading the file timed out (usually due to temporary network problems), then the upload process would attempt to retry the upload, but due to faulty logic it would fail and leave the upload stuck in the 'processing' state.

This can be reproduced with this source: http://httpbin.org/drip?numbytes=100&duration=60&code=200.
