### ISSUE TITLE
Add a user perm for flagging

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#3662]
Some users should not be allowed to flag posts at all. They either use it to harass specific uploaders, or their flags frequently get overturned, or they misunderstand how it should be used despite repeated warnings. We should add a user perm that prevents a user from flagging.

**Comment by BrokenEagle** [comment]
Will all users start with this permission?  I would think so myself at least.  Otherwise it would be a nightmare for the mods to manage the new permission, plus it would prevent the vast majority of users that only browse and nothing else from flagging a post.  It would also cause quite the commotion if anybody was excluded without due cause.

Also, maybe we should consider whether any of the other activities should have a permission, such as commenting, editing the wikis, or making a forum post.

**Comment by nonamethanks** [comment]
Losing forum voice would probably be symptom of a behavior grave enough to deserve a ban - I can't imagine a mod would opt to mute someone and unmute them after a while instead of giving them a full package timeout for a couple of days. There are however several cases of users that were banned only because of their comments, in a relatively recent period too, so a privilege just for that (given by default to everyone) is probably not too farfetched.

But I have to admit that flags are really getting ridiculous lately. Still, giving mods the ability to stop users from flagging all by themselves should be considered carefully - there's the remote chance of it being used as retribution. Perhaps make it admin-only?

Also this is probably not going to even be considered, but perhaps replacing images should too be made a privilege like that - to be handed out to selected approvers instead of all of them, given what happened in the past. https://danbooru.donmai.us/forum_topics/14156 is not a very efficient substitute since we have only one person actively doing replacements (still, he's a hero for doing all of that by himself).

**Comment by r888888888** [comment]
This is an issue I am still internally debating. If someone is abusing flags despite a warning, maybe it's better to just outright ban them instead of trying to tolerate their behavior. But I view this current trend of 1% of users accounting for 90% of flags (estimating) as harmful.

**Comment by evazion** [comment]
I don't really see the need for a permission when a mod could just as easily say "stop doing this or be banned".

My issue with fine-grained permissions is I think they make the role-based model more complicated than it needs to be. It becomes harder to remember who can do what (let alone manage it correctly) when everyone has 5 or 10 separate privileges you have to keep track of, especially when you can no longer tell what someone can do just from their username color.

**Comment by BrokenEagle** [comment]
> I don't really see the need for a permission when a mod could just as easily say "stop doing this or be banned".

_When all you have is a hammer, everything looks like a nail._  In some cases, that might be like throwing the baby out with the bath water.  If the users do good elsewhere, why should we eliminate that just because they can't be trusted elsewhere.  If the user ratchets up the aggression upon having their permission revoked, further action could be taken then such as dropping user levels or banning.

> It becomes harder to remember who can do what (let alone manage it correctly)...

The user search index could be utilized to find these sets of users, just like it can be used now to find those with the current set of permissions/levels.

> ...especially when you can no longer tell what someone can do just from their username color.

I've been using various bells and whistles for all of the current set of permissions and statuses for quite a while now.

![image](https://user-images.githubusercontent.com/21149935/39213151-a0bd2cec-47c5-11e8-8fca-fc263980f9b3.png)

- Underline = unlimited uploads
- Checkmark = approver
- Star = super voter
- Strikethrough + black = banned (_not shown_)

Though if we're to officially support something like this, I would suggest using some kind of trailing/preceding icons for the permissions.  Other sites already add icons to usernames to denote different statuses.  Change the "Colored usernames" text to "Stylized usernames" in the settings menu, and have that set whether users see these various permission icons.

**Comment by swayze00** [comment]
Being a bit facetious here, but we could also [add a role for appealing.](https://isshiki.donmai.us/user-reports/post_appeals/2018-04-22_v1.html) We could add a role for voting on comments, since certain users like downvoting the comments of others in order to get them hidden. Point is, I think that if a user's flagging is egregiously out of line, they should be DMailed or demoted, not just have their flagging taken away. Quality control is what sets other image boards apart from the rest of the crowd.
