### ISSUE TITLE
Highlight non-gentags in post tooltip

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3664]
Something that has been suggested in the forums (https://danbooru.donmai.us/forum_topics/15163) and that would be pretty neat to have.

The idea is to make these tags show up in separate lines above the main tag list in the tooltip so that it's possible to tell with a glance, basically like it's already done in each post's page.

I know some of us spend a lot of time when tagging chracters from copyrights we don't know by opening each post and looking at the character tag list, so easier tagging would also be a reason to implement this.

**Comment by BrokenEagle** [comment]
The following is a mockup I posted on Danbooru in the thread mentioned above (https://danbooru.donmai.us/forum_posts/145529):

https://drive.google.com/open?id=18HpnSB0Ix3qoLNllEPHZMRzgcAQ9vI-F

**Comment by r888888888** [comment]
The last time we tried to type tags on previews it caused a major performance regression. Maybe the previous attempt wasn't optimized well but it's something to be aware of.

**Comment by evazion** [comment]
Yeah, I think doing it server-side would add an appreciable amount of overhead. You can see the difference if you compare [/uploads?limit=100](https://danbooru.donmai.us/uploads?limit=100) (which includes tag types) with [/uploads.json?limit=100](https://danbooru.donmai.us/uploads.json?limit=100) (which doesn't).

I think it could be done dynamically though (i.e. when you hover the thumbnail, some Javascript calls `/posts/{id}.json` and generates the tooltip).

**Comment by BrokenEagle** [comment]
I think in addition to the above, keep the title as is (expect maybe moving the rating and score up front) so that the user gets some instantaneous feedback upon hover.

Also, it would probably be best to have some kind of hover time threshold before a network call is made to avoid any non-needed calls by the user just scrolling down the page.  I'm not sure what that threshold should be (between 0.2 - 1 seconds...???), but if a test deployment of this can be made, we can get some user feedback before deployment.

**Comment by evazion** [comment]
> I think in addition to the above, keep the title as is (expect maybe moving the rating and score up front) so that the user gets some instantaneous feedback upon hover.

See #3666. I left this out because when I tried it, having the tooltip's content change made the tooltip jump around and made it feel jerkier to me.

The hover threshold is 0.3 seconds. This can be tuned from a userscript by setting `Danbooru.PostTooltip.QTIP_OPTIONS.show.delay`. `Danbooru.PostTooltip.render_tooltip` can also be overridden to experiment with the tooltip content.
