### ISSUE TITLE
Possibly exclude pixiv replaced twitter posts from posting penalties.

### ISSUE THREAD

**Issue by Signum1** [r888888888/danbooru#3751]
I am told that this is the place to discuss this, so here goes.

Myself and many others will post an image from Twitter in good faith, get blindsided by a Pixiv post that is dropped 30 minutes or so later. The moderators decide to approve the Pixiv post, reject the Twitter post, and it counts against the upload quota which is reduced, not mention the tagging work that goes with it and is sometimes just copied to the approved post.

The advice is to just keep track of artists that post twitter and pixiv posts within minutes of each other, but with the exception of some known artists that do this, it's hard to keep track. I understand Danbooru mods would want to delete unnecessary Twitter posts that are less than an hour old, but many cases quota users do get blindsided.

Poor anatomy, porn, or just subpar work I can understand being penalized, but I'm asking if there is a way to set up danbooru to exclude quality, but short time superseded Twitter posts from the penalty.

**Comment by hakusaro** [comment]
This ties heavily into the problem of upload sniping, and I'm not sure there's a great solution. If you're seeing uploads with Pixiv sources and yours aren't getting approved, it could be either:

* A Pixiv source got approved and yours didn't
* Someone with builder access uploaded it and bypassed the mod queue

I personally can't think of a way to mitigate this. The first one is somewhat easy -> if it's a child of a parent that's approved and they have a high similarity, just approve it? But it would still require parenting to work. The second case...maybe it's indicative that a post got uploaded, but wouldn't normally be approved?

If your only concern is the upload quota, then I think the easy solution would be to allow people to delete uploads that are still in the queue, and have those self deletions give upload slots back. A user can still go add the tags to the more up to date post and appear as the "top tagger," while simultaneously being able to remove items that don't matter anymore from the queue. This could even be tracked as a separate metric, e.g., "self removals."

For the most part, the mod queue works like a "yes, this goes in" rather than a "no, this stays out" system. In other words, it's not that people are _actively rejecting_ the post, but are simply _not approving it_. Another option could be to allow an item in the queue to be flagged as "already uploaded" but this gets into bleh territory with artist revisions and other situations where similar but not identical images appear in the queue.

I personally think self removals/self curation is a good solution. If a person wants to self curate and remove a post to get an upload slot back, they should be able to.

**Comment by nonamethanks** [comment]
Problem with that last suggestion is that bad uploaders would start deleting their own pending uploads when the three day mark is almost over, which would effectively make them able to upload 50 posts a day no matter what.

We already have some problems with users creating sockpuppets to go around the upload limit so it's a very real problem.

**Comment by hakusaro** [comment]
> We already have some problems with users creating sockpuppets to go around the upload limit so it's a very real problem.

Is this a problem on gold/platinum? Feature gating it to them (us) could work. One could argue that if you're in need of this feature, you're already invested in the site. But then it becomes a bit of a hinderance for the very real number of good uploaders who never upgrade to gold/platinum.

**Comment by Signum1** [comment]
Problem with that last suggestion is that bad uploaders would start deleting their own pending uploads when the three day mark is almost over, which would effectively make them able to upload 50 posts a day no matter what.

>

**Comment by Signum1** [comment]
So is it possible to reduce the self-deletion period down to 5 hours instead of three days to get around someone trying that?

**Comment by nonamethanks** [comment]
Yeah imo it's essential that the act does not require just one user. We've already seen the kind of abuse that stemmed from merely replacing a post. Deleting it has entirely new possibilities if the decision is left to one user only, some of which are purely malicious (such as annoying people in rush hour by sniping and then deleting after they've been fully tagged by someone else).

Uploader + Approver is probably a good combination, but there's also some issues of that. Deleting should be limited to pictures uploaded very recently (last one or two days maybe?) and there's still the issue of revisions that, if the approver is not careful enough, might be lost forever, even though their similarity rating would be very high.

**Comment by Signum1** [comment]
Well now I know what the expression "opening a can of worms" means. What's simple on the user side is a headache with Danbooru administration when they have to sort out potential abuses before  even touching the code. It's good this is getting attention. I hope the idea can be fine tuned.
