### ISSUE TITLE
Favgroup search negation doesn't work as expected

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3769]
I noticed this recently and had it confirmed by other users.  Basically, if a favgroup is empty, then it will return no posts, but if it has any posts than it works as expected.  This is different then how pools function, as negative searches on zero-count pools still returns posts.

The difference is that pool searches, both negative and positive, use the pool string on posts, whereas favorite groups use the post ID array for a favorite group.

https://github.com/r888888888/danbooru/blob/79ea6f7e6c37b5f017c4208b6bfce5ce8dcf3ec5/app/logical/post_query_builder.rb#L374

I'm guessing that the query has issues with negative searches like the above when the array is empty?  Maybe as a fix, have an array length check and if the array length is zero, then it won't add that query term.

```ruby
        if favgroup && favgroup.post_id_array.length > 0
          relation = relation.where("posts.id NOT in (?)", favgroup.post_id_array)
        end
```

The need for negation of an empty favorite group does have practical usecase.  For myself, when I populate a favorite group that I have emptied, I like to add the negation to the search terms. Then I can refresh the page to see what posts still haven't been added in case there are any that need to be.

As it is right now it's somewhat workable, but I have to seed the favorite group with at least one post before I can add on the negation search term, though it'd be nice to not have to do that extra step.

**Comment by evazion** [comment]
The query is basically this:

```ruby
Post.where("id not in (?)", [])
=> SELECT "posts".* FROM "posts" WHERE (id not in (NULL))
```

What's happening is that `id not in (NULL)` is always false, so the search returns nothing. It's false because in SQL comparing NULL to anything else is always false. `42 = NULL` and `42 != NULL` are both considered false, and likewise `42 in (NULL)` and `42 not in (NULL)` are also both false.

The correct way is this:

```ruby
Post.where.not(id: [])
=>  SELECT "posts".* FROM "posts" WHERE 1=1
```

This way allows Rails to generate the correct SQL to return the desired set of all posts.

Ref: https://stackoverflow.com/questions/12946004/issue-when-retrieving-records-with-empty-array
