### ISSUE TITLE
Post counts are off for most tags

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3783]
> skylightcrystal said ([forum #148958](https://danbooru.donmai.us/forum_posts/148958)):
> 
> The count for the overwhelming majority of used tags on the site is wrong. Some of these are by large margins, eg. under-rim eyewear says there are 17996 posts with the tag but actually there are less than 9900.
> 
> Perhaps a leftover side-effect of forum #148041? But it's a widespread issue affecting almost every tag on the site, and meaning that going to the last page of a single tag search frequently results in a redirect to the wiki or a "nobody here but us chickens" message rather than actually going to the end of the search results, even when the difference is relatively small.

I looked into it and validated that all of the tags on the page I checked were off of what they should be.

https://danbooru.donmai.us/tags?search%5Border%5D=count

I had started to think the problem could be fixed locally via tag corrections, so I fixed a few like the above-mentioned and the Touhou tag, but then I realized that perhaps all tags are off, and so it would take an exceedingly long time to do, and by that time the tag counts would most likely be off again.

**Comment by r888888888** [comment]
I don't have a whole lot of evidence for what's going on but here's an example of a call to `Post.update_tag_post_counts` that went in twice with the same tags:

Timestamp | App ID | App Name | Hash | Host | Pid | Real Agent ID | Stacktrace | User ID
-- | -- | -- | -- | -- | -- | -- | -- | --
2018-08-01 20:40:05 | 71204 | Danbooru | 15c1ppw43fph9 | sonohara | 6133 | 91814390 | app/models/post.rb:575:in `update_tag_post_counts` app/controllers/posts_controller.rb:52:in `update' | 406536
2018-08-01 20:39:55 | 71204 | Danbooru | 15c1ppw43fph9 | hijiribe | 28402 | 91814387 | app/models/post.rb:575:in `update_tag_post_counts` app/controllers/posts_controller.rb:52:in `update' | 406536

These are 10 seconds apart but it looks like the request was sent twice to two different servers, and because the post is never locked they both pull the same data and double increment for the same change.

Probably some sort of locking mechanism with timestamps needs to be introduced.

**Comment by r888888888** [comment]
I'm content to just rely on probabilistic updates to fix the counts. For now I'm tying it to the process that updates the related tags since they're both correlated to count.
