### ISSUE TITLE
Batch bookmarklet for tumblr reports wrong posts as already uploaded

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3873]
[Example](https://danbooru.donmai.us/uploads/batch?utf8=%E2%9C%93&batch%5Burl%5D=http%3A%2F%2Ftynytnm.tumblr.com%2Fpost%2F177723855966%2F&commit=Fetch): opening the first link shows "This post was probably already uploaded (post #3246912)", but [that post](https://danbooru.donmai.us/posts/3246912) is not the right one.

This is very misleading and will lead to people skipping otherwise perfectly fine images.

**Comment by evazion** [comment]
That dupe check is performing a `source:<canonical_url>` search, where the canonical url is the html page url for sites like Twitter or Tumblr, or the image url for sites like Pixiv or Deviant Art.

Searching the page url will generally return false positives, since gallery images usually share the same page url. Technically even the image url can return false positives, since it's possible for revisions to share the same image url.

Ultimately, I think it would be better to do an md5 dupe check here instead of a source check. This should technically be possible now that uploads are asynchronous, but I think it would require more refactoring.

Failing that, probably the best thing to do would be to show the actual thumbnails found by the `source:<url>` search, instead of just showing a `post #1234` link.
