### ISSUE TITLE
Using numbers for tag completion

### ISSUE THREAD

**Issue by ampersham** [r888888888/danbooru#3892]
I have a suggestion for tag completion, which is that as typing a tag the suggestions should be prefix with a number, that when you type completes the tag using that suggestion. Illustrated below:
https://files.catbox.moe/h0oy73.png

I should, in that case, be able to type 6 to complete the tag to aqua_sailor_collar after typing 'asc'.

**Comment by evazion** [comment]
What about tags that contain numbers? If you type `re5`, does that mean `resident_evil_5` or the 5th `re` tag? I think typing Ctrl+1-9 or Alt+1-9 would be better. It's an extra key, but it avoids ambiguity.

To be honest, this is why I think it'd be better if you had to type `/asc` to trigger abbreviations. Then your only options would be `alternative_skin_color` and `aqua_sailor_collar` and you could just use down arrow. The real problem is sometimes you want to type an abbreviation but too many other results outrank it.

**Comment by r888888888** [comment]
Instead of numbers how about function keys? It looks like the jquery plugin supports it. The only tricky part would be somehow conveying that information in the dropdown. Maybe in lieu of the post count.

**Comment by chinatsu-chan** [comment]
By function keys I assume you mean the row on the top of a kb like F1, F2, etc? That would be cumbersome to me, to move my hands from their resting position that reach all letters to stop and reach up, and have to look, to select an F-key.

As far as the re5 situation, I don't think it's a big deal. I think that it should default to selecting the number tag as shown in my picture. Otherwise you can just use the arrow keys to select the Resident Evil option. Further, if you select the Home key, it should move the selection to option 1, if you select the End key it should select the last numbered option; you would need to still click enter to complete. This would just allow for easy navigation/toggling through choices, whereas selecting a number should just complete the tag (but if there's a tag with a number as eva pointed out, perhaps just select the numbered tag and let you either continue toggling through tags or hit tab to complete).
