### ISSUE TITLE
Force "animated_gif" tag on applicable images

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3915]
The issue came up with https://danbooru.donmai.us/posts/3257748 - it didn't have the animated_gif tag, and so the sample was being rendered as an artifacted, downscaled still image (https://danbooru.donmai.us/data/sample/sample-42ea5c99074738fa93e7bef5c685f29b.jpg).

animated_gif should work like the various resolution tags, or ugoira, webm, etc, in that it should be automatically added to posts and be considered a permanent, irreplaceable tag for the posts where it was assigned automatically by the site.

**Comment by crs00** [comment]
Animated PNG is also removable and should be a forced tag.

**Comment by evazion** [comment]
These tags aren't forced because the animated_gif detection isn't 100% accurate. The check is just that the gif has multiple frames. But it's technically possible to have a gif with multiple frames where each frame is identical, such that there's no actual visible animation.

This is similar to video_with_sound, where we check whether the video has an audio track, but it's possible for the audio track to be silent.

We could check that the frames aren't all identical, but that's easier said than done. Most libraries don't support animated PNGs, so it's difficult to even extract the frames for those. There are also denial-of-service considerations. It's possible to generate absurdres gifs where the file itself is small, but it takes gigabytes of ram to decompress the file into memory ([link](https://bomb.codes/bombs#images)).
