### ISSUE TITLE
Lots of 502 in the past few days

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3932]
As the title says, it seems since last week the site's been showing a noticeable increase in random 502s, and it's been pretty slower than usual in general.

Reported in https://danbooru.donmai.us/forum_posts/150921 and https://danbooru.donmai.us/forum_posts/150728. I've also been experiencing them a lot.

**Comment by r888888888** [comment]
According to [Matomo](https://matomo.donmai.us/index.php?module=CoreHome&action=index&idSite=1&period=day&date=yesterday#?idSite=1&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1) traffic has been marginally up, from 200k visitors daily to 260k visitors daily. I was also running an rsync on hijiribe that probably wasn't helping any; that's done now.

**Comment by Unbreaky** [comment]
Any ideas when this will be fixed? Because it's still going on.

**Comment by r888888888** [comment]
Are people still seeing this?

**Comment by deusexcalamus** [comment]
> 
> 
> Are people still seeing this?

I don't think I've seen more than 1-2 in the past 24hrs.

**Comment by Unbreaky** [comment]
Same here, not many since a few days back.

**Comment by evazion** [comment]
According to New Relic, page loads are significantly faster on average since the migration, twice as fast as the old servers:

![image](https://user-images.githubusercontent.com/8430473/46981338-7b303580-d09d-11e8-834b-7aff1c11da60.png)
![image](https://user-images.githubusercontent.com/8430473/46981347-85eaca80-d09d-11e8-94d0-2062255bc6b6.png)

The spikes above correspond with periods of 502s. I think it's correlated with spikes in the number of slow json/xml API requests being performed:

![image](https://user-images.githubusercontent.com/8430473/46981546-74ee8900-d09e-11e8-85ae-58a0c849e40b.png)

It's hard to tell what was happening, since the user ids and actual searches being performed weren't logged, but I think some bots might have been hammering the site with slow searches, with not enough unicorn workers to handle the load.
