### ISSUE TITLE
Reemphasize banned artists on uploads page

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#3964]
Unbreakable (@Unbreaky) brought up on Discord that the banned artist notification on the uploads page seems to have been deemphasized.

How it currently looks:
![image](https://user-images.githubusercontent.com/21149935/47622882-90f32100-dac7-11e8-80dc-6bdc38024778.png)
How it used to look?:
![image](https://user-images.githubusercontent.com/21149935/47622870-6b661780-dac7-11e8-8f17-a1b85090b0fa.png)

Perhaps also adding some blinking effects? It's possible with CSS and is more likely to draw the eye, although I don't know if that would be too intrusive.

**Comment by BrokenEagle** [comment]
AFAIAA, images from banned artists should be avoided as uploads.  At least, I've always sought to avoid uploading from them, though I've done a few times accidentally since the artist info wasn't populated (like from Yandere).

**Comment by evazion** [comment]
If they shouldn't be uploaded, I think it would make more sense to block the upload completely. Or at the least, have a written warning. Otherwise I don't think it makes a lot of sense to warn about something that's not really disallowed. People typically aren't punished for uploading from banned artists (unless they do things like deliberately not tagging the artist).

**Comment by BrokenEagle** [comment]
Well, I haven't really heard a solid policy either way.  I'll leave it to higher hands to decide.
