### ISSUE TITLE
Problems with create artist function

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4028]
Brought up in [topic #15843](https://danbooru.donmai.us/forum_topics/15843).

1. Pixiv places the account name in the artist field, and the artist name in the others field.

    Instead, both should be placed in the other names field, and the user should manually decide the artist's name.  Also, not sure if this is being done, but duplicate names should be discarded, in case the artist name and the account name are the same.

2. For Pixiv, Danbooru does not add the STACC link to the list of URLs.

    Example: https://www.pixiv.net/stacc/some_account

3. If the artist name is added to the other names field as is, even if it includes spaces.

    Since spaces are now used to delineate other names, all of the spaces for the artist name should be converted to underscores instead.

4. Different URLs with only a change in caseness can be added to the account.

    Granted, with some domains caseness matters.  However, for many/most caseness does not matter.  Perhaps something could be added to the site strategies that would indicate whether caseness matters for that site or not, and if a strategy does not exist, then treat the URL as if different cases are different links.

5. There is still confusion on which separator to use, i.e. commas vs spaces.

    Not sure what to do about this one. I have seen one site that uses a scheme where when you use the separator, it creates a discrete clickable entry to the left of the text input with a clickable "x" if you want to delete it.  The benefit to that system is that it is very visually obvious what will get added, however it would require a lot more coding.

    Another potential idea instead of the above would be to display the names that would be added in a visually separate form below the textbox, like something with borders.

**Comment by evazion** [comment]
Fixed 2 and 3, and fixed duplicate other names for 1. For 5, I added a notice to use spaces instead of commas:

![image](https://user-images.githubusercontent.com/8430473/50494716-9a770780-09ea-11e9-89de-d0d17dfc0dc3.png)

> Pixiv places the account name in the artist field, and the artist name in the others field. Instead, both should be placed in the other names field, and the user should manually decide the artist's name.

As discussed in topic #15843, the stacc name isn't ideal, but I think it's better than users not making artist tags because they can't figure out a better name.

> Not sure what to do about this one. I have seen one site that uses a scheme where when you use the separator, it creates a discrete clickable entry to the left of the text input with a clickable "x" if you want to delete it. The benefit to that system is that it is very visually obvious what will get added, however it would require a lot more coding.

[selectize.js](https://selectize.github.io/selectize.js/) could be used for this. I'm sure there are other plugins too. One issue with systems like this, though, is that it's usually harder to edit individual words or to copy/paste the entire string.

> Different URLs with only a change in caseness can be added to the account.

I haven't looked closely at which sites are case-sensitive, but I know that at least stacc names are. See https://www.pixiv.net/stacc/LuoXin vs https://www.pixiv.net/stacc/luoxin.

Probably we'll need a strategy-dependent method for normalizing artist urls in general. We also should normalize http/https differences and trailing slash differences (http://www.pixiv.net/stacc/uroobnad vs https://www.pixiv.net/stacc/uroobnad/).

**Comment by BrokenEagle** [comment]
I think one thing that can at least be eliminated is domain names for case-sensitivity. Case sensitivity isn't allowed for domain names.

**Comment by BrokenEagle** [comment]
I brought this up in Discord, but it seems like the **Create artist** and the profile links (under **Fetch source data** on the uploads and post edit) are direct links instead of opening up into a new tab. For myself at least, I can't think of any reason why I would want to directly navigate to any of those pages from an upload or post edit.

Actually, looking over all of the links on the edit form though, it looks like most/all should open up into a new tab instead of being direct links. The one exception would be the related tags, as clicking them will toggle the tag on or off rather than going to that page.
