### ISSUE TITLE
URL correlation mistakes on artist_versions HTML endpoint

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4036]
Noticed the following recently.

https://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=90353&limit=1

![image](https://user-images.githubusercontent.com/21149935/50721645-a9f3f180-1077-11e9-924f-43915961c841.png)

For some reason, it thinks that the new Pixiv links are related to the deleted Nicolist links.

**Comment by evazion** [comment]
The current algorithm is basically that two urls are considered a match if they have at least 25% overlap. Here both urls have `http://www.` in common, which makes up just over 25% of the string, so they're a match.

More precisely, the algorithm is that we compute the Levenshtein edit distance between all pairs of strings and call two strings a match if the distance between them isn't too large, where "too large" is "more than 25% of the length of the first string".

The threshold is only 25% because if it's too high edits like

```
- http://this-is-a-very-long-artist-name.deviantart.com
+ http://www.deviantart.com/this-is-another-very-long-artist-name
```

won't be matched. This can be tuned, but there will probably always be borderline cases.
