### ISSUE TITLE
Some pixiv sketch links can't be added or block the editing of a post's tags

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#4043]
Latest example:
https://img-sketch.pixiv.net/uploads/medium/file/853888/3270289746156961930.png
I had to remove it from https://danbooru.donmai.us/posts/2428340 to edit its tags, but now I can't add it again.

The error is the following:
```ruby
ActiveModel::RangeError exception raised
3270289746156961930 is out of range for ActiveModel::Type::Integer with limit 4 bytes

app/controllers/posts_controller.rb:47:in `update'
```

**Comment by evazion** [comment]
The root problem was that illust id parsing was too loose. Effectively, anything that looked like `*.pixiv.net/*/1234.jpg` was interpreted as an illust id, which was incorrect for img-sketch.pixiv.net urls. This made saving the post fail because the id was too large to store in the post's pixiv_id field.

I tightened up the parsing. Hopefully this won't break anything. Pixiv has a bunch of legacy url formats that we still have to support because they're still used in old posts.
