### ISSUE TITLE
FontAwesome CDN is slow/blocking

### ISSUE THREAD

**Issue by r888888888** [r888888888/danbooru#4058]

**Comment by evazion** [comment]
Self hosting it would be a good idea. Sometimes users block third party CSS / JS then get confused when things don't work.

https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

**Comment by r888888888** [comment]
I didn't even realize this was an option. I assumed they would mandate hosting because of the licensing requirements.

**Comment by evazion** [comment]
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

Looks like you can use their private NPM registry but you have to configure an auth token to get access. Not sure how this works though in a non-production setting where you don't have an auth token.

**Comment by evazion** [comment]
https://status.fortawesome.com/incident/119

FontAwesome had an issue with their CDN returning 500 errors. This caused icons to break on Danbooru. I've switched to the self-hosted version to fix this.

It turns out that we're only using free icons so we don't need the pro version, which is good because configuring the pro version is a pain. They really want you to put your auth token in your git repo, which is no good for public repos.
