### ISSUE TITLE
Skip processing of old SavedSearch.populate jobs

### ISSUE THREAD

**Issue by kittey** [r888888888/danbooru#4127]
When the delayed jobs queue workers die, thousands of jobs accumulate quickly, and it takes a long time to catch up after the queue workers are restarted. Many of those jobs are `SavedSearch.populate`, which seem to be slower than most other delayed jobs. Not only are they slow, but the results from several hours ago are useless because the user triggering that job is long gone to do something else.

To speed up catching up with a backed-up queue, processing of `SavedSearch.populate` jobs should be skipped if they’re older than a certain amount of time, maybe 15 minutes. If the user wants to view saved searches after that time, a new job will be triggered anyway.

**Comment by evazion** [comment]
The underlying issue with job workers randomly dying was fixed, so I don't think this is necessary any more.

I'm reluctant to delete jobs automatically because the job queue getting backlogged is something that should Never Happen™ in normal operation. If it does happen then something's gone wrong and it needs to be investigated.
