### ISSUE TITLE
Remove preceding/trailing whitespace from all inputs

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4136]
Currently a trailing or preceding space can cause a search input to fail, such as a username input. Stripping these out upon processing will be more user-friendly as it won't cause searches to fail just because of a space.

Since spaces are useful for some inputs, such as body_matches, strip out all preceding/trailing whitespace and only  them in by exception, sort of like a white-list.

**Comment by evazion** [comment]
The narrow issue of stripping whitespace in username searches was fixed in 7b8584e3b0. The broader idea of stripping whitespace from everything is something I'm very wary of. It's too easy to break things in some subtle way without realizing it. Passwords are an example of something that would be very subtly broken by stripping whitespace.
