### ISSUE TITLE
Don't allow invalid prefix combinations for autocomplete

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#4174]
![image](https://user-images.githubusercontent.com/21149935/65188732-f293e500-da23-11e9-81bd-19358dd83360.png)

It can be fixed by changing the following code though:

https://github.com/r888888888/danbooru/blob/4dfa645550771be9f2de2015366f834b05b4b177/app/javascript/src/javascripts/autocomplete.js.erb#L286-L290

To the following:

```javascript
  match = term.match(/^([-~]+)(.*)$/);
  if (match) {
    if(match[1].length > 1) {
        return {}
    }
    operator = match[1];
    term = match[2];
  }
```

Basically, it grabs up all operators, and if the count is greater than zero it returns an empty hash, which will cause the autocomplete to close out.

**Comment by evazion** [comment]
I ended up rewriting the parser because it also allowed invalid tagtype + metatag combinations, such as `char:rating:s`. In the new parser, extra operators are swallowed up and effectively autocorrected to the first operator. So for example, `--tagme` completes to `-tagme`. I think this is more useful than returning nothing at all, since it's probably what you meant to type.
